### PR TITLE
WIP: aspectbase.__eq__: Add check language

### PR DESCRIPTION
**Pull request by newbazz**
The `__eq__` function now check language.

Closes https://github.com/coala/coala/issues/4391

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by blazeu** [comment]
The shortlog tag ideally has ["The file or class or package being modified."](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog), not function name :)

**Comment by blazeu** [comment]
If you've read my deleted comments (sorry, I didn't mean to delete it !!), don't worry about it, it seems like there's a few commits already that has function name in the shortlog tag.

Anyway, it seems like you need to modify the unit test as well.

**Comment by newbazz** [comment]
@blazeu yeah I have read it!! I will surely change the commit msg, and btw which unit testing r u talking abt?

**Comment by blazeu** [comment]
No, I said don't worry about it (don't change it).

See the travis link i gave to you, it has list of test file that are failing and the complete log as well.

**Comment by newbazz** [comment]
@blazeu yeah i saw that link but m not able to figure out how to solve it, can you help me with this?

**Comment by newbazz** [comment]
I think i dont need ti change the collectionTest.py, do i?

**Comment by userzimmermann** [comment]
@newbazz @blazeu No need to change tests. They are failing due to https://github.com/coala/coala/pull/4109 not finished yet

But even then it anyway needs at least one new test case for a language mismatch

**Comment by userzimmermann** [comment]
@newbazz Please also change the commit message to `aspectbase.__eq__: ...` Otherwise it could be any `__eq__` ;)

**Comment by userzimmermann** [comment]
@newbazz @blazeu Please also take a look at https://github.com/coala/coala/issues/4391#issuecomment-340605096

**Comment by newbazz** [comment]
@userzimmermann is the comment to be added as a test case?

**Comment by userzimmermann** [comment]
@newbazz No need for testing the `is` operator ;) But yes... as already mentioned in https://github.com/coala/coala/pull/4813#issuecomment-340602505 above: Some `!=` test has to be added for aspect instances with different `.language`. Either in `tests/bearlib/aspects/InstanceTest.py` or `.../SubTest.py`. The latter already contains a good `test__eq__` example

**Comment by newbazz** [comment]
@userzimmermann can you plz help me in this.

**Comment by newbazz** [comment]
I dont know much abt aspects so....

**Comment by userzimmermann** [comment]
@newbazz To make it work, we first have to get https://github.com/coala/coala/pull/4109 done

But you should already take a look at https://github.com/coala/coala/blob/41d9412f993f3240d4edaf456e5e4a546245bc9c/tests/bearlib/aspects/SubTest.py#L40

This test could be extended with checks like `assert SubAspect('py') != SubAspect('cs')`...

**Comment by newbazz** [comment]
okk I will surely take a look at it, but for now this issue is on hold right?

**Comment by userzimmermann** [comment]
@newbazz Yes. It's blocked for now. So give https://github.com/coala/coala/pull/4109 a review... :)

**Comment by alphadose** [comment]
@newbazz the commit header should consist of the name of the file not the function within it. :)

**Comment by newbazz** [comment]
@alphadose yeah that point has already been told to me by @userzimmermann .

**Comment by newbazz** [comment]
@userzimmermann has https://github.com/coala/coala/pull/4109 solved?

**Comment by userzimmermann** [comment]
@nvzard The `location: ...` in the shortlog doesn't need to be a filename. In this case, using the file name `bearlib/aspects/base.py: ...` and then explaining that a change was made to `aspectbase.__eq__` would unnecessarily bloat up the shortlog and violate its length constraint. The location just needs to be clear, unique, and intuitive. And that's the case in the current form

@newbazz It's ok to leave the shortlog as it is

**Pull request closed without merging**
