### PR TITLE
setup.cfg: Shift fail_under to another section

### PR DESCRIPTION
**Pull request by aashraybhandar1**
Moving fail_under to coverage section

Fixes https://github.com/coala/corobo/issues/112

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by gabru-md** [comment]
It seems that the version of `setuptools` in your `travis build` is `35.0.2` but `.misc/check_setuptools.py` requires it to be `17.0`.
I tired this issue on my end , and it seems that even after executing the command `pip install setuptools==17` , the setuptools version is still the latest release.
So there is nothing wrong with your commit. It is with the specific command `pip install pip==9 setuptools==17`

Let me check. But do make sure to ping on `gitter` regarding this.

**Comment by aashraybhandar1** [comment]
hey @gabru-md how to proceed can you help me?

**Comment by gabru-md** [comment]
I have already issued a PR for changes in .travis.yml so that it can be resolved. Just wait till it gets merged.

**Comment by aashraybhandar1** [comment]
thanks

**Comment by newbazz** [comment]
Try to rebulid your pr.

**Comment by meetmangukiya** [comment]
This PR doesn't belong here @aashraybhandar1 This has to be a PR in corobo

**Pull request closed without merging**
