### PR TITLE
ConsoleInteraction: Suggest Ctrl+Z to exit on win

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by Nosferatul** [comment]
ack 9e95f57

**Comment by Nosferatul** [comment]
rebase 👍

**Comment by sils** [comment]
reack https://github.com/coala/coala/pull/3429/commits/16915add3e0eeecde44f07b83cf50500f4434ac3

**Comment by sils** [comment]
3918f71 reack

**Comment by jayvdb** [comment]
I have zero confidence in Ctrl-Z on Windows being similar enough, in Python, but at least it is better than Ctrl-D ;-)

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
