### PR TITLE
coalaCITest.py: Remove unused variables

### PR DESCRIPTION
**Pull request by Jassu225**
Fixes https://github.com/coala/coala/issues/4885

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

### CODE REVIEW

**Comment by nkprince007** [comment]
ack https://github.com/coala/coala/pull/4908/commits/252f5931b5ab8288594ff579572f917e7da54432

**Comment by shreyateeza** [comment]
Hello. I would like to work on this issue.

**Comment by nkprince007** [comment]
Hi @shreyateeza. This pull request has already been taken up and contributed by someone else. Please choose some other issue at https://coala.io/new

**Comment by Makman2** [comment]
Please use `Closes` instead of `Fixes` as keyword as the issue you're fixing is not a labelled as bug.

**Comment by Makman2** [comment]
unack 252f593

**Comment by nkprince007** [comment]
Hey @Jassu225, please amend you commit message to `Closes` instead of `Fixes`.

**Comment by Makman2** [comment]
Closing due to inactivity.

**Pull request closed without merging**
