### PR TITLE
TypeScript.py:Change aliases to type tuple

### PR DESCRIPTION
**Pull request by ananyaarun**
closes https://github.com/coala/coala/issues/5463

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by sks444** [comment]
Hey @ananyaarun, the changes you made look good ;)

But now, you have to fix your commit message and squash it into one.

Please follow our [commit guidelines](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html) to fix the same.

Leave a comment here if you face any problem, we will help you ;)

**Comment by ananyaarun** [comment]
@sks444 Thanks !! I tried those commands but they don't seem to work as i have made my commits through GUI actually. How do i go about it now ? Shall i make another commit with a proper commit message this time ?

**Comment by jayvdb** [comment]
Almost all GUIs let you use the command line `git` as well.  After you use `git`, the GUI should update automatically, or maybe it has a "refresh" button.

**Comment by sks444** [comment]
No, why another commit? That would make it `3` commits, and only one is acceptable. Please follow the steps, I suggested and describe the problems you are facing.

**Comment by ananyaarun** [comment]
@sks444 
This is what i get when i do git log now 
latest0
But i am not able to push these changes due to errors.

**Comment by ananyaarun** [comment]
@sks444 I am sorry ! I will push only the changed files next time onwards. Did not realize this time.

**Comment by ananyaarun** [comment]
@sks444 I am so sorry ! I deleted the unwanted files.

**Comment by sks444** [comment]
Hey @ananyaarun, Nothing to be sorry about. Come on Gitter before doing another push, we will discuss it further.

**Comment by sks444** [comment]
Great, you have learned the basics of `git` now, but I just realized you have made this PR from your master;
Now, sadly you have to close it, and make a new PR from another branch.
(*But, please read the docs properly from now on, before creating a PR*)

**Comment by ananyaarun** [comment]
okay sure.

**Pull request closed without merging**
