### PR TITLE
Fixed typos (fixes issue #2935)

### PR DESCRIPTION
**Pull request by anjabeth**
Basic typo fixes in lines 149 and 87. 

Fixes Issue #2935.

### CODE REVIEW

**Comment by sils** [comment]
Hi, it looks like you did your changes via the GitHub UI - you'll have to grab the git CLI now to fix up the commits. We're a bit strict here and we do that so you learn it. If you don't want to contribute on long term we can do that for you but if you intend to do more than one issue (which is usually the case for newcomer issues) you'll want to do this.

Essentially I'd recommend squashing the commits together (git rebase -i origin/master, use `fixup` instead of `pick` on the second commit; you gotta have two git remotes: our repo and your fork whereas you rebase onto our master) and make your commit message comply to coala.io/commit - instead of `Fixing ...` you'd rather do `README: Fix typos`

Let us know if you need any help, we're there for you at coala.io/chat as well.

**Comment by sils** [comment]
fixing the commit message will also fix all those red checks on github ;)

**Comment by sils** [comment]
@anjabeth should someone take this over?

**Comment by anjabeth** [comment]
Thanks for the rebase instructions! That's what I couldn't figure out how to do properly. I'll fix it this morning, so I can handle it. I appreciate all the pointers/you guiding me through it - thanks!

**Comment by anjabeth** [comment]
Never mind, looks like someone else already handled it - I'll close this one.

**Pull request closed without merging**
