### PR TITLE
Undefined name: import sys

### PR DESCRIPTION
**Pull request by cclauss**
__sys__ is used on line 45 but it is never imported.  This will probably raise __NameError__ at runtime instead of __sys.exit()__ as expected.

[flake8](http://flake8.pycqa.org) testing of https://github.com/coala/coala on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./tests/collecting/collectors_test_dir/bears/incorrect_bear.py:1:7: E999 SyntaxError: invalid syntax
The Zen of Python, by Tim Peters
      ^
./coalib/coala_delete_orig.py:44:5: F821 undefined name 'sys'
    sys.exit(main())
    ^
1     E999 SyntaxError: invalid syntax
1     F821 undefined name 'sys'
2
```

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by cclauss** [comment]
@li-boxuan Is this an active project?  I do not see a pull request that has passed the continuous integration tests in more than a year.

**Comment by li-boxuan** [comment]
> Is this an active project?

Yes. If you join the gitter channel, you'll find the community is friendly and quite active. (see newcomer guide for details)

> I do not see a pull request that has passed the continuous integration tests in more than a year.

That's not true ;) Not sure how you come up with this observation

**Comment by cclauss** [comment]
https://github.com/coala/coala/pulls  # None passed
https://github.com/coala/coala/pulls?page=2  # None passed
https://github.com/coala/coala/pulls?page=3  # None passed
https://github.com/coala/coala/pulls?page=4  # None passed
https://github.com/coala/coala/pulls?page=5  # One passed from April 2017

Similar results when looking at closed PRs.

**Comment by li-boxuan** [comment]
> https://github.com/coala/coala/pulls # None passed

Incorrect. You can see many of them are in `Some checks haven’t completed yet` state, which is expected, because `review/gitmate/manual` and `review/gitmate/manual/pr` will pass only when a maintainer approves it and gives ack. Anyway, this is not the right place to discuss this. You may want to go to https://gitter.im/coala/coala if you still have doubts.

**Pull request closed without merging**
