### PR TITLE
.coafile: Fix docstring typo builting --> builtin

### LINKED ISSUE #5949: Typo in coafile
In [coala/.coafile](https://github.com/coala/coala/blob/master/.coafile) ,
In line 88, the word should be `builtin` instead of `builting` .

### PR DESCRIPTION
**Pull request by pavanrkadave**
This fixes the typo in .coafile from 'builting' --> 'builtin'

Closes #5949

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by pavanrkadave** [comment]
I have made the changes, please review it.

**Comment by pavanrkadave** [comment]
Thank you so much for the help! and sorry for making so many mistakes, i am new to open source.

**Comment by pavanrkadave** [comment]
Thanks! @uds5501 . I have changed that.

**Comment by KVGarg** [comment]
Please describe your changes and which issues does this PR closes in the [commit body](https://github.com/coala/coala/pull/5951#issue-244263230)

**Comment by pavanrkadave** [comment]
Hi @li-boxuan, I still getting merging is blocked.

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5951/commits/cb2b29f7ec662821c64189da138e966700a64726

**Pull request merged**
