### PR TITLE
coalib/parsing/DefaultArgParser.py: Reorder

### PR DESCRIPTION
**Pull request by pratham-pc**
This changes the order of logging
shown in help to
Debug -> Info -> Warning -> Errors

Fixes https://github.com/coala/coala/issues/3617

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [x] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

**After you submit your pull request, DO NOT click the 'Update Branch' button**

### CODE REVIEW

**Comment by nemaniarjun** [comment]
Hey! The change seems great. Just a small change. The filename in the commit head doesn't need to be the full path.

**Comment by aptrishu** [comment]
The Changes -> This changes
in commit message.

**Comment by pratham-pc** [comment]
Thank you @aptrishu and @nemaniarjun

**Comment by yash-nisar** [comment]
We need to close this as https://github.com/coala/coala/issues/3617 has been resolved ! @aptrishu @meetmangukiya

**Pull request closed without merging**
