### PR TITLE
Remove use of line continuation

### PR DESCRIPTION
**Pull request by IamRaviTejaG**
Remove use of line continuation completely.

Closes https://github.com/coala/coala/issues/4552

### CODE REVIEW

**Comment by shreyans800755** [comment]
@IamRaviTejaG 
I think you have missed some of the occurrences of backslash.
Some of them are in file `docs/Makefile`. Look at https://github.com/coala/coala/blob/master/docs/Makefile#L88.

You can do grep to search all the occurrences.

**Comment by jayvdb** [comment]
This is about line continuations in Python only.

And this isnt fixed until this bit is done:

> Add it to the banned word list in .coafile

**Comment by IamRaviTejaG** [comment]
@jayvdb How to add the symbol to the banned words list? Need help.

**Comment by nvzard** [comment]
@prnvdixit can you please help with this PR?

**Comment by prnvdixit** [comment]
1. I am not sure about banned words in ```.coafile``` either 😉
2. Also, you should try not to push more than one PRs to a single issue (that hinders in keeping reviews at one place). In case of any problem, head over to gitter channel and ask the same - Someone would be around to help you 😃. 👍

**Comment by IamRaviTejaG** [comment]
@prnvdixit I believe all the python occurrences have been fixed. The `grep` search does show up some results which are in the MAKEFILE etc. And from @jayvdb 's comment above, it seems the Python occurrences have been fixed as expected. Any help will be appreciated.

**Comment by IamRaviTejaG** [comment]
@ayush1999 Yeah, that's where I'm stuck actually. How to add the '/' to the banned words list is something I'm yet to figure out. Please help me if possible. :)

**Comment by troublemagnet** [comment]
@IamRaviTejaG Banning words is equivalent to black listing words. For example if you read the current .coafile, last line we have black listed the word `urlopen` to encourage the use of requests. If you add to the keyword "\\" you'll essentially ban the back slash.

**Comment by IamRaviTejaG** [comment]
@troublemagnet Sure, I'll work on that today. Regarding the commit, do you believe the changes in the files have been done correctly? Or are there any other occurrences of `/` that I might have missed?

**Comment by troublemagnet** [comment]
@IamRaviTejaG you did miss few of the occurrences. Also please update the method doc strings too.

**Pull request closed without merging**
