### PR TITLE
SpaceConsistencyTestBear.py: Edit param options

### PR DESCRIPTION
**Pull request by Projjol**
Remove period at the end of param options as it doesn't play well
with the following parenthesis.

Fixes https://github.com/coala/coala/issues/2798

### CODE REVIEW

**Comment by Projjol** [comment]
Hey @Flap-Py @dracarys09 @arush0311 could you review this please? :)

**Comment by arush0311** [comment]
The changes looks alright :). ack https://github.com/coala/coala/commit/5af686a0dda7fdde7e22fa80959191903ee6dbea

**Comment by Projjol** [comment]
Hey @arush0311 I had to amend the commit message, the new hash is a9d5412 :)

**Comment by sils** [comment]
Hey,

we use some bug prediction in coala which relies on the `Fixes` keyword in commit messages. To get good results from that we need to use `Closes` for normal issues instead of `Fixes` which should only be used for real bugs. (See also [the commit message docs](http://coala.io/commit).)

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by sims1253** [comment]
ack 85d1fb4

**Comment by sims1253** [comment]
this has to be rebased

**Comment by sils** [comment]
don't do the update branch thing :/ I'l take care

**Comment by Projjol** [comment]
@sils sorry! What would be the right way to do this?

**Comment by sils** [comment]
coala.io/git but don't do it, I'm cherry picking a bunch of PRs for mass merge

**Comment by Projjol** [comment]
@sils Got it, sorry for the trouble!

**Comment by sils** [comment]
cherry picked into https://github.com/coala/coala/pull/3330 this'll be merged for you

**Comment by Projjol** [comment]
@sils thanks! :)

**Pull request closed without merging**
