### PR TITLE
Change afected->affected

### PR DESCRIPTION
**Pull request by vreethesh**
Closes https://github.com/coala/coala/issues/2836

### CODE REVIEW

**Comment by manu-chroma** [comment]
@vreethesh shortlog not upto the mark. You know what to do. Check your commit message from last PR

**Comment by vreethesh** [comment]
@manu-chroma There it is. Sorry. Now it is same as my last PR.

**Comment by Adrianzatreanu** [comment]
ack ab4970f

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by sils** [comment]
First issue? Please fill coala.io/newform and consider contributing further
- this newcomer program is really sucking a lot of resources and we need
your help.

**Pull request merged**
