### PR TITLE
Backport bear test fix

### PR DESCRIPTION
**Pull request by Mixih**
Backport the test fixes for Bear.py to coala 0.9 to enable docker image build. We have no idea when this test started failing, only that it did.

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
- [x] I have followed the [guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference).
- [x] I have [run all the tests](http://coala.readthedocs.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### Reviewers
@underyx 
@sils

### CODE REVIEW

**Comment by sils** [comment]
Don't you need the commit from @underyx as well?

**Comment by Mixih** [comment]
which one?

**Comment by sils** [comment]
didn't he have a commit fiddling with the dependencies?

**Comment by sils** [comment]
https://github.com/coala/coala/commit/092ce5b69505b7a9afa78bf1514b5edad849b6b9

**Comment by sils** [comment]
reack https://github.com/coala/coala/pull/3115/commits/9739d33f1bca23f55667dc8ab4aa10326420af71 https://github.com/coala/coala/pull/3115/commits/f9aad34bc5c3c0599d71a906caefb29fb1f7863f

**Comment by Mixih** [comment]
Oh crap, yes he did. I'll add it.

**Comment by Mixih** [comment]
Added.

**Comment by Mixih** [comment]
Random circle fails... Investigating

**Comment by Mixih** [comment]
see gitter for current status

**Comment by sils** [comment]
I don't understand why we need to backport https://github.com/coala/coala/pull/3115/commits/846d244635628d0fd1ab5b8aa9df09579063f378 ?

**Comment by jayvdb** [comment]
I agree that 846d244 isnt needed on the release branch

**Comment by Mixih** [comment]
without 846d244 the circle build fails on sphinx for some reason when it is unable to import the module coalib.mixc.ContextManagers. I'm not exactly sure why. 846d244 deems to fix it.

**Comment by Mixih** [comment]
Compare https://circleci.com/gh/Mixih/coala/38 which has 846d544 and passes with https://circleci.com/gh/Mixih/coala/42 which doesn't have 846d244 and fails.

**Comment by Mixih** [comment]
Yes this is all docker needs. Here is a build I ran with there patches and a few patches to the Dockerfile(pull is open) https://travis-ci.org/Mixih/docker-coala-base/builds/179116584 . Ready for review and merge.

**Comment by sils** [comment]
reack
846d244635628d0fd1ab5b8aa9df09579063f378
b5752ae585215287184495aa88a0c6fbfffecfe9
95bc2a31c4f449f546f285acbc843814bb79c48e
71ee7d385ce513200525ce680c16f321b01a3a14
b5836bcf08cceef3232a278300ca8edf224e6ef5

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
