### PR TITLE
 Development_Setup.rst: Remove .. _dev-notes:

### PR DESCRIPTION
**Pull request by Balaji2198**
removed .. _dev-notes: on the first line of Development_setup.rst.
This is unused in the file.

Fixes https://github.com/coala/coala/issues/4222

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
Please amend you git commit message to follow http://coala.io/commit

**Comment by mrtes** [comment]
Looks fine to me.

**Comment by mrtes** [comment]
ack 98f80f8

**Comment by supergr35** [comment]
`Fixes` -> `Closes` in commit message please

**Comment by Balaji2198** [comment]
I think i messed up something can anyone @mridubhatnagar @supergr35 @mrtes check this let me know.
I just removed the Blank line in Development_setup.rst and amend the commit message and pushed to the patch-1.

**Comment by meetmangukiya** [comment]
Follow the squash guide

**Comment by SanketDG** [comment]
try following https://asciinema.org/a/11269

or come to https://coala.io/chat if you need help

**Comment by jayvdb** [comment]
You have someone elses commit in https://github.com/coala/coala/pull/4226/commits .  Could you remove that, and rebase please.

**Comment by nityeshaga** [comment]
@Balaji2198 You still working on this PR?

**Pull request closed without merging**
