### PR TITLE
Writing_Tests: Correct "Executing Tests" reference

### PR DESCRIPTION
**Pull request by sils**
### Checklist

- [ ] I have rebased properly. Please see [our tutorial on rebasing](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing).
- [ ] I have gone through the [commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html) and I've followed them.
- [ ] I have followed the [guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
- [ ] I have followed the [guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
- [ ] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference).
- [ ] I have [run all the tests](http://coala.readthedocs.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### Reviewers

Fixes https://github.com/coala/coala/issues/3199

### CODE REVIEW

**Comment by sils** [comment]
I set @Mixih as author as he did the original commit (although I made a new one)

**Comment by Mariatta** [comment]
lgtm. Thanks! :)

**Comment by sils** [comment]
reack 09d6b89

**Comment by sils** [comment]
a22ec25 reack

**Comment by sils** [comment]
reack
ea48d66 Linter: Fix documentation link
49f8884 Globbing: Make comments more consistent

**Comment by jayvdb** [comment]
ack 09d6b89
ack a0d8178
ack 4da8bd6
ack a22ec25
ack 39b0a17
ack 49f441b

**Comment by sils** [comment]
ack 39b0a17

**Comment by jayvdb** [comment]
reack 4da8bd6
reack a0d8178

**Comment by sils** [comment]
reack 4da8bd6

**Comment by sils** [comment]
@jayvdb maybe you have a tab or some other whitespace that isn't a regular space in there, then gitmate doesn't seperate the shas properly?

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
