### PR TITLE
create page about cobot

### PR DESCRIPTION
**Pull request by ashwini0529**
I've gathered information from `cobot help` and https://gitlab.com/coala/cobot
If there's something left, please mention.

### CODE REVIEW

**Comment by sils** [comment]
can we rather improve the help of cobot? As I mentioned on the issue. That'd be way better.

**Comment by ashwini0529** [comment]
The need was to create a page for cobot. I like your idea of improving cobot help page.  But what should we improve in that?

**Comment by ashwini0529** [comment]
I somewhere feel a need for a cobot page. While people go through the `docs`, they must know about `cobot`

**Comment by ashwini0529** [comment]
Where can i find cobot help page?

**Comment by sils** [comment]
there's no help page, there's just the cobot help command.

**Comment by sils** [comment]
closing as per https://github.com/coala/coala/issues/3228#issuecomment-270025271 @ashwini0529 reopen if you disagree please

**Pull request closed without merging**
