### PR TITLE
DefaultArgParser.py: Change order of logging

### PR DESCRIPTION
**Pull request by kumarmj**
**DefaultArgParser.py:** Change order of logging to DEBUG/INFO/WARNING/ERROR

Closes https://github.com/coala/coala/issues/3617

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [x] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

**After you submit your pull request, DO NOT click the 'Update Branch' button**

### CODE REVIEW

**Comment by rhemon** [comment]
@kumarmj you need to fix your commit's shortlog. its too big

**Comment by kumarmj** [comment]
@gaocegege thanks for nice response. Please let me know for any other changes

**Comment by supergr35** [comment]
Please rebase :) 
http://api.coala.io/en/latest/Developers/Git_Basics.html#rebasing

**Comment by kumarmj** [comment]
@supergr35 rebased, feel free asking, any other changes

**Comment by gaocegege** [comment]
Hi, CI task is failed, plz check it :)

**Comment by kumarmj** [comment]
> command pip install coala-bears[alldeps] --pre -U took more than 900 seconds since last output

This is the error help troubleshooting, guide me here please

**Comment by kumarmj** [comment]
Hi, hope all is going well. I just rebased and all test are passing please review

**Comment by SanketDG** [comment]
ack 575250a

**Comment by SanketDG** [comment]
@rultor merge

**Pull request merged**
