### PR TITLE
provided deprecation warning for log_printer param

### LINKED ISSUE #4972: coala_modes.py: Deprecate log_printer param for mode_normal
# Issue
log_printer param is now deprecated and unused. 

## Proposal
Provide a deprecation warning (with `logging.warn`) if `log_printer` param is used.

EDIT by @Makman2:
Removed `DeprecationWarning` and rephrased to not confuse with the class from the `warnings` module (as we don't use those warnings, at least not yet)

### PR DESCRIPTION
**Pull request by Anonymous26**
Fixes #4972 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by GabrielDS** [comment]
Hi @Anonymous26 

:stop_sign:  I am sorry but you can work on the issue only if you are assigned. 

Please read our [Welcome to the Newcomers’ Guide!](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html)

**Comment by Anonymous26** [comment]
Sorry, This is my first issue since no one was active i started working on it. Is it possible to get it assigned.

**Comment by somnathrakshit** [comment]
@GabrielDS Can I get it assigned?

**Comment by Makman2** [comment]
Sorry, but have to close due to not being assigned to the issue.

**Comment by somnathrakshit** [comment]
@Makman2 Can you please assign it to me?

**Pull request closed without merging**
