### PR TITLE
Writing_Native_Bears.rst: Add explained outputs

### PR DESCRIPTION
**Pull request by nityeshaga**
Adds the outputs of various commands used as examples in the tutorial
along with their explanation when available.

Closes https://github.com/coala/coala/issues/4406

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by nityeshaga** [comment]
I don't understand why it is showing all these space inconsistencies. I ran coala on the project before committing and it applied the patches :(
applypatch

**Comment by nityeshaga** [comment]
Can someone help and tell me why circleci failed?

**Comment by JohnMoutafis** [comment]
@nityeshaga Although I cannot place my hand over fire, I believe that your commit title is 50 characters long and the newline makes them 51...
Maybe that makes the test fail.

**Comment by nityeshaga** [comment]
Nah. The commit title is 47 letters long. Must be something else.

**Comment by Arsfiqball** [comment]
Please rebase @nityeshaga

**Comment by nityeshaga** [comment]
Thanks @Arsfiqball ! All checks have passed now! do we need to rebase the commit every time there is a new PR merge in upstream?

**Comment by Arsfiqball** [comment]
ack 78db509bba887ddb99213b0b09cc9a776597b961

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
