### PR TITLE
Review.rst: Replace a word

### LINKED ISSUE #5085: Review.rst: rephrase a sentence
It would be nice to use `their` instead of `his` when refering to `someone` in the sentence
`Reviewing always involves saying someone that his code isn't right, be very careful not to appear rude even if you don't mean it!` to be more inclusive.

The page in question: http://api.coala.io/en/latest/Developers/Review.html
The file in question: `Review.rst`, at line 33.

### PR DESCRIPTION
**Pull request by kunal09**
Change his --> their.

Closes #5085

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by newbazz** [comment]
Thr `r` in `reframe` sud be capital

**Comment by kunal09** [comment]
How about now, Ishan?

**Comment by ishanSrt** [comment]
would be better if you followed exactly like mentioned in the link in the previous example @kunal09

**Comment by EverWinter23** [comment]
I feel like the commit description is more than sufficient and moreover the commit SHORTLOG describes the change appropriately.

**Comment by ishanSrt** [comment]
actually there are spaces before arrows in the link I gave 😛. But anyways LGTM.

**Comment by nvzard** [comment]
ack 6062569

**Comment by Makman2** [comment]
ack 6062569

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
