### PR TITLE
Sils/trumpscript

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3055/commits/7614b5983f24996262756427d4f22035ebf0dcda

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/3055/commits/b51cfd4e32ff2514b65cac5f62e9518527eedb14

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/3055/commits/5b42da5decab64bb7e22b255db9206c572c5059c

**Comment by userzimmermann** [comment]
https://github.com/coala/coala/pull/3055/commits/7614b5983f24996262756427d4f22035ebf0dcda fixes #3054

**Comment by userzimmermann** [comment]
@rultor merge

**Pull request merged**
