### PR TITLE
Writing_Documentation.rst: reStructuredText link is working now

### PR DESCRIPTION
**Pull request by lalitmee**
Writing_Documentation.rst: Fix url 

This fixes the earlier [url](http://www.sphinx-doc.org/en/latest/rest.html) to a new [url](http://www.sphinx-doc.org/en/master/rest.html). 
 
Fixes https://github.com/coala/coala/issues/5263

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by palash25** [comment]
@lalitmee read the commit guidelines and alter your commit accordingly :wink:

**Comment by lalitmee** [comment]
Yeah, I am doing that.

**Comment by palash25** [comment]
One commit is more than enough for a small change. Squash them and follow the guidelines.

**Comment by lalitmee** [comment]
Actually, I messed up with my forked repo. So I am closing this one. I will create a new one and hope that will pass all the tests.

**Comment by palash25** [comment]
@lalitmee don't close PR's without asking. If you have messed up a fork or a branch then ask on the Gitter channel and someone will reach out to you. We don't encourage opening multiple PRs for the same issue. Keep that in mind the next time. :wink:

**Comment by lalitmee** [comment]
@palash25 , oh sorry. I will keep that mind the next time. :innocent:

**Pull request closed without merging**
