### PR TITLE
coala_main.py: Add param doc for 'arg_parser'

### PR DESCRIPTION
**Pull request by shubhamswain**
### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
- [x] I have followed the [guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference).
- [ ] I have [run all the tests](http://coala.readthedocs.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### Reviewers

Fixes https://github.com/coala/coala/issues/3016

### CODE REVIEW

**Comment by ap916** [comment]
ack ebfd044

**Comment by Mixih** [comment]
unack ebfd044

**Comment by Mixih** [comment]
Also, you will need to rebase

**Comment by shubhamswain** [comment]
Made the changes, rebased and pushed. :)

**Comment by Mixih** [comment]
ack 56a8e15

**Comment by Mixih** [comment]
@rultor merge

**Pull request merged**
