### PR TITLE
Pull template: Add branch button warning

### PR DESCRIPTION
**Pull request by bharg**
Pull template: Add branch button warning

PULL_REQUEST_TEMPLATE.md now contains a warning about
the 'Update Branch' button

Closes https://github.com/coala/coala/issues/3406

### Checklist

- [ ] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [ ] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [ ] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [ ] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [ ] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [ ] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by bharg** [comment]
I've created this new pull request as my old one got really messed up.

I see that in the new comer's guide, it says that I am not supposed to push from master. I'll keep it in mind from the next time or should I make change now?

**Comment by Mixih** [comment]
keep it for now as this seems mergable

**Comment by Mixih** [comment]
ack	c7ed3e8

**Comment by Mixih** [comment]
ack c7ed3e8

**Comment by Mixih** [comment]
@rultor merge

**Comment by bharg** [comment]
First merge \m/

**Pull request merged**
