### PR TITLE
Hacktoberfest

### PR DESCRIPTION
**Pull request by Bucceroni**
Hacktoberfest

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
Please mark this as invalid via adding the invalid label. This will tell Digital Ocean (which runs hacktoberfest) to not count this PR as it is just spam

**Comment by robbyoconnor** [comment]
@sils mark this using the invalid tag so DigitalOcean and GitHub know this guy is just spamming pull requests.

**Comment by sils** [comment]
@robbyoconnor @TheSharpieOne thanks for the heads up. I've reported the user to GitHub so they can remove the github user, that should be way more efficient.

**Comment by robbyoconnor** [comment]
i also reported the user

**Comment by sils** [comment]
awesome let's hope they react soon

**Comment by TheSharpieOne** [comment]
I was going to report the user as well, but these actions didn't seem enough for github to take action against him/her (based on github's policies). I decided to just point out the PRs to other repos were not legit and it instruct how to mark them as invalid.
Speaking of marking them as invalid, the label/tag needs to be "invalid". "status/invalid" doesn't mark this PR as invalid for hacktoberfest (AFAIK; the official site says "invalid" and the unofficial [hacktoberfest-checker](https://github.com/jenkoian/hacktoberfest-checker) is counting this PR as valid).

**Pull request closed without merging**
