### PR TITLE
Update Git Installation command

### PR DESCRIPTION
**Pull request by nikhil-seth**
docs\Developers\Git_Basics.rst : Update Git installation command
Change git installation command from git-all to git

Fixes :https://github.com/coala/coala/issues/4903

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
We have docs that explain how to write a good commit message you can have a look at
http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html. 

To make amends to your commit message you'll have to do something like
`git commit --amend`. 

In case you get stuck with any git related issues. Please ping in the channel and someone will
help you out.

**Comment by mridubhatnagar** [comment]
For future reference make sure you don't create a PR from the master branch of your forked repo.
You can know the reason for it by reading through the newcomer docs. 
http://api.coala.io/en/latest/Developers/Newcomers_Guide.html.

**Comment by mridubhatnagar** [comment]
> Shortlog of HEAD commit isn't in imperative mood! Bad words are 'Updated'

This error is raised by the gitmate bot because your commit message uses keyword 
as 'Updated' . Commit messages are always in present tense. Hence, Update or Updates 
would work.

**Comment by nikhil-seth** [comment]
I've made the requested changes & will keep in mind in future to put changes through other branch & not through Master branch

**Comment by mridubhatnagar** [comment]
Did you push the changes done? I am online through mobile hence asking. Because I am unable to see the commit.

**Comment by RaiVaibhav** [comment]
Please go through [commit guidelines](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html)

And always `coala` before push changes or `open a PR` it will help you in getting the error.

**Comment by RaiVaibhav** [comment]
@nikhil-seth  `git commit --amend` will help you

**Comment by nikhil-seth** [comment]
I've made a new commit of the change.

**Comment by mridubhatnagar** [comment]
As per coala guidelines. Only 1 commit should be there.  You can make changes in the commit by using git commit --amend . Or in case you have made a new commit and pushed it. Then, you will have to squash your commits.

**Comment by mridubhatnagar** [comment]
@nikhil-seth
You have changed the title. Not the commit.

**Comment by mridubhatnagar** [comment]
Re-open don't close. These are not meant to be closed. It can easily be resolved.

**Pull request closed without merging**
