### PR TITLE
Git_Basics.rst: Correct RST Syntax

### PR DESCRIPTION
**Pull request by adtac**
Fixes https://github.com/coala/coala/issues/4221

### CODE REVIEW

**Comment by adtac** [comment]
To maintainers: do not rultor merge this. I recently merged a verification into coala that checks whether the person calling rultor is a maintainer. To check this, we obviously need a non-maintainer attempting to merge an approved PR. Feel free to ack though.

To non-maintainers: If this PR has been reviewed and merged, please comment `@rultor merge`.

**Comment by adhikasp** [comment]
ack 9416e6fed573a2041efeee3a2faedec8f6549318

**Comment by adhikasp** [comment]
Oh wait, am i supposed to ack first before call rultor..?

**Comment by adhikasp** [comment]
@rultor merge

**Comment by adtac** [comment]
@rultor merge

**Comment by adhikasp** [comment]
@rultor merge

**Comment by adtac** [comment]
@rultor merge

**Comment by adtac** [comment]
@rultor merge

**Comment by adtac** [comment]
reack https://github.com/coala/coala/pull/4574/commits/7c586ff92f0005419b4d53c28f7924e84729056b

**Comment by adtac** [comment]
@rultor merge

**Pull request merged**
