### PR TITLE
Bear: Print error instead of warning

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/2964/commits/39071e1b7dec1a27d3d8b593e9f61ad4d3609567

**Comment by sils** [comment]
@Makman2 we were working on another PR for a longer time so I'm merging the other one first - so rebase, reack and merge for you :)

**Comment by Makman2** [comment]
reack 2abfe27

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
