### PR TITLE
Newcomers_Guide.rst: Fix docstring typo

### PR DESCRIPTION
**Pull request by kapurm17**
This fixes the comma typo from 
"When you say "Hello World" in chat ``corobo`` (our gitter bot) will invite you"
to
"When you say "Hello World" in chat, ``corobo`` (our gitter bot) will invite you"

Fixes https://github.com/coala/coala/issues/5924

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by kapurm17** [comment]
@shashank-b  Okay thanks! Will do.

**Comment by Dhiraj240** [comment]
@kapurm17 You have to edit your commit message use ```git commit --amend```  check [this](https://github.com/coala/community/pull/228/commits/db5c78e216ef97343ffbdc5312adaa1e1bcea113) for reference.

**Comment by Dhiraj240** [comment]
@kapurm17 Its unrelated to your change.

**Comment by sanchit48** [comment]
@kapurm17 there should be a line space between the commit body and the issue reference. kindly do the same.

**Comment by sanchit48** [comment]
LGTM :+1:

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5929/commits/4b3d7f26bf33cc09321e316d95db769307ca4724

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
