### PR TITLE
Development_Setup.rst: Fix dead link

### LINKED ISSUE #6160: Link Does not exist
link present on line 77 of docs/Developers/Development_Setup.rst does not exist. Remove line 75-77 to fix this.

difficulty/newcomer

### PR DESCRIPTION
**Pull request by DestroyerAlpha**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

Fixes #6160

### CODE REVIEW

**Comment by DestroyerAlpha** [comment]
> 
> 
> Hi @DestroyerAlpha. The changes look good, but go through coala [commit guidelines](http://coala.io/commit) and make proper commit. Also you will need to squash the commit if there are more than one commits in the PR

Fixed

**Review by CLiu13 — CHANGES_REQUESTED** [review]
Commit message is too long (currently 55 characters, 50 is the maximum limit as per the [commit guidelines](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html)) - I would suggest changing it to ```Development_Setup.rst: Fixed dead link.```

Otherwise, nice job!

**Comment by DestroyerAlpha** [comment]
> 
> 
> Commit message is too long (currently 55 characters, 50 is the maximum limit as per the [commit guidelines](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html)) - I would suggest changing it to `Development_Setup.rst: Fixed dead link.`
> 
> Otherwise, nice job!

Edited

**Review by CLiu13 — APPROVED** [review]
LGTM 👍

**Review by pra17dod — APPROVED** [review]

**Comment by abhishalya** [comment]
@DestroyerAlpha Can you share a link to travis build on your fork (just enable travis on your fork and create a PR to your own fork)? Unfortunately we exhausted all our travis credits for this month, and we're no longer able to trigger builds here. So until then I guess we have to make use of fork builds.

**Comment by DestroyerAlpha** [comment]
> 
> 
> @DestroyerAlpha Can you share a link to travis build on your fork (just enable travis on your fork and create a PR to your own fork)? Unfortunately we exhausted all our travis credits for this month, and we're no longer able to trigger builds here. So until then I guess we have to make use of fork builds.

[Link to Travis build](https://travis-ci.com/github/DestroyerAlpha/coala/builds/222681756) Here you go @abhishalya

**Comment by abhishalya** [comment]
@DestroyerAlpha And the build fails as you can see, you'll need to fix that before I can merge this.

**Comment by DestroyerAlpha** [comment]
> 
> 
> @DestroyerAlpha And the build fails as you can see, you'll need to fix that before I can merge this.

Build passed now. [https://github.com/DestroyerAlpha/coala/pull/1](url)

**Comment by abhishalya** [comment]
The commit guidelines specify that commits should be written in imperative present tense.

I'm letting it go for this time as a first contribution, although please take care of it next time.

**Review by abhishalya — APPROVED** [review]
LGTM :tada:

**Pull request merged**
