### PR TITLE
FilterHelper.py: Correct parameter reference

### PR DESCRIPTION
**Pull request by Raman1121**
Replaces 'args' with 'filters' in lines 38 and 39.

Closes https://github.com/coala/coala/issues/4694

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by IpshitaC** [comment]
ack ccc85a84e59802b95b4a1695988b2685514dac1f

**Comment by Raman1121** [comment]
@palash25 @IpshitaC Great advice! I will keep that in mind from now on. It's great learning new things from people like you. Thanks again!

**Comment by prakashdanish** [comment]
@Raman1121 you should add a reason in the commit message so that other members can easily understand the fix. I understand that this is a newcomers issue and hence doesn't involve much but It's a practice you should do as stated [here](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html)
Kudos on the PR!

**Comment by Raman1121** [comment]
@prakashdanish Thanks for the advice!

**Comment by Raman1121** [comment]
One more thing, should I close this PR or leave it as it is?

**Comment by palash25** [comment]
@Raman1121 you don't need to do anything now a maintainer would merge and close this PR. All you can do now is start working on a difficulty/low issue.

**Comment by stellargo** [comment]
@Raman1121 Well you shouldn't be merging you master branch due to the following reasons listed wonderfully on the newcomer's guide:

> It is important that you DO NOT make your changes on the master branch of your forked repository to avoid the following cases:
> 1. If you make a rebase to synchronize your repository to the original, every commit that is pushed to the remote master will be pulled in your master branch. Then if you make a pull request to commit your changes to the remote, the commits that got synced from the rebase will be recommitted along with your work in the pull request.
> 2. You cannot have two pull requests using the same branch name. Therefore, if your fork’s master has been used in a pull request and you decide to work on a different issue you will have to branch eventually. Differently every new commit that you make on your master branch will get attached to the initial pull request and that will result in altering the purpose of that request.
> 3. If your fork’s master has been used in a pull request, you have to keep the change in the branch until that get’s merged to the remote master. That will lead to the complications listed above, if you decide to work on a different issue.

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
LLVM is down, hopefully it's back online soon...

**Comment by prnvdixit** [comment]
@Makman2 This might merge now (probably) 😉

**Comment by prnvdixit** [comment]
reack 292ccda08f2fe815f1d1969a3441d357123fc8c5

**Comment by prnvdixit** [comment]
ack 292ccda08f2fe815f1d1969a3441d357123fc8c5

**Comment by prnvdixit** [comment]
ack ack 292ccda08f2fe815f1d1969a3441d357123fc8c5

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
