### PR TITLE
Linter.py: Typo error removed

### PR DESCRIPTION
**Pull request by Harshish**
Changed parsed to passed in line 596.

Closes https://github.com/coala/coala/issues/3850

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Vamshi99** [comment]
ack f85cf9a

**Comment by jayvdb** [comment]
You need to rebase your branch.

**Comment by jayvdb** [comment]
@harshish, you havent followed the newcomer process [again](
https://github.com/coala/coala/pull/3763#issuecomment-280830546).  You havent accepted the invitation to the organisation, and didnt get assigned to your issue before creating your PR, which [confuses](https://github.com/coala/coala/issues/3850#issuecomment-284312665) other developers and creates work for maintainers like me.

**Comment by sils** [comment]
@Harshish we sent you an invitation, check your mail or go to github.com/coala , accept it and get assigned; if you don't you're causing lots of overhead, somebody else already got started working on this causing work duplication. Please get assigned and follow [the guide](coala.io/newcomer)!

**Comment by Harshish** [comment]
@jayvdb I am really sorry for the trouble caused. I will read the instructions carefully. This won't happen again I assure you.

**Comment by jayvdb** [comment]
Ok, now rebase your branch.

**Comment by Techievena** [comment]
Why did you close it? @Harshish

**Comment by Harshish** [comment]
@Techievena  I made two commits which couldn't be squashed into one.

**Pull request closed without merging**
