### PR TITLE
README.rst: Add OpenHub badge to README

### PR DESCRIPTION
**Pull request by yuxiangdai**
Closes https://github.com/coala/coala/issues/4317

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
This change is approved, however now you need to rebase *this* PR.

Do not use GitHub's silly rebase buttons like you did on https://github.com/coala/coala/pull/4343.  Use git command line.

And finally, do not close this PR and start a new one.

Rebasing properly is a *fundamental* skill required to become a coala developer.  We have guides in our developer documentation, and we provide high quality assistance on https://coala.io/chat to help newcomers learn how to use git properly.

**Comment by jayvdb** [comment]
ack c1d3c69

**Comment by shreyans800755** [comment]
ack c1d3c69

**Comment by jayvdb** [comment]
@yuxiangdai , please rebase, and then mention this PR on gitter so it is merged

**Comment by sils** [comment]
I'm rebasing this for you to https://github.com/coala/coala/pull/4430 and merging it, thanks for your contribution :)

**Pull request closed without merging**
