### PR TITLE
Development_Setup.rst: Change redirecting link

### PR DESCRIPTION
**Pull request by sachincool**
This changes the redirecting link to installing from git in 'Development
Setup Notes' under 'Using virtualenv' section.

Closes https://github.com/coala/coala/issues/5002

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by sachincool** [comment]
@newbazz done,   is it alright !!

**Comment by sachincool** [comment]
@newbazz  are you suggesting make changes in the PR comment ? Or  totally reissue a new  PR ? 
as you can see the commit body is changed, so closing this  PR  and sending a same exact one  is a bit confusing to understand for me  please explain.

**Comment by newbazz** [comment]
no no, i am just asking you to make an empty commit by doing 
`git commit --amend --allow-empty`
`git push -f`

**Comment by sachincool** [comment]
I see what you're going for,  but when i pushed the  amended  commend last time it automatically rebuilded the PR  with the latest changed commit. ( only 1 commit is showing but, it's a different Sha-1 hash with changed  commit body).
P.s  It shows this `Aborting commit due to empty commit message.` if i try to allow an empty commit with no Short tag, no body , no issue   that is  with  the --alow-empty option.

**Comment by ishanSrt** [comment]
there was a timeout on some test in Circle CI. Get that to pass. Use `git commit --amend --no-edit` and then force push to rebuild your tests 😁

**Comment by ishanSrt** [comment]
@newbazz @sachincool `--allow-empty` means that you are not making any changes to the files and not, you are not making changes to commit messages

**Comment by ishanSrt** [comment]
looks like everythings good for now. I am gonna do
ack https://github.com/coala/coala/pull/5030/commits/26f0662673fae10897936eb40b89333ad9db3f73
although gitmate-bot is gonna scold me

**Comment by ishanSrt** [comment]
@sachincool don't wait for this to get merged. Pick your new difficulty/low issue

**Comment by sachincool** [comment]
@ishanSrt  Haha LOL :stuck_out_tongue_winking_eye:  understood, thanks for such  fast  reply :+1: .
:bowtie: will do

**Comment by newbazz** [comment]
@ishanSrt `--allow-empty` means you are not making any changes but u can change the last commit message if you want ;)

**Comment by newbazz** [comment]
ack 26f0662673fae10897936eb40b89333ad9db3f73

**Comment by Makman2** [comment]
ack 26f0662

**Pull request merged**
