### PR TITLE
Language.py: Fixed typo error

### LINKED ISSUE #4365: Change ``prarses``->``parses``
[here](https://github.com/coala/coala/blob/master/coalib/bearlib/languages/Language.py#L25)

### PR DESCRIPTION
**Pull request by S2606**
Changed from 'prarses' -> 'parses' in language.py

Fixes #4365 

For short term contributors: we understand that getting your commits well defined like we require is a hard task and takes some learning. If you look to help without wanting to contribute long term there's no need for you to learn this. Just drop us a message and we'll take care of brushing up your stuff for merge!

Checklist

 - [x] I read the commit guidelines and I've followed them.
 - [x] I ran coala over my code locally. (All commits have to pass individually. It is not sufficient to have "fixup commits" on your PR, our bot will still report the issues for the previous commit.) You will likely receive a lot of bot comments and build failures if coala does not pass on every single commit!

After you submit your pull request, DO NOT click the 'Update Branch' button. When asked for a rebase, consult coala.io/rebase instead.

Please consider helping us by reviewing other peoples pull requests as well:

    pick up any PR at https://coala.io/review
    review it (check https://coala.io/reviewing for more info)
    if you are sure that it needs work, use cobot mark wip <URL> to get it out of the review queue.

The more you review, the more your score will grow at coala.io and we will review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
wow.  Your commit message on https://github.com/coala/coala/pull/4373/commits is not correct.  We do not want all that in the commit log.
See https://github.com/coala/coala/commits/master for what nice commit messages look like.

**Comment by jayvdb** [comment]
Also, do not use GitHub online editor.
Using git command line tools is mandatory.

**Comment by S2606** [comment]
Ok @jayvdb i shall see it

**Comment by S2606** [comment]
@jayvdb I have changed the commit message. Pls review it

**Comment by jayvdb** [comment]
Please stop editing the description of this PR in the GitHub web interface.
You can not fix this in the GitHub web interface.
You *must* use `git` command line tools.

Go back and do http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#optional-get-help-with-git and especially read http://coala.io/git and other parts of our developer documentation.

**Comment by AMR-KELEG** [comment]
@S2606 You should get yourself assigned to the issue before working on it.
You can find more information here: http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-3-picking-up-an-issue

**Comment by jayvdb** [comment]
Please follow http://coala.io/newcomer , and ask to be assigned to https://github.com/coala/coala/issues/4365 at the appropriate step.

**Comment by jayvdb** [comment]
now you can rebase your patch, & fix your commit message so it follow http://coala.io/commit .

**Comment by S2606** [comment]
@jayvdb On rebasing my patch, its showing that its up-to-date with master branch.

**Comment by S2606** [comment]
@jayvdb and could you Please tell me what i havent changed since https://github.com/coala/coala/pull/4373/commits/14d3a1f0994d35dc8ed67d01a61e28c474510ded

**Comment by jayvdb** [comment]
For the third time, please rebase your patch, & fix your commit message so it follow http://coala.io/commit .  I am telling you this because those are the problems, and it your responsibility to fix them.

**Pull request closed without merging**
