### PR TITLE
Newcomers_Guide.rst: correct grammatical mistake

### LINKED ISSUE #5087: Newcomers_Guide.rst: typo error
There's a typo: `to to` should be `to` in the file Newcomers_Guide.rst at line 400.

### PR DESCRIPTION
**Pull request by lollichop**
This corrects a grammatical error, changes it from "to to" --> "to".

Closes #5087

### CODE REVIEW

**Comment by lollichop** [comment]
Done @pareksha. Thanks for the suggestion :)

**Comment by lollichop** [comment]
Done @vibhanshuvaibhav. Thanks for the suggestion :)

**Comment by Makman2** [comment]
ack b7b77dd

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
