### PR TITLE
Rename DoNothinActionTest.py

### PR DESCRIPTION
**Pull request by Nosferatul**
Rename DoNothinActionTest.py into DoNothingActionTest.py
Rename class to DoNothingActionTest

### CODE REVIEW

**Comment by damngamerz** [comment]
LGTM :)

**Comment by SanketDG** [comment]
ack 75a0c7f

**Comment by Nosferatul** [comment]
reack 530bcd7

**Comment by Nosferatul** [comment]
@rultor merge

**Pull request merged**
