### PR TITLE
Made comments more consistent

### PR DESCRIPTION
**Pull request by Ludvigch**
Added capital letters and periods.

### CODE REVIEW

**Comment by erickzhao** [comment]
Not a fan of the periods in the inline comments. They're short enough to omit those, no?

**Comment by Asnelchristian** [comment]
Well @Ludvigch , your test are failing :(

**Comment by Asnelchristian** [comment]
You should modify your commit short log a little. Did you follow http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog ?

**Comment by Asnelchristian** [comment]
Marking it WIP

**Comment by Nosferatul** [comment]
Hello! You should rebase because out-of-date branch

Rebasing
As people work on coala new commits will be added. This will result in your local fork going out of sync with the remote repository. To sync your changes with the remote repository run the following commands in the desired branch:

$ git fetch origin
$ git rebase origin/master
This will fetch the commits from the remote repository and will merge it into the branch where you are currently working, and move all of the local commits that are ahead of the rebased branch to the top of the history on that branch.

Note

After following these instructions when you try to push to remote you may get fast-forwarding error. If that is the case, then you will have to force push since you are attempting to rewrite the git commit history. To do that append the --force argument in the push command:

$ git push myfork --force

Warning: Never force-push on the master branch, or any branch not owned by you.
To verify whether you have rebased correctly, go to the web page of the branch in your fork. If it says your branch is n commits behind coala:master (or whichever repo you are contributing to), then you haven’t correctly rebased yet. Otherwise, you’re good to go!

**Comment by sils** [comment]
@Ludvigch should we fix this up for you?

**Comment by Makman2** [comment]
Taking over in https://github.com/coala/coala/pull/3186

**Pull request closed without merging**
