### PR TITLE
CI: Remove explicit nltk download

### PR DESCRIPTION
**Pull request by jayvdb**
The bear now downloads the data on demand.

Related to https://github.com/coala/coala-bears/issues/1617

### CODE REVIEW

**Comment by adtac** [comment]
ack https://github.com/coala/coala/pull/4128/commits/d79bfb97e6fbf6776c97c9adfa0ee0b0079823ed

**Comment by jayvdb** [comment]
The data still needs to be cached, and we need to explicitly tell the CI what to cache.

**Comment by jayvdb** [comment]
reack 3b42d25

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
