### PR TITLE
gsoc: Numbers to letters

### PR DESCRIPTION
**Pull request by Nosferatul**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
ack 2f2ab390b0f5f188253b2460803ccc1bb6efe05f

**Comment by Adrianzatreanu** [comment]
btw it appears you have conflicts, maybe its stuff that was fixed in the mean time, can you please rebase?

**Comment by yukiisbored** [comment]
Gonna wipe the cache and see if it'll pass or not.

**Comment by Adrianzatreanu** [comment]
the code looks great, we just gotta fix the coverage and tests and we're done :)

**Comment by Adrianzatreanu** [comment]
the code is outdated anyway.

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala/pull/4390/commits/2fa3250335d39a3be2c4b6d9cc6a13b2768baada

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala/pull/4390/commits/061044d7d1d28c9792eee1b5e85ba26e9e9f12ed

**Comment by yukiisbored** [comment]
@Adrianzatreanu Merge it when the tests pass, trigger rebuilds without cache if it fails again.

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala/commit/2f0f3116aea7e2933322d4cc2a44a9fef61981a4

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala/commit/8a25983187966a60a810756c200ece1d9bb59607

**Comment by yukiisbored** [comment]
@rultor merge

**Pull request merged**
