### PR TITLE
Add Brackets Code to known editors for coala

### LINKED ISSUE #5829: Add Brackets editor Code to known editors for coala

### PR DESCRIPTION
**Pull request by XLAR-8**
Added bracket to the list of known GUI Editors.

Guidance Required:
In order to open a file , the command goes:

Open a file in the current folder,
without switching projects:
brackets index.html

Open two files from a specific path,
without switching projects:
brackets ~/Sites/index.html ~/Sites/index.css

Open the current folder as a project in Brackets:
brackets .

Open a specific folder as a project in Brackets:
brackets ~/Sites/mysite

Brackets can be launched from the command line.
Presently it does not accept any other arguments.
Any updates required will be implemented.
Closes #5829 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by XLAR-8** [comment]
@AkshJain99 , https://ci.appveyor.com/project/coala/coala/builds/19662745 is this the error comming because i wrote fixes instead of closes?
can i send another pull request before getting label as review/wip.

**Comment by AkshJain99** [comment]
No I dont think that appveyor is the error due to Fixes but yes you should change it to Closes and yes you can change commit message in this PR only there is no need to open new PR for same issue 
you can refer to http://api.coala.io/en/latest/Developers/Git_Basics.html

**Comment by srivama** [comment]
Duplicate of https://github.com/coala/coala/pull/5838

**Comment by XLAR-8** [comment]
@AkshJain99  thank you for help.

**Comment by XLAR-8** [comment]
@srivama thanks ,i understood your point.

**Comment by jayvdb** [comment]
Duplicate of #5838

**Pull request closed without merging**
