### PR TITLE
Testing_Bears: Add Glossary

### PR DESCRIPTION
**Pull request by sonali0901**
This update removes Glossary from Writing_Bears.rst and adds it to Testing_Bears.rst.

Closes https://github.com/coala/coala/issues/4755

### CODE REVIEW

**Comment by RaiVaibhav** [comment]
@khanchi97  review this PR

**Comment by sonali0901** [comment]
@nealkarpe @RaiVaibhav I updated the commit before it was reviewed. Added a newline manually and edited the commit body to have less than 72 characters, hence it passed the checks in the second go. Let me know if any change is needed.

**Comment by nealkarpe** [comment]
@sonali0901 Apologies. My bad :). Looks good to me! :+1:

**Comment by RaiVaibhav** [comment]
@sonali0901  use coala and run the bear for SpaceConsistency and then submit the PR

**Comment by sonali0901** [comment]
@RaiVaibhav  I installed the requirements and ran coala. I am unable to understand how to read the output of the tests. I am attaching a screenshot of the output.
screenshot from 2017-10-18 16 59 53

**Comment by Makman2** [comment]
There are no issues detected on your screenshot, that is a clean coala run ;)

**Comment by Makman2** [comment]
ack d1dd53a

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by RaiVaibhav** [comment]
@sonali0901 soory for the late reply as you know there is a  festival going on i was busy there there is any issue according to your screen shot

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
