### PR TITLE
Sils/showpatch

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala/pull/2995/commits/2c84a6f5bbadc24e2b078338588a8a7d7fd77435

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala/pull/2995/commits/12422fde6fa317469d37f1de40b9eeaaf8a4339f

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala/pull/2995/commits/f29960d942ef3093cea6e7029ecf8840baec506c

**Comment by Asnelchristian** [comment]
maybe you should squash the the third and fourth commit into one

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala/pull/2995/commits/8d159a9778daaa894cd1181f24668af35bf9aac5

**Comment by sils** [comment]
have been thinking and I think this is clearer for review

**Comment by sils** [comment]
also it doesn't matter too much

**Comment by sils** [comment]
reack 7d670cb

**Comment by sils** [comment]
@rultor merge

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala/pull/2995/commits/7d670cbdef9c9bd6aa27faa2683fbd3eade39ed9

**Pull request merged**
