### PR TITLE
better pip command example

### PR DESCRIPTION
**Pull request by Shekharrajak**
Fixes https://github.com/coala/coala/issues/3903

line  `(venv)$ pip3 install -e <path/to/your_forked_coala_repo>`  is more understandable. 

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [x] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by Shekharrajak** [comment]
@aptrishu , @rishikksh20 I have read the guidelines. This PR is not related to any opened issue and I hope the commit msg is fine. Let me know what else I can do.

**Comment by jayvdb** [comment]
There doesnt appear to be an existing about this PR...?

I did request a rewrite a few days ago in https://github.com/coala/coala/issues/3903 .

Could you please rebase and follow our git commit guideline.

**Comment by Shekharrajak** [comment]
@jayvdb , I have added these lines in PRs description : 

```
Fixes #3903

line (venv)$ pip3 install -e <path/to/your_forked_coala_repo> is more understandable.
```

I think commit message is good to go. Can you suggest better commit msg if you are not agree ?

**Comment by jayvdb** [comment]
@Shekharrajak , you need to modify your [commit](https://github.com/coala/coala/pull/3548/commits) (not the PR).

See http://coala.io/commit and http://coala.io/git#follow-up .

**Comment by jayvdb** [comment]
The issue was fixed

**Pull request closed without merging**
