### PR TITLE
Language.py: Typo error fixed

### PR DESCRIPTION
**Pull request by S2606**
Typo issue ``prarses`` has been changed to ``parses``
for better readability.

Fixes https://github.com/coala/coala/issues/4365

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Udayan12167** [comment]
The commit message is wrong. It should not be 
```
Typo issue ``prarser`` has been changed to ``parser``
for better readability.
```

But 

```
Typo issue ``prarses`` has been changed to ``parses``
for better readability.
```

**Comment by rhemon** [comment]
ack f74cdc1

**Comment by zeeshan-amjad** [comment]
Please edit your commit message.
It should be: 
Typo issue ``prarser`` has been changed to ``parses``
for better readability.

Fixes https://github.com/coala/coala/issues/4365

**Comment by S2606** [comment]
Can anyone please tell me why Codecov has failed??

**Comment by S2606** [comment]
@jayvdb Please review my PR

**Comment by mridubhatnagar** [comment]
There should be only 1 commit. As of now there are 2 commits. You will have to squash your commits. 
http://api.coala.io/en/latest/Developers/Git_Basics.html.

**Pull request closed without merging**
