### PR TITLE
Writing_Linter_Bears.rst: Clean docs

### PR DESCRIPTION
**Pull request by SergeyGorbatyuk171**
Removing an ambiguity in 'Using Severities' section.
Just deleted a sentence that contained confusing info
because there are enough explanations given in the
beginning of the paragraph.

Closes https://github.com/coala/coala/issues/5248

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by SergeyGorbatyuk171** [comment]
@ishanSrt,  done. Sorry for that, got stuck with git for a while

**Comment by ishanSrt** [comment]
looks like while squashing your commits, you concatenated the commit messages so now they don't follow our format. Fix that 👍.

**Comment by SergeyGorbatyuk171** [comment]
@ishanSrt, yeah, my fault. As you have probably noticed, I did not have much practice with advanced git commands, but now I know :) Finally it looks fine (at least I hope so)

**Comment by ishanSrt** [comment]
Maybe change your commit body to be more short and precise and less ambiguous.

**Comment by SergeyGorbatyuk171** [comment]
@ishanSrt ok, removed long explanations.

**Comment by ishanSrt** [comment]
@SergeyGorbatyuk171 
>short and precise

but still explaining what you are doing 😉

**Comment by SergeyGorbatyuk171** [comment]
@ishanSrt , @newbazz , sorry for delay - there we go. Is that better?) 
BTW, why didn't gitmate assign this PR to me as he does with others? Am I missing some steps in this process?

**Comment by SergeyGorbatyuk171** [comment]
@newbazz , ok, done =)

**Comment by SergeyGorbatyuk171** [comment]
@jayvdb , done. Not sure how to make this description clear but concise)

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5283/commits/b2d5852288da14dc9c076fea74e28ca48123b9d9

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
