### PR TITLE
Compatibility.py: Add error message -Add comment explaining JSONDecodeError is available from Python3.5.x. Closes #4156

### LINKED ISSUE #4156: Compatibility.py: Add comment explaining JSONDecodeError is missing in Python 3.4
difficulty/newcomer

Opened via [gitter](https://gitter.im/coala/coala/?at=59098da68fcce56b205cd7e0) by @jayvdb

### PR DESCRIPTION
**Pull request by shreyateeza**
Add comment explaining JSONDecodeError is available from Python3.5.x.
Closes https://github.com/coala/coala/issues/4156

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
@shreyateeza this is again closed. 
Ping in the channel, or ping me I'll help you out. Closing PR's is not the solution to getting your first PR merged.

**Comment by alphadose** [comment]
ack ec0e8331da95911fe60a2f53dd8202589e3d697c

**Comment by mridubhatnagar** [comment]
unack ec0e833

**Comment by mridubhatnagar** [comment]
@shreyateeza you'll have to amend the commit message. 
Using `git commit --amend`.
How to write commit message you can refer to http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html.

**Comment by palash25** [comment]
I think you should squash your commits into one.

**Comment by shreyateeza** [comment]
Please suggest me a commit message

**Comment by ishanSrt** [comment]
The procedure for writing a good commit message is here http://coala.io/commit . You have not followed that

**Comment by shreyateeza** [comment]
I guess I have followed..@ishanSrt please check the guidelines once again

**Comment by ishanSrt** [comment]
No @shreyateeza . You haven't followed this:

> How to Write Good Commit Messages
> A commit message consists of 3 parts:
> 
> shortlog
> commit body
> issue reference

**Comment by shreyateeza** [comment]
@ishanSrt  you mean to say shortlog is missing?

**Comment by ishanSrt** [comment]
Your commit message is just this:

> Compatibility.py: Add error message

Where is the commit body and issue reference?

**Comment by shreyateeza** [comment]
Its in comment. Please check it.

**Comment by shreyateeza** [comment]
@mridubhatnagar is this alright?

**Comment by newbazz** [comment]
@shreyateeza run the command `git commit --amend --allow-empty` and write the commit msg as you have written in the comment.

**Comment by ishanSrt** [comment]
It seems you are not familiar with working with a Version Control System. I would suggest you go on and read about git and GitHub and follow some basic tutorials.

**Comment by sibasish14** [comment]
@shreyateeza have a look at other PRs that have passed all tests and compare with your's. You'll find the difference.

**Comment by sibasish14** [comment]
And yes.....
You forgot a newline between the shortlog and the body(as mentioned by gitmate-bot).

**Comment by mridubhatnagar** [comment]
ack c267a36

**Comment by vddesai1998** [comment]
ack c267a36

**Comment by Makman2** [comment]
> Add error message 

Hm you don't add an error message, but a comment ;) `Add comment` would be fine with me :+1:

While we're on it:

> Add comment explaining JSONDecodeError is available from Python3.5.x.

Missing space between `Python` and `3.5.x`. Also `from` --> `since` :)

**Comment by Makman2** [comment]
unack c267a36

**Comment by RaiVaibhav** [comment]
Two PR of same issue close this PR as second one already approved
dupe https://github.com/coala/coala/pull/4980

**Pull request closed without merging**
