### PR TITLE
Modified:   coalib/parsing/CliParsing.py

### PR DESCRIPTION
**Pull request by shashwatmishra76**
Changed variable name comment_seperators to comment_separators.

Fixes https://github.com/coala/coala/issues/5510

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

### CODE REVIEW

**Comment by shashwatmishra76** [comment]
@jayvdb This PR got a label of newcomer.So,this should be ready for reviewing from your side,right?

**Comment by jayvdb** [comment]
Get rid of the incorrect attempt at fixing the typo. It is wrong. You are not assigned to do
https://github.com/coala/coala/issues/5510#issuecomment-410521945

**Comment by shashwatmishra76** [comment]
This PR is a duplicate of https://github.com/coala/coala/pull/5696 .

**Comment by jayvdb** [comment]
Duplicate of https://github.com/coala/coala/pull/5696

**Pull request closed without merging**
