### PR TITLE
Newcomers_Guide.rst: Add survey link

### PR DESCRIPTION
**Pull request by ashwini0529**
Added survey link http://coala.io/newform
Closes https://github.com/coala/coala/issues/3142

### CODE REVIEW

**Comment by Nosferatul** [comment]
without period at the end of shortlog

**Comment by Mariatta** [comment]
ack 7723314a

**Comment by Mariatta** [comment]
@rultor merge

**Comment by Mariatta** [comment]
Thanks! :tada:

**Pull request merged**
