### PR TITLE
Newcomers_Guide.rst : Google form link

### PR DESCRIPTION
**Pull request by yashraj-Dhanuka**
Newcomers_Guide.rst : Google form link
 
Add Google form link for promotion request in Newcomers_Guide.rst

closes https://github.com/coala/coala/issues/4880

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
@yashraj-Dhanuka this issue seems to be assigned to someone else.

**Comment by mridubhatnagar** [comment]
Also there are many PR's you have raised and closed for the same issue. Closing the PR's is not a good idea. So, in case you get stuck with any git related issues. Always ping in the gitter channel. Someone from the community will help you out. The newcomers issues are basically there to make newcomers learn git. And there is always a way out to fix those git issues.

PS: I was advised this when I had joined :) . Forwarding it to you.

These are small changes. Initially everyone makes mistake in them. But, once you get a hang 
of these things it would be easy for you :)

**Comment by mridubhatnagar** [comment]
@yashraj-Dhanuka why did you close this?

**Comment by yashraj-Dhanuka** [comment]
@mridubhatnagar This Issue was assigned to someone else and according to community norms the PR will be closed.
So i closed it .
Is it Ohk ?

**Comment by mridubhatnagar** [comment]
Mostly. The maintainers close it. But as you have already closed it. Let it be as it is. And move ahead with newcomer issue. Remember to assign it to yourself first.

**Pull request closed without merging**
