### PR TITLE
PR of PRs

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by AbdealiJK** [comment]
ack
dfa2afd naming_convention: Handle dots in `to_snakecase`
ad84547 Result: Change from `== None` to `is None`
32c9936 LogMessage: Change from `== None` to `is None`

**Comment by AbdealiJK** [comment]
@rultor merge

**Comment by sils** [comment]
I think there's an issue somewhere about the template...

**Comment by AbdealiJK** [comment]
I thought so too, in fact I remember commenting on it. But I can't seem to find it anymore !

**Comment by sils** [comment]
maybe it was on coala-bears? :thinking:

**Comment by AbdealiJK** [comment]
Seems like it's in documentation, as documentation does not have a template yet, I'll let it be - https://github.com/coala/documentation/issues/222

**Comment by sils** [comment]
shouldn't we agree on one standard template for all repos ideally? I.e. make a default .github folder with those files, put it everywhere.

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/2933/commits/2b20794383c52079b3fbababdc0cc449052a13ff

**Comment by AbdealiJK** [comment]
@sils I am not sure. I think documentation repo has no tests to run and probably would have fewer number of checks. Bears may have something more like "please ensure it works with cib before commiting" and so on.

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/2933/commits/5e19dee274ae515fe04624513683bb47673fb9d6

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/2933/commits/5e19dee274ae515fe04624513683bb47673fb9d6 https://github.com/coala/coala/pull/2933/commits/21c70fd5e2e11096f2cceedae0960eeb0e12ab62

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
