### PR TITLE
Fix problem with not grammaticaly correct sentence.

### PR DESCRIPTION
**Pull request by hato221**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
hey, as gitmate pointed out, your shortlog needs to be 1 character shorter to be accepted by Github.

also, your commit message is a little off, but the change is alright! So please change the commit message according to the guidelines here http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html THANKS!

also, to edit the last commit, just do a ``git commit --amend``, edit it, save it, and then push again with the new flag ``--force``!

**Comment by chauffer** [comment]
`grammaticaly` is not grammatically correct.

**Comment by aptrishu** [comment]
Still on this @hato221 ?

**Comment by aptrishu** [comment]
Hey @hato221  , Your commit doesn't seem to be providing much information about the commit. Please follow our writing good commits Guideline here .
Then update you commit message using git commit -a --amend and force push it. To know more about git basics follow this link.
In case you get any doubt, feel free to ping us on our gitter channel https://gitter.im/coala/coala .

**Comment by AbdealiJK** [comment]
Closing as it's been inactive for a long long time. Unassigning too.
Ping to be reassigned / re-open the PR if you want to continue working on it.

**Pull request closed without merging**
