### PR TITLE
LocalBearTestHelper: Change Indentation

### LINKED ISSUE #5137: LocalBearTestHelper: Change the docstring indentation
difficulty/newcomer

### PR DESCRIPTION
**Pull request by flaredragon**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

Fixes #5137 

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by flaredragon** [comment]
@kriti21 Done! Sorry I forgot that while making the PR.
I think it could be added to the template

**Comment by kriti21** [comment]
@flaredragon you have to add it in the commit message (not in the github comments). Use `git commit --amend --allow-empty` to change the commit message and push your PR again. Read http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html to understand better. :)

**Comment by kriti21** [comment]
Why have you closed the PR?

**Comment by flaredragon** [comment]
I had some confusion with rebasing my head before.
I sorted it out now.
I apologize for the delay.

**Comment by kriti21** [comment]
No problem. Take your time :) If you need any help, ask here or on gitter if you wish.

**Comment by kriti21** [comment]
You need to rebuild your PR though. ;)

**Comment by flaredragon** [comment]
Thanks a lot! could you guide me through rebuilding a PR too? :)

**Comment by kriti21** [comment]
Told you already ;) `git commit --amend --allow-empty` This time without changing the commit message.

**Comment by kriti21** [comment]
You have made changes in the master branch. This is wrong. You need to create a separate branch to make changes and push that branch in your PR.

**Comment by Makman2** [comment]
The underlying issue is a duplicate.

**Pull request closed without merging**
