### PR TITLE
Updated README.rst

### PR DESCRIPTION
**Pull request by rayandas**
Simply exchanged the quote with another one for the README.rst.

### CODE REVIEW

**Comment by srivama** [comment]
The changes look good:) You need to write a proper commit message though. Please refer to coala.io/commit. Also, you’ll have to squash your commits into one. Look at coala.io/git for that 😉

**Comment by ryand91** [comment]
Yeah okay I'll fix it.

**Comment by jayvdb** [comment]
@ryand91 , you have six commits in https://github.com/coala/coala/pull/5817/commits

A PR for a change like this should only have one commit.

See https://coala.io/commit and https://coala.io/newcomer and https://coala.io/git

**Comment by jayvdb** [comment]
And if you need help, come onto https://coala.io/chat and we can help you fix this PR.  Please dont create a new PR.

**Pull request closed without merging**
