### PR TITLE
Update Review.rst

### PR DESCRIPTION
**Pull request by gautam1858**
referring to this issue https://github.com/coala/coala/issues/5512

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by EverWinter23** [comment]
@gautam1858 Pls, read the  [commit guidelines](http://coala.io/commit) carefully. Your shortlog, and your commit message do not correspond to the format specified.
Checklist specifically tells you to go through the commit guidelines, but you seem to have sipped that part altogether.

You're commit message should be something like this:

Review.rst: Typo Github->GitHub
Closes https://github.com/coala/coala/issues/5512

This format makes sure, that the issue is closed automatically when the pull request is merged. Filename is important because when you see your repository, it displays you're last commit in that directory, and it's much easier to know where the change was made when the filename is specified in the commit shortlog.

Please update your PR, and DO NOT FORGET TO SQUASH YOU'RE COMMITS into one. If you have trouble squashing commits, let me know.

**Comment by palash25** [comment]
@gautam1858 if you are having problems understanding the commit guidelines ask your questions here. This is a simple PR we can get it merged soon :+1:

**Comment by palash25** [comment]
This issue has no assignees and there is a duplicate PR for it here https://github.com/coala/coala/pull/5521

@gautam1858 always ask for assignment before working on an issue.

**Comment by li-boxuan** [comment]
Issue done by https://github.com/coala/coala/pull/5551

**Pull request closed without merging**
