### PR TITLE
.travis.yml: Add sentinel job

### PR DESCRIPTION
**Pull request by jayvdb**
This makes Python 3.6 the sentinel job,
so it runs by itself initially and causes
all other jobs to be cancelled if it fails.

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
Matrix at https://travis-ci.org/coala/coala/builds/393939619 showed the 3.4 & 3.5 jobs start after 3.6 finished.

**Comment by jayvdb** [comment]
Ugh ... `fast_finish` not needed with sentinel job, and will cause master pushes to not do a complete build.  Testing without it, and removing.

**Comment by jayvdb** [comment]
It doesnt appear possible to fast finish conditionally.
https://github.com/travis-ci/beta-features/issues/28#issuecomment-398284501

On the other hand, caching seems to work.

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala/pull/5542/commits/4895579fc7926af2d98e9c5ce96221325f0d4f2b

**Comment by yukiisbored** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
On the master build of this PR, py344 & py36 jobs kept their cache
https://travis-ci.org/coala/coala/jobs/393996271#L502
https://travis-ci.org/coala/coala/jobs/393996273#L501

On the first build of a PR after this, sentinel and normal builds kept their cache
https://travis-ci.org/coala/coala/jobs/394053243#L522
https://travis-ci.org/coala/coala/jobs/394053246#L523

**Pull request merged**
