### PR TITLE
Testing_Bears.rst: Change settings snippet

### PR DESCRIPTION
**Pull request by roydipayan003**
Changed settings={'max_number_of_lines': int=20} to settings={'max_number_of_lines': 20}
closes https://github.com/coala/coala/issues/3873

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Vamshi99** [comment]
@roydipayan003 Please follow http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html and commit again using "git commit -a --amend"

**Comment by roydipayan003** [comment]
@gaurav1911 How to do that?

**Comment by Vamshi99** [comment]
@roydipayan003 I have given how to do that in my comment. See that.

**Comment by roydipayan003** [comment]
Is it okey now? @Vamshi99

**Comment by RohanVB** [comment]
It still isn't following the commit guide :( . Check out the link provided by gaurav above :D

**Comment by Vamshi99** [comment]
Also, your branch has conflicts, please resolve that :)

**Comment by SanketDG** [comment]
@roydipayan003 still on this?

**Comment by supergr35** [comment]
Uh-oh! You have have the dreaded merge commit. This is probably because you pushed the rebase(update branch from master) button in github. This is not the proper way of doing this and will break many things. Please do an interactive rebase on the commit before the merge commit and remove the merge commit line(see http://stackoverflow.com/questions/17577409/git-remove-merge-commit-from-history). See https://api.coala.io/en/latest/Developers/Git_Basics.html#rebasing for the proper way to rebase.
(it's okay, we all make mistakes in git ;) )

Also, changing your commit doesn't mean changing the PR title. It means running `git commit -a --amend` on your own local code, and then pushing to the repository. If you need help, ask for it on our gitter channel, but check our documentation a lot first. All the info is there.

**Comment by aptrishu** [comment]
whats the update on this @roydipayan003 ?

**Comment by acashmkj** [comment]
@roydipayan003 are you still working on this issue

**Comment by Makman2** [comment]
Closing due to inactivity. Feel free to reopen, but only if assigned to the issue again :+1:

**Pull request closed without merging**
