### PR TITLE
FilterTest.py: unused 'InvalidFilterException'

### PR DESCRIPTION
**Pull request by yugeshk**
The said unused import has been removed from FiterTest.py file.

Closes https://github.com/coala/coala/issues/5026

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by yugeshk** [comment]
This pull request had number of character issues. Should I close this and make a new PR?

**Comment by sangamcse** [comment]
1. Never send a PR from master branch.
2. Please make a good commit. Use `git commit --amend` to change your commit. 
e.g., `FilterTest.py: Remove unused import`
Please follow as guided here http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#how-to-write-good-commit-messages.

**Comment by yugeshk** [comment]
Okay. So should I make a fresh PR?

**Comment by sangamcse** [comment]
No, don't make a fresh PR. First use `git commit --amend` and edit you commit there and then do a `git push --force branch_name`.

note: In your case branch_name is master.

**Comment by sangamcse** [comment]
Now the only issue is the assignee. You were not assigned to this issue.

**Comment by yugeshk** [comment]
Okay. I'll put a comment on the issue to assign me. Thank you :)

**Comment by shreyateeza** [comment]
Read the commit guidelines from https://coala.io/commits as given in the checklist. Also it would be better if you check the items of the checklist.

**Comment by yugeshk** [comment]
@shreyateeza Done. Also, I had made amends to my PR based on some suggestions. As this is my first one, please let me know what else I should do. Thank You :)

**Comment by sangamcse** [comment]
@shreyateeza It's fine. LGTM.
screen shot 2018-01-07 at 4 25 45 pm

**Comment by Makman2** [comment]
ack 99a38f7

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
