### PR TITLE
Add Support Neovim Code Editor

### LINKED ISSUE #4084: Support neovim (`nvim`) as an editor
```
[WARNING][14:15:54] The editor "nvim" is unknown to coala. Files won't be opened at the correct positions and other quirks might occur. Consider opening an issue at https://github.com/coala/coala/issues so we can add support for this editor. Supported editors are: atom, emacs, emacsclient, geany, gedit, gvim, kate, nano, subl, vim, xed
```

It's basically the same as `vim` so it could be just added to the allowed editors list and given the same behavior as `vim`.

### PR DESCRIPTION
**Pull request by mubaris**
This closes #4084

### CODE REVIEW

**Comment by Makman2** [comment]
Please read our commit message guidelines:
- You are missing the issue reference in the commit message
- A commit tag would also be good

**Comment by Makman2** [comment]
But code changes look good :+1:

**Comment by mubaris** [comment]
I have changed my commit message.

**Comment by Makman2** [comment]
ack 751a07a

**Comment by userzimmermann** [comment]
@mubaris @Makman2 We got a travis issue with Python 3.6 :/ https://travis-ci.org/coala/coala/jobs/231250070#L1028

**Comment by Makman2** [comment]
@userzimmermann See https://github.com/coala/coala/issues/4218.

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
