### PR TITLE
LogPrinter: Deprecate LogPrinter

### PR DESCRIPTION
**Pull request by shreyans800755**
This PR deprecates LogPrinter by using built-in logging.
It doesn't remove it completely so that public API is
not affected.

Closes https://github.com/coala/coala/issues/3472

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by yash-nisar** [comment]
@shreyans800755 You can prefix the title with `WIP` instead of manually marking it as `WIP` with `corobo`. e.g Something like `WIP LogPrinter...`

**Comment by shreyans800755** [comment]
@sils @jayvdb 
Please review this. The only public API being broken is `LogPrinterThread`. I believe its very specific to `coala` code making it less probable to be used by someone else outside `coala` project.
In source code, its not being used anywhere except in tests. Let me know what you think.

I'm still checking if something is missed out by mistake.

**Comment by sils** [comment]
_warn_if_unused_glob isn't public (leading underscore) and we can remove the arg there completely. Also I wonder how we can ever remove the argument properly without breaking things because it's oftentimes a positional argument?

**Comment by shreyans800755** [comment]
Yup, I've provided default value `None` to all the places possible.

**Comment by shreyans800755** [comment]
Ref https://github.com/coala/coala/issues/4484

**Comment by shreyans800755** [comment]
Deleted by mistake. New PR at https://github.com/coala/coala/pull/4608

**Pull request closed without merging**
