### PR TITLE
Bear.py: Remove set_up/tear_down

### LINKED ISSUE #3038: Bear.py: Remove set_up/tear_down paragraph from doc comment
Those functions don't exist anymore since ages. Just remove the paragraph.

difficulty low area documentation

Opened via [gitter](https://gitter.im/coala/coala/?at=5830c3c2297a180b4f154835) by @sils

### PR DESCRIPTION
**Pull request by robstat7**
### Checklist

- [ ] I have rebased properly. Please see [our tutorial on rebasing](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing).
- [ ] I have gone through the [commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html) and I've followed them.
- [ ] I have followed the [guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
- [ ] I have followed the [guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
- [ ] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference).
- [ ] I have [run all the tests](http://coala.readthedocs.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### Reviewers

Removed the paragraph from the doc comment in Bear.py containing set_up/tear_down

### CODE REVIEW

**Comment by Nosferatul** [comment]
Please check http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by Mixih** [comment]
@dileepsankhla Ping. Just checkign in ;)

**Comment by Mixih** [comment]
You need to fix you commit and rebase. Let us know when you have done that (please get this done soon, we have incorrect documentation until we can merge this)

**Comment by jarifibrahim** [comment]
@dileepsankhla Rebase your branch using the following commands

1. `git branch issue-3038`  (This will create a new branch. You should always create a new branch before you start working on an issue)
2. `git checkout master` (Just to make sure you're on the master branch)
3. `git reset HEAD~1 --hard` (Go back one commit. This is to make sure you don't get merge conflicts when you try to update your master branch)
4. `git pull upstream master` (Get new commits from the coala master branch)
5. `git checkout issue-3038` (Go to your branch)
6. `git rebase master` (Rebase your branch against master branch)
7. `git commit --amend` (This is to change the commit message. Change it to something like `Bear: Remove set_up/tear_down from doc` )
8. `git push origin issue-3038` (Push your new branch to Github)

Then close this PR and send a new one.

**Comment by dileepsankhla** [comment]
Sorry I was away from the github for a month. Actually I can not work anymore. I have other commitments to do. Sorry. Will anyone please close/delete this pull request?

**Comment by jayvdb** [comment]
Completed in https://github.com/coala/coala/pull/3498

**Pull request closed without merging**
