### PR TITLE
Git_Basics.rst : Incorporated the commands from http://ohshitgit.com/

### PR DESCRIPTION
**Pull request by sourojit**
Some important git commands from http://ohshitgit.com/
These are helpful when something goes wrong.

Closes https://github.com/coala/coala/issues/4985

### CODE REVIEW

**Comment by sourojit** [comment]
ok 👍

**Comment by prnvdixit** [comment]
Or wait... It might be a better idea to add them into the Git Basics itself - Maybe wait for someone else to comment - Sorry :smile:

**Comment by prnvdixit** [comment]
But still, amend your commit meanwhile :+1:

**Comment by sourojit** [comment]
@prnvdixit should I do something about these failed tests??

**Comment by prnvdixit** [comment]
Yup... see the errors pointed out by gitmate-bot :)
And you need to amend your commit (not the title of PR) - Use http://ohshitgit.com/#change-last-commit-message for same :wink:

**Comment by sourojit** [comment]
@prnvdixit the error messages now being shown are for previous commit messages and not the current one.What should I do?

**Comment by shreyateeza** [comment]
@sourojit Your doesn't commit doesn't have commit body and issue reference. Add it. Have a look at this example:

>  setup.py: Change bears' entrypoint
> 
> This entrypoint ensures that coala discovers the bears correctly.
> It helps not writing more functions inside ``coalib`` for this.
> 
> Closes https://github.com/coala/coala/issues/5861

Read  https://coala.io/commit and follow it. :)

**Comment by shreyateeza** [comment]
unack 22921fd

**Pull request closed without merging**
