### PR TITLE
Update Newcomers_Guide.rst 

### PR DESCRIPTION
**Pull request by snakevenom04**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

#4509
#4518

### CODE REVIEW

**Comment by AMR-KELEG** [comment]
You should follow the commit guidelines that are stated in (http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html).

So instead of using 
`Update ConfigurationGathering.py`
You can make it:
```
ConfigurationGathering.py: Fix the spelling mistake Alernative

Fixes https://github.com/coala/coala/issues/4518 
```
Additionally, make sure to assign yourself to the issue before working on the code.
See: http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-2-picking-up-an-issue

If you need help, use https://coala.io/chat .
Finally, keep motivated :wink:

**Comment by snakevenom04** [comment]
Oh right ! forgot to edit the name, sorry.
The problem wasnt assigned so I thought I d jump in. I am new to the whole
open code thing.
I ll definitely check out the chat link you sent me :)
I want to contribute more so I ll stick around, I found this project to be
quite fun.
Thanks for the quick reply!
P.S do i send the pull requests again then ? with the said changes ?

**Comment by Makman2** [comment]
You don't need to close the PR, just repush :+1:

**Comment by snakevenom04** [comment]
Oh okay, but I had to make a new PR cause this one had two commits...Anyhow i already put up the new PR for this as well as the other issue

**Comment by Makman2** [comment]
you can easily combine commits (called squashing or fixup) with the help of an interactive rebase:
```
git rebase -i master
```
just for the future ;)

next time please don't close PRs, you can always modify existing commits in a PR without problems by rebasing and repushing :)

**Comment by snakevenom04** [comment]
Woah.... Thanks for letting me know : ) I ll do that next time !

**Pull request closed without merging**
