### PR TITLE
Typo error in FunctionMetadata.py

### PR DESCRIPTION
**Pull request by robstat7**

### CODE REVIEW

**Comment by jackthepirate6** [comment]
You can work on the issue only if you are assigned.

**Comment by robstat7** [comment]
ConsoleInteraction.print_result: Fix docstring typo

deprecared -> deprecated

Fixes https://github.com/coala/coala/issues/5132

**Comment by robstat7** [comment]
@jackthepirate6 Oh! Closing this PR.

**Comment by kriti21** [comment]
You can't work on any issue without assignment.

**Pull request closed without merging**
