### PR TITLE
coala_main.py: Fix E501:10:80:line too long 

### PR DESCRIPTION
**Pull request by richardson-souza**
…2:462:12:no newline at end of file

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by sourabh1031** [comment]
Hello, @richardson-souza first and the foremost before sending the pr you can whether the code is following PEP8 guidelines or not, either you can have an IDE or an editor offering the same. Secondly, you need to change the commit message as it is not following the expected style see here https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html  and one more thing please tick mark the checkbox in your pr message description

**Comment by jayvdb** [comment]
@richardson-souza , please re-push to your branch `richardson` , and then re-open this PR.

It is *never* necessary to open a second PR.  You need to fix the existing PR.

A PR is just a link to a branch name in your repo.

**Comment by jayvdb** [comment]
Awesome.  Most people fail when trying to re-open a PR.

Now, the next step in fixing your PR is to squash your two commits into one commit.

There are many ways to squash commits, and we have some suggestions at https://coala.io/git

Here is one approach which should work quite well for your current situation.

```console
$ git checkout richardson
$ git reset --soft HEAD~1  # discard the top commit, but keep the changes 
$ git add coalib/coala_main.py  # submit this to be added
$ git commit --amend  # put the additional changes into the most recent commit
# an editor will open with the existing commit message
```

Check you have one commit only, and it contains what you wish to submit to this PR.

```
$ git log
$ git show
```

If there is only one commit by you, and it is correct, you can push that to this PR.

The next step is to improve your commit message.

Again, see https://coala.io/commit and https://coala.io/git for tips, or ask for help on https://coala.io/chat .

**Comment by li-boxuan** [comment]
What issue are you intending to solve? Please mention that in your opening comment https://github.com/coala/coala/pull/5781#issue-219803543

Also please learn git basics first before do further changes. This PR is getting messy.

**Pull request closed without merging**
