### PR TITLE
Language: Provide attribute inheritance for defs

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/3076/commits/7a6c40ddee587ba8e7a1b0be1e76f1842fba37d2

**Comment by sils** [comment]
7330eca reack

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/3076/commits/a974cbfc1044db885ee1cc40b042b68a7fc06757

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/3076/commits/7330eca9bd542cfdeaf5c420143e7a9a01dd98e4

**Comment by sils** [comment]
reack
7e1b9e2 aspects/meta: Use signature to get doc params
688dbf7 Language: Provide attribute inheritance for defs
a34635a Result: Add missing param

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/3076/commits/104a92a2538faacf205553ee0f58eece17036fc8

**Comment by userzimmermann** [comment]
@rultor merge

**Pull request merged**
