### PR TITLE
Adds Awards section and yegor256 award image to README.md

### PR DESCRIPTION
**Pull request by LadySith**
###Added yegor256 award into newly created Awards section

From issue #2924

### CODE REVIEW

**Comment by manu-chroma** [comment]
hey @LadySith, thanks for your contribution. 

As highlighted by gitmate, your commit message could use some work. 
Mention the filename in the short log, also use `adds` rather than `added`

this might help: http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by LadySith** [comment]
Hi. I'm not sure if the commit title was edited but I tried to fix it just now. Do I have to resubmit the commit?

**Comment by manu-chroma** [comment]
hey @LadySith, you changed the Pull Request title and not the actual commit message. 

To change your message you just use ``git commit --amend`` and then ``git push --force`` the new commit to replace the old one. 

Reply back here or feel free to drop in at https://gitter.im/coala/coala in case you need further help :)

**Comment by sils** [comment]
apparently you made a new PR, please avoid that it usually causes people (you, not us, we don't care as long as you close your old PR) more headaches than it helps :/ rather ask on coala.io/chat for help

**Pull request closed without merging**
