### PR TITLE
Fix markup in Newcomer's Guide

### PR DESCRIPTION
**Pull request by Mariatta**
The link to promotion form was missing an underscore in the end.

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by vddesai1998** [comment]
@Mariatta  If I am not wrong your commit message should contain the link to the issue it closes or fixes.

**Comment by Mariatta** [comment]
Thanks for the review @vddesai1998. For this trivial change, I don't see a need to create an issue, so I'll bypass it.

**Comment by Makman2** [comment]
Seems like there's an underlying issue: https://github.com/coala/coala/issues/4880 and it's been assigned now. I have to be strict, once @Nshul has submitted a PR I will close this one.

**Comment by Makman2** [comment]
PR submitted.

**Comment by Makman2** [comment]
Sorry @Mariatta :/

**Pull request closed without merging**
