### PR TITLE
aspects: Add Root aspect

### PR DESCRIPTION
**Pull request by sils**
@Asnelchristian

### CODE REVIEW

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala/pull/2953/commits/47f96232e78584b9a1addcc152909a029f240385

**Comment by adtac** [comment]
@sils ow coverage - these lines should be covered by the doctests, right?

**Comment by sils** [comment]
no idea, I restarted the build but it failed again. Also only one of them fails which means coverage is full for the otehr?

**Comment by sils** [comment]
this is included in another PR

**Comment by sils** [comment]
https://github.com/coala/coala/pull/2950

**Pull request closed without merging**
