### PR TITLE
gsoc: Add "Executing section <section>..."

### PR DESCRIPTION
**Pull request by Nosferatul**
Closes https://github.com/coala/coala/issues/4598

### CODE REVIEW

**Comment by damngamerz** [comment]
Looks good to me... I think CI is hanged... repush the commit :)

**Comment by Adrianzatreanu** [comment]
ack 32c7932

**Comment by jayvdb** [comment]
needs rebase

**Comment by Nosferatul** [comment]
reack 6935923

**Comment by Nosferatul** [comment]
@rultor merge

**Pull request merged**
