### PR TITLE
Fix invalid escape sequence and remove W605 from ignore list

### LINKED ISSUE #5383: Remove W605 from ignore list and fix invalid escape sequence
As per discussed in https://github.com/coala/coala/issues/5372#issuecomment-381314867

https://github.com/coala/coala-bears/pull/2432 can help.

importance/high
difficulty/low

### PR DESCRIPTION
**Pull request by seeeturtle**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!
https://github.com/coala/coala

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

Closes #5383

### CODE REVIEW

**Comment by palash25** [comment]
@seeeturtle please squash your commits into a single commit This might help http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by seeeturtle** [comment]
sorry, i just squashed it.

**Comment by yzgyyang** [comment]
Please refer to https://coala.io/commit for commit message guidelines, and this similar PR might help: https://github.com/coala/coala/pull/5399

**Comment by palash25** [comment]
@seeeturtle change it to something like
`Remove W605 and fix invalid escape sequence `
I hope thats 50 chars

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5472/commits/c504deb6c61a10ba2338351cd1e67b3eff2a1821

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
