### PR TITLE
Writing_Good_Commits.rst: Remove extra "and"

### PR DESCRIPTION
**Pull request by shrutishrm512**
### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
- [x] I have followed the [guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference).
- [x] I have [run all the tests](http://coala.readthedocs.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### Reviewers

Closes https://github.com/coala/coala/issues/3257

### CODE REVIEW

**Comment by Mariatta** [comment]
ack 6e36abc

**Comment by Mariatta** [comment]
unack 6e36abc

**Comment by Mariatta** [comment]
@yash-nisar is correct. Please follow the suggestions.

**Comment by shrutishrm512** [comment]
okay ! I will make changes as per suggestions.

**Comment by Udayan12167** [comment]
ack 
https://github.com/coala/coala/pull/3272/commits/7f3a035e67461fe1e68caaf47e2f3122560b6f9e

**Comment by Udayan12167** [comment]
@rultor merge

**Pull request merged**
