### PR TITLE
ConsoleInteraction.py: Typo in docstring 

### PR DESCRIPTION
**Pull request by HyungKen**
ConsoleInteraction.print_result: Fix docstring

Fixes https://github.com/coala/coala/issues/4018

### CODE REVIEW

**Comment by arjunsinghy96** [comment]
Please follow our [commit guidelines](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html) for writing commit messages.

**Comment by HyungKen** [comment]
I read the commit guideline. Are there any incorrect commit message parts?

**Comment by HyungKen** [comment]
Is that about the commit body?
Like I did now?

**Comment by userzimmermann** [comment]
@HyungKen Almost ;) It's not about your pull request message. It's about your git commit message. Just re-commit with `git commit --amend` to change it. Then re-push your branch with `-f` (force). For more details look at:

https://help.github.com/articles/changing-a-commit-message/

**Comment by HyungKen** [comment]
Thank you for a detailed description.

**Comment by meetmangukiya** [comment]
@userzimmermann I went through typo commits in coala `git log --oneline | grep typo` it seems that we have most of the commits in this form `File: Fix typo <typo> -> <correct>` So I think we should promote this in future

**Comment by HyungKen** [comment]
I modified it yesterday. Is there anything I need to fix?

**Comment by userzimmermann** [comment]
@HyungKen It's ok! We are just busy people ;)

@meetmangukiya Good idea! I opened https://github.com/coala/coala/issues/4034

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/4024/commits/b3807f63412a5868188a13c5bd4e82b9c2726a48

**Comment by userzimmermann** [comment]
@rultor merge

**Comment by userzimmermann** [comment]
@HyungKen Want to take over https://github.com/coala/coala/issues/4034 ? :)

**Comment by HyungKen** [comment]
yeah , i try it

**Comment by userzimmermann** [comment]
@HyungKen Oops :) Merging failed... Please try to rebase your branch on coala's master and push again:

http://api.coala.io/en/latest/Developers/Git_Basics.html#rebasing

**Comment by HyungKen** [comment]
I did a rebase. I am not familiar with rebase, but is this correct?

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/4024/commits/b4307554d8c5b6a23b12f52802e8b5cbda8b8db0

**Comment by userzimmermann** [comment]
@rultor merge

**Comment by userzimmermann** [comment]
@HyungKen Very correct :) Now that you learned all that stuff, we can't wait for your next PRs!

**Pull request merged**
