### PR TITLE
Modifying Newcomer's guide : Add a general command to label a PR as process/pending review

### PR DESCRIPTION
**Pull request by Kanav-7**
Closes https://github.com/coala/coala/issues/4766

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by nvzard** [comment]
There is no commit body. Please add a commit body and [never close a Pull Request unless you are told to do so](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-6-waiting-for-review).

**Comment by Kanav-7** [comment]
@nvzard Added commit body. Can you please review now.

**Comment by Kanav-7** [comment]
@prnvdixit Sorry for that. I am new to open source and didn't knew about it. I will keep that in mind next time onwards.

**Comment by Kanav-7** [comment]
@prnvdixit Thanks :sweat_smile:

**Comment by nvzard** [comment]
ack 621964d

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
