### PR TITLE
Update ConfigurationGathering.py

### PR DESCRIPTION
**Pull request by ppatel221**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by ishanSrt** [comment]
So,
1st: Please reference the issue link on your PR next time onwards. I am doing it for you https://github.com/coala/coala/issues/5025#issuecomment-355074126

2nd: You have done everything wrong, read the issue heading, see what a doctsring in python means. thats why all the tests are failing.

3rd: Please follow the commit guidelines at https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by ishanSrt** [comment]
unack https://github.com/coala/coala/pull/5032/commits/93ae46cd3eaa40fd65c61b2fe3f4a1c2b735d013

**Comment by ishanSrt** [comment]
@ppatel221 the issue just asks for changing the doctoring and nothing else. also squash your commits into one

**Comment by ppatel221** [comment]
Alright I've changed the documentation: return values of True and False are interchanged.

**Comment by ishanSrt** [comment]
@ppatel221 https://github.com/coala/coala/pull/5032#issuecomment-355081350

**Comment by ishanSrt** [comment]
@ppatel221 
> also squash your commits into one

https://github.com/coala/coala/pull/5032#issuecomment-355081350

**Comment by ishanSrt** [comment]
also make a commit message according to the commit guidelines

**Comment by ishanSrt** [comment]
@prnvdixit 👍 will take care from now on

**Comment by jayvdb** [comment]
Fixed by https://github.com/coala/coala/pull/5093

**Pull request closed without merging**
