### PR TITLE
Fix rst problems in sphinx

### PR DESCRIPTION
**Pull request by Siddhartha1234**
This ensures the asterisk is bypassed in the docstring.

Fixes https://github.com/coala/coala/issues/3334

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [ ] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by hemangsk** [comment]
Hey @Siddhartha1234 ! You can resolve these errors by running coala on the code

**Comment by Mixih** [comment]
Can you fix the other error there too? I want to merge a clean file so we can enable rst bear on this one too.
`/home/ubuntu/coala/docs/Developers/Newcomers_Guide.rst:4: WARNING: Duplicate explicit target name: "here".`

**Comment by Mixih** [comment]
ack f2a97d1

**Comment by Mixih** [comment]
@rultor merge

**Comment by Mixih** [comment]
ah, well, we'll probably have to batch merge this

**Comment by jayvdb** [comment]
Can we try rebasing and re-merging?

**Comment by Mixih** [comment]
@Siddhartha1234 Please rebase

**Comment by Siddhartha1234** [comment]
@Mixih , rebased ..try merging

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala/pull/3341/commits/f42100b805ca8c22014683bdd2f0e7c83d0f87e5

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
