### PR TITLE
 Executing_Tests.rst: Fix a grammatical mistake

### PR DESCRIPTION
**Pull request by Kagamihime**
This changes `testing` to `test` for better readability.

Closes https://github.com/coala/coala/issues/3956

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jackthepirate6** [comment]
LGTM

**Comment by ishanSrt** [comment]
Wait this is not a typo, but just a grammatical mistake. so change your shortlog and body. Keep using `Closes` 👍

**Comment by Kagamihime** [comment]
So I say that it fixes a grammatical mistake?

**Comment by ishanSrt** [comment]
Anything that explains what you are doing.

**Comment by Kagamihime** [comment]
I have to change the shortlog to `Executing_Tests.rst: Fix a grammatical mistake` and the commit body to `Change "testing" to "test" for better readability.`, if I'm right?

**Comment by newbazz** [comment]
@Kagamihime yup, you are right ;)

**Comment by Kagamihime** [comment]
I've applied the changes to my commit :)

**Comment by Makman2** [comment]
Do you like to fix the commit authorship to point to your GitHub account?

**Comment by Makman2** [comment]
Commit looks good otherwise

**Comment by Kagamihime** [comment]
Oh no, I didn't notice that. I changed my e-mail on my GitHub account yesterday but I've forgotten to change it on my computer...

**Comment by Makman2** [comment]
ack 7e670fb2065cc6a7990a656321b1a25fab10d69a

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
