### PR TITLE
docs: Correct spelling mistakes

### LINKED ISSUE #4816: Fix spelling and grammatical errors in documentation.
Find mistakes in current documentation and enhance it.

https://github.com/coala/coala/tree/master/docs

### PR DESCRIPTION
**Pull request by margobra8**
This corrects the current spelling mistakes
found in /docs and is a hotfix until
`SpellCheckBear` can be added to CI tests.

Fixes #4816

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by newbazz** [comment]
unack 27244fbe22a8b61a1cc2b4670b06b4baa061f5a1

**Comment by margobra8** [comment]
@newbazz ping

**Comment by newbazz** [comment]
ack 77f3b7a42f84fb4142a712dc8e02dfef54cf2730

**Comment by Makman2** [comment]
The issue is not yet solved:
> and prevent them from re-occurring by improving the .coafile.

However I would allow a merge if you change the issue reference to "Related to ..." instead of "Closes ...", fixing spelling errors is always good :+1:

> until `SpellCheckBear` can be added to CI tests.

Why it can't be added?

**Comment by Makman2** [comment]
unack 77f3b7a

**Comment by Makman2** [comment]
Closing due to inactivity.

**Pull request closed without merging**
