### PR TITLE
requirements.txt: pytest-profiling version changed to 1.7.0

### LINKED ISSUE #6165: Travis build failure due to setuptools-git
From [build](https://travis-ci.com/github/coala/coala/jobs/505462177):

```
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-git')
```

### PR DESCRIPTION
**Pull request by anshalshukla**
Adding PR on gitlab for moban sync

Closes #6165

### CODE REVIEW

**Comment by anshalshukla** [comment]
Created [MR](https://gitlab.com/coala/mobans/-/merge_requests/144) for mobans sync.

**Comment by anshalshukla** [comment]
@abhishalya, I think we can get this merged now. I didn't notice the commit message error yesterday have fixed it now.

**Comment by abhishalya** [comment]
@anshalshukla Please take care of your commit messages, they are always wrong. I won't always clean up for you.

Also, don't hard pin the dependencies, we won't do that in a master branch as we want to keep the dependencies as updated as we can.

**Comment by abhishalya** [comment]
Also, whenever there's an issue like this (where we want to get changes in moban updated first) then you can add a temp commit here to change the source for the moban repo -- this helps us get the moban result as well. Later we can simply delete that commit and merge the MR and proceed with this.

**Comment by anshalshukla** [comment]
@abhishalya I'll take care of the points mentioned in future.

**Pull request merged**
