### PR TITLE
added backticks

### PR DESCRIPTION
**Pull request by aastha980**
Signed-off-by: aastha <aastha980@gmail.com>

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by palash25** [comment]
Your commits don't follow the commit guidlines please have a look at [how to write good commits](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html) and edit your commit accordingly. Also it is not recommended to have multiple commits so squash your commits. Read this [guide](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html).

**Comment by stellargo** [comment]
While I was reviewing this PR, I realized I don't understand why circleci is failing. Could anybody tell me just for the sake of future knowledge :)

**Comment by nvzard** [comment]
Please make the changes suggested above by @palash25

**Comment by Makman2** [comment]
```
coala --non-interactive

[WARNING][14:16:39] Implicit 'Default' section inheritance is deprecated. It will be removed soon. To silence this warning remove settings in the 'Default' section from your coafile. You can use dots to specify inheritance: the section 'all.python' will inherit all settings from 'all'.
Executing section python...
Executing section flakes...
Executing section autopep8...
Executing section linelength...
Executing section DOCS...
Executing section commit...
[nltk_data] Downloading package punkt to /home/ubuntu/nltk_data...
[nltk_data] Error downloading 'punkt' from
[nltk_data]     <https://raw.githubusercontent.com/nltk/nltk_data/gh-
[nltk_data]     pages/packages/tokenizers/punkt.zip>:   [Errno 104]
[nltk_data]     Connection reset by peer
[ERROR][14:17:51] Bear GitCommitBear failed to run. Take a look at debug messages (`-V`) for further information.
Executing section css...
Executing section rst...
Executing section text...
Executing section urllib...
Executing section cli...

coala --non-interactive returned exit code 1
```

**Comment by nvzard** [comment]
@aastha980  @Makman2 this issue has been (closed)[https://github.com/coala/coala/issues/4671]. You need to close this PR.

**Pull request closed without merging**
