### PR TITLE
Newcomers_Guide.rst: Changed the text "step4" to "step3".

### PR DESCRIPTION
**Pull request by snakevenom04**
The text was wrong.

Closes https://github.com/coala/coala/issues/4509

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Nosferatul** [comment]
you have 2 prs for newcomers please proceed to `low` issues.

**Comment by snakevenom04** [comment]
Yep on it :) Thanks !

**Comment by IpshitaC** [comment]
ack 4f6655a4ed1ff01f1c1f660e6285e829d80b6ae6

**Comment by snakevenom04** [comment]
rebased

**Comment by adhikasp** [comment]
reack 39102b6527e248f06c20334f04d68a75f662dd0e

**Comment by swapagarwal** [comment]
ping

**Comment by Makman2** [comment]
Looks good.

**Comment by Makman2** [comment]
ack 39102b6

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by newbazz** [comment]
@snakevenom04 also make the commit body a bit descriptive.

**Comment by jayvdb** [comment]
Already done

**Pull request closed without merging**
