### PR TITLE
coafile: Disable E303 for PycodeStyleBear

### PR DESCRIPTION
**Pull request by shreyans800755**
This commit disables E303 message since it is already
covered by pep8bear.

Closes https://github.com/coala/coala/issues/3556

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
The commit shortlog should be `.coafile: ...`

**Comment by shreyans800755** [comment]
@jayvdb Updated. Not sure why gitmate-bot is giving errors on files that are not being updated by this commit.

**Comment by shreyans800755** [comment]
@jayvdb @Makman2 
Something wrong with gitmate ?
review/gitmate/commit is still in progress after 19 hours of commit push. And gitmate/pr giving errors on files not being updated by the commit.

**Comment by Makman2** [comment]
Hm that's weird. The CI does flag the same issues in the coala run. Deleted the comments so they don't bother here :+1: Have you tried to rebase? Maybe that helps already :/

**Comment by Makman2** [comment]
Ahhh wait a second. You change our coafile to ignore only E303 errors. That means all other errors that are ignored by default aren't ignored any more. You need to copy the default list too :) That's why coala suddenly starts to flag issues in files not affected, as the code rules did change :)

**Comment by Makman2** [comment]
You can find the default list in the `PycodeStyleBear` inside the `coala/coala-bears` repo :+1:

**Comment by shreyans800755** [comment]
@Makman2 I don't see any default values in `pycodestyleBear` at https://github.com/coala/coala-bears/blob/master/bears/python/PycodestyleBear.py#L24.
List is empty by default.
Am I missing something ?
(Branch seems to be updated already, no need to rebase.)

**Comment by Makman2** [comment]
Looks like `pycodestyle` has defaults itself: https://pypi.python.org/pypi/pycodestyle
> Added W503 to the list of codes ignored by default ignore list;

Found them here: https://pycodestyle.readthedocs.io/en/latest/intro.html
> the checks E121, E123, E126, E133, E226, E241, E242, E704 and W503 are ignored

**Comment by SanketDG** [comment]
so, ideally, we need to have these in the default str argument of pycodestyle, @shreyans800755 can you open an issue?

**Comment by shreyans800755** [comment]
@Makman2 Are we waiting for https://github.com/coala/coala-bears/issues/1739 to merge first ?

**Comment by Makman2** [comment]
Nope you were first ;) Also it's not ready, changing the type to `typed_list(str)` requires to tweak some code :+1:

**Comment by Makman2** [comment]
ack 6d94643

**Comment by Makman2** [comment]
@rultor merge

**Comment by meetmangukiya** [comment]
@rultor merge!

**Comment by Makman2** [comment]
Ah it's not rebased ;)

**Comment by shreyans800755** [comment]
@Makman2 Branch seems to be updated. Even `Update branch` button is disabled.
And I tried to push again after rebase with master and it shows status as `up-to-date`.

**Comment by SanketDG** [comment]
@Makman2, known error, see its `gpgconf command not found`

See https://github.com/yegor256/rultor/issues/1177

**Comment by Makman2** [comment]
Oh sorry I though because the green buttong stated "rebase and merge" it's out of sync again. My bad^^

Ah okay then we have to wait it seems.

**Comment by shreyans800755** [comment]
@Makman2 Issue https://github.com/yegor256/rultor/issues/1177 is closed. Can you please try again to merge ?

**Comment by meetmangukiya** [comment]
@shreyans800755 please rebase

**Comment by shreyans800755** [comment]
@meetmangukiya Rebased.

**Comment by meetmangukiya** [comment]
ack 3fc3c08

**Comment by meetmangukiya** [comment]
ack

**Comment by meetmangukiya** [comment]
ack 3fc3c089ae90e298cd224fc78938fa76cbb51883

**Comment by meetmangukiya** [comment]
@rultor merge

**Pull request merged**
