### PR TITLE
core: Add FileProxy

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by sils** [comment]
CC @jayvdb

**Comment by sils** [comment]
@jayvdb our stand on this right now: merge this ASAP so we got something that's already better than what we have. This defines a nice API, we tried to leave out some simplifications so the user isn't tempted to do badly performant things, i.e. we removed the `__len__` wrapper etc.

We can change this and add caching and everything underneath later.

**Comment by sils** [comment]
ack a9ccaea0508a346caa9af55caeea2fd9d814fa1b

**Comment by sils** [comment]
unack a9ccaea as per discussion with @jayvdb we'll pause this.

@jayvdb we're working around this, you don't need to stress yourself too much.

**Comment by Makman2** [comment]
Shall we merge this anyway? I kinda want to have it as an initial point for the future `FileProxy`^^

**Comment by Makman2** [comment]
The "factory" term and approach do fit more into the picture. Keeping the branch alive for reference.

**Pull request closed without merging**
