### PR TITLE
DocBaseClass.py: Move class to new file

### PR DESCRIPTION
**Pull request by troublemagnet**
Rename the existing DocBaseClass.py to DocumentExtraction.py
and move the DocBaseClass to a new DocBaseClass.py.

Closes https://github.com/coala/coala/issues/4507

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by troublemagnet** [comment]
This one test seems to fail, however I proceeded just like my previous PR where all the tests passed. @SanketDG or @hemangsk  can you please help me with this?

**Comment by SanketDG** [comment]
@damngamerz can you take a look at why the tests are failing? It is related to your changes

**Comment by damngamerz** [comment]
@troublemagnet I don't see any reason why this shouldn't work. Anyway tried to run the tests locally?

**Comment by troublemagnet** [comment]
@damngamerz yes I did. Seems to work fine locally.

**Comment by damngamerz** [comment]
@troublemagnet maybe give a rebase and force push. Sometimes(most of the times) CI is weird :P

**Comment by troublemagnet** [comment]
@damngamerz Still fails :(

**Comment by troublemagnet** [comment]
@SanketDG and @damngamerz Sorry, that was my bad. The strip() splicing wasn't there in the DocumentExtraction.

**Comment by SanketDG** [comment]
Nice, but you now have an extra file in your commit, you may want to remove that. :smile:

**Comment by troublemagnet** [comment]
@SanketDG fixed, squashed and rebased :D

**Comment by damngamerz** [comment]
@troublemagnet One more thing the commit message doesn't seems right. Can you please change it.
It's like 2-3 Instances are copied. You will notice what I m talking about :)

**Comment by SanketDG** [comment]
ack 0415ef1

**Comment by SanketDG** [comment]
@rultor merge

**Comment by SanketDG** [comment]
@rultor stop

**Pull request merged**
