### PR TITLE
Newcomers_Guide: Remove grey colored patches

### LINKED ISSUE #5333: Remove extra colon in Newcomers Guide
See https://github.com/coala/coala/pull/5119 
The grey colored patches over yellow background are due to the extra colon before the exemplar commands. Just remove one colon and it will look fine.

### PR DESCRIPTION
**Pull request by nityanandagohain**
### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

Closes #5333

### CODE REVIEW

**Comment by nityanandagohain** [comment]
@jayvdb please check the commit message now whats wrong in there.

**Comment by nityanandagohain** [comment]
@IpshitaC I have updated it please check.

**Comment by IpshitaC** [comment]
Click on the build link for [Circle CI](https://circleci.com/gh/coala/coala/17220?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and click on the rerun job button.
Similarly for other CIs

**Comment by ishanSrt** [comment]
@kriti21 this seems to be making the problem about the bad looking heading severities even worse, 
and why only target yellow bg color? the code formatting looks as bad as on any other bg color,
screen shot 2018-04-29 at 10 57 25 am
just removing the code formatting on some lines doesn't seem an appropriate fix if this is all you are trying to change,
screen shot 2018-04-29 at 11 03 03 am
screen shot 2018-04-29 at 11 02 41 am
This is removing the code styling on what are commands which should not be encouraged.
This issue should be labeled `status/blocked` and this PR closed as this will automatically get fixed when the entire theme is fixed such that when commands are formatted as code, they look great on bg colors of all severities.

**Comment by kriti21** [comment]
@ishanSrt I get that removing colons is not the right approach (I have changed the issue heading as well). Apology for that. However, I am not sure if this will get fixed automatically though. @nityanandagohain You might as well close this PR for now.

**Comment by nityanandagohain** [comment]
ok :(

**Comment by ishanSrt** [comment]
Is there an issue created to fix the colors according to the theme?

**Comment by kriti21** [comment]
Nope but IMO multi colored theme is just for Newcomers guide only so https://github.com/coala/coala/issues/5333 should do it. And https://github.com/coala/coala/issues/5423 is also there.

**Comment by ishanSrt** [comment]
>Otherwise it would require changes in css file and that would not be as simple.

That seems better

**Comment by kriti21** [comment]
Yeah... So @nityanandagohain You can try making changes in CSS. If it works out, make sure to reopen this PR with your modified changes. :)

**Comment by Gromy1211** [comment]
HI, I am working on this issue https://github.com/coala/coala/issues/5333 I think I need to change colors in css file. Does that mean I can change the color according to my understanding to beauty?

**Pull request closed without merging**
