### PR TITLE
coala-json to coala --json in external_bears.rst

### PR DESCRIPTION
**Pull request by harshit890**
### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [x] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by Mixih** [comment]
Can you fix you commit message error and add a link to the issue you fixed using the style we have over here: http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html ? If you don't have an issue, please open one with a detailed description of why this is necessary. Thanks!

**Comment by Techievena** [comment]
@harshit890 You need not write all those statements in your git commit body. Just elaborate the fix you have made in body. And the implication of bad word doesn't asks you to remove that word. Avoid words like changed and instead use words like change or  something of that sort and also below mention Closes issue #?/Fixes issue #?. I suggest you take a look at commit messages of previously merged pull requests

**Comment by Techievena** [comment]
Great!! Everything looks perfectly fine. Ask in gitter channel to merge this commit.
__NOTE: MAKE SURE YOU HAVE REBASED THE COMMIT PROPERLY___

**Comment by Techievena** [comment]
ack  	02ef584

**Comment by adtac** [comment]
ack https://github.com/coala/coala/commit/02ef5846628d443aa2ff5e5f04e8b2fe447680f6

**Comment by adtac** [comment]
@rultor merge

**Comment by adtac** [comment]
@rultor stop

**Comment by adtac** [comment]
@harshit890

It looks like your PR is out of date and needs a rebase. [This page](http://coala.io/git) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

We also have a quick video tutorial on how to rebase: [https://asciinema.org/a/78683](https://asciinema.org/a/78683). That should help you understand the basics of how it works and what you should be doing.

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

(Be sure to use the coala-bears URL if you're on coala bears!)

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Comment by nemaniarjun** [comment]
Hate to ask you to edit again, but your commit message says `docstring` this is not a docstring.
Just use `note` instead of it.

**Comment by nemaniarjun** [comment]
ack 5f65fbd

**Comment by Mixih** [comment]
needs rebase, but otherwise good.

**Comment by sims1253** [comment]
ack 56936b0

**Comment by harshit890** [comment]
do i need to make anyother change in it or it is ready to b merged...

**Comment by nemaniarjun** [comment]
Have you rebased? Do a rebase and this will be merged. :)

**Comment by harshit890** [comment]
did it after my last commit

**Comment by harshit890** [comment]
did it after my last commit ....do i need to rebase it again

**Comment by adtac** [comment]
You need to rebase - other commits have been merged into master since then.

**Comment by harshit890** [comment]
i have rebased it ...is it ok now

**Comment by hemangsk** [comment]
ack #25ca975e33a1d59e7a14be4f34854edb00a45f02

**Comment by hemangsk** [comment]
ack 25ca975e33a1d59e7a14be4f34854edb00a45f02

**Comment by harshit890** [comment]
@adtac @hemangsk is it ready to b merged

**Comment by Makman2** [comment]
Cherry-picked into https://github.com/coala/coala/pull/3520

**Pull request closed without merging**
