### PR TITLE
Constants.py: Removed unused import

### PR DESCRIPTION
**Pull request by tusharmakkar08**
Removed `BUS_NAME` and fixed the test `BuildDbusServiceTest.py`
which failed when removed the given import.

Fixes https://github.com/coala/coala/issues/2902

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
hey could you please work on your commit message?

A better shortlog would be:
``Constants: Remove unused import``

as for body:

``Removes unused DBUS import because ...... etc``

**Comment by Adrianzatreanu** [comment]
Also, its not a bug, its a quick enhancement, should use Closes instead of Fixes.

**Comment by tusharmakkar08** [comment]
@Adrianzatreanu : It says `Remove` is a bad word apparently.

**Comment by tusharmakkar08** [comment]
@Adrianzatreanu : Updated the commit message.

**Comment by Nosferatul** [comment]
Also please rebase. If you need help, drop on gitter and ask cobot to help you( `cobot explain rebase`)

**Comment by Adrianzatreanu** [comment]
It cant be, it should be like i said, try pushing like that please :) thanks. also, rebase needed

**Comment by tusharmakkar08** [comment]
Done @Adrianzatreanu and @Nosferatul

**Comment by Nosferatul** [comment]
Your rebase went wrong! Please check https://docs.coala.io/en/latest/Developers/Git_Basics.html to squash your commits

**Comment by Nosferatul** [comment]
Or drop on gitter and ask us!

**Comment by Nosferatul** [comment]
Something went wrong, as you see your branch is 1 commit behind

**Comment by tusharmakkar08** [comment]
Done @Nosferatul .

**Comment by Nosferatul** [comment]
Rebasing
As people work on coala new commits will be added. This will result in your local fork going out of sync with the remote repository. To sync your changes with the remote repository run the following commands in the desired branch:

$ `git fetch origin`
$ `git rebase origin/master`
This will fetch the commits from the remote repository and will merge it into the branch where you are currently working, and move all of the local commits that are ahead of the rebased branch to the top of the history on that branch.

Note
After following these instructions when you try to push to remote you may get fast-forwarding error. If that is the case, then you will have to force push since you are attempting to rewrite the git commit history. To do that append the --force argument in the push command:

$ `git push myfork --force`

Warning: Never force-push on the master branch, or any branch not owned by you.
To verify whether you have rebased correctly, go to the web page of the branch in your fork. If it says your branch is n commits behind coala:master (or whichever repo you are contributing to), then you haven’t correctly rebased yet. Otherwise, you’re good to go!

**Comment by tusharmakkar08** [comment]
I am closing this PR due to some issue in rebasing.

**Comment by tusharmakkar08** [comment]
Hey @Nosferatul and @Adrianzatreanu 

Please review https://github.com/coala/coala/pull/2944 instead. 

Thanks.

**Pull request closed without merging**
