### PR TITLE
LogPrinter: Fix "occured"->"occurred"

### PR DESCRIPTION
**Pull request by Pratik151**
Fixes issue : https://github.com/coala/coala/issues/2486

### CODE REVIEW

**Comment by sims1253** [comment]
Hey thanks for your contribution.
The change looks finde but the commit message needs another touch.
Can you please take a look at the commit message guidelines and rework accordingly? Just amend the commit and change the message.
https://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by Pratik151** [comment]
@sims1253 Thanks for your reply. Modified the commit message. 
Does it look good or any other changes needed?

**Comment by Adrianzatreanu** [comment]
well its not basically an update, and i like this format more: ``LogPrinter: Fix "occured"->"occurred"``

also, apperas like you need a rebase :)

**Comment by Pratik151** [comment]
@Adrianzatreanu  Changed to `LogPrinter: Fix "occured"->"occurred"`

**Comment by Adrianzatreanu** [comment]
you failed somewhere in your rebase, we dont want merge commits :( 

follow this: 
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.io/git) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

We also have a quick video tutorial on how to rebase: [https://asciinema.org/a/78683](https://asciinema.org/a/78683). That should help you understand the basics of how it works and what you should be doing.

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

(Be sure to use the coala-bears URL if you're on coala bears!)

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Comment by Adrianzatreanu** [comment]
ack 63fc82fd5c47c82cf833dc537ea4c42d37a98bf6

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
