### PR TITLE
custom.css: Add styling to various elements

### LINKED ISSUE #3792: docs: Update styling to match with coala/documentation
Involves replicating all the styling changes done in documentation repo to Developer docs https://github.com/coala/documentation/commit/bfa74dcd0bba647508c48090f169c71e4bcc1946

Opened via [gitter](https://gitter.im/coala/coala/?at=58b33ca27ceae5376a41b530) by @hemangsk

### PR DESCRIPTION
**Pull request by hemangsk**
Closes #3792

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by hemangsk** [comment]
<p align="center" >Screenshots</p>


- Dark background in the Note Block
- Font weights

<p align="center"></p>



- Header image
<p align="center"></p>


- Code Blocks
<p align="center"></p>

**Comment by yukiisbored** [comment]
ack 0ec02c6c3ef0cab57a16858edd7a32d2fdecbf78

**Comment by yukiisbored** [comment]
ack c026a8b49b5ea322d263c636aaf0507765e82035

**Comment by yukiisbored** [comment]
ack aaf42d86845ac35d3f1c6ff797086577e48c3875

**Comment by sils** [comment]
Cherry picked onto https://github.com/coala/coala/pull/3923 for mass merge, thanks for your contribution! :)

**Pull request closed without merging**
