### PR TITLE
 Executing_Tests.rst: Fix Typo Error

### PR DESCRIPTION
**Pull request by imshashwataggarwal**
Fixes Typo Error in Executing_Tests.rst from testing to test.

Fixes https://github.com/coala/coala/issues/3956

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by supergr35** [comment]
You can't just change the title, you need to amend your commit. Please check our commit docs.

**Comment by ashwini0529** [comment]
Can you please change your commit message from `Fixed Typo Error` to `Fix a typo`

**Comment by ashwini0529** [comment]
Again same thing. Please xhange your commit message. You can do it by `git commit --amend -m 'commit message'`

**Comment by supergr35** [comment]
It's in the git basics guide 👍

**Comment by jayvdb** [comment]
Just noting the changes are correct, but we can not accept two commits for this, and the commit message must be following our commit guidelines.  Please squash your two commits into one commit, and amend the commit message.
Come join us on http://coala.io/chat if you need help.

**Comment by supergr35** [comment]
ping @imshashwataggarwal are you still working on this?

**Pull request closed without merging**
