### PR TITLE
README.rst: Fix typo "langauge" -> "language"

### PR DESCRIPTION
**Pull request by shrutishrm512**
There is a change in line 149, changing langauge to language.

Closes https://github.com/coala/coala/issues/2935

### CODE REVIEW

**Comment by sils** [comment]
you need to put a `Closes <full issue url>` *including the closes* keyword in the commit message to autoclose the issue, otherwise it's all good :+1:

**Comment by sils** [comment]
i.e. this is an approval except this one tiny thing

**Comment by shrutishrm512** [comment]
I have made the changes in commit message .by adding Closes <issue url>

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/2947/commits/5cfd082ebbac95c1ae47fae3026e9a08229bc6c5

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

You can help us a lot by filling out <http://coala.io/newform>!

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

We would really appreciate it if you could help us with

- some code reviews for other newcomers
- fixing at least a difficulty/low issue

We're all volunteers and we're currently struggling to keep this up. Helping all those newcomers is a lot of work and we do need your help so we can continue this for others!

**Comment by shrutishrm512** [comment]
Yes, it is my first contribution. I have just started contribution for coala ! Please suggest the next bug !

**Comment by sils** [comment]
see coala.io/low

**Pull request merged**
