### PR TITLE
ConfigurationGathering.py: Corrected spelling error "Alernative" to "…

### PR DESCRIPTION
**Pull request by snakevenom04**
…Alternative"

Spelling was wrong.

Closes https://github.com/coala/coala/issues/4518

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Nosferatul** [comment]
I don't like `Spelling was wrong`. Just `This change alernative to alternative`

**Comment by snakevenom04** [comment]
Oh okay ! I ll edit the commit message

**Comment by IpshitaC** [comment]
ack a480efa9cc639a4bbeaac1308e0cda5c56c7cbd4

**Comment by shreyans800755** [comment]
@snakevenom04 Please follow the guidelines for commit message given at coala.io/commit and update it accordingly.
You can write something like:
```
ConfigurationGathering: Fix typo in docstring
<Description>
Fixes <issue link>
```

unack a480efa

**Comment by snakevenom04** [comment]
Strictly speaking it is following all the guidelines (file tag isnt compulsory) but sure, I ll change it.

**Comment by snakevenom04** [comment]
rebased

**Comment by Nosferatul** [comment]
ack 8035c83

**Comment by Nosferatul** [comment]
@rultor merge

**Comment by shreyans800755** [comment]
@snakevenom04 Appreciate it.

**Pull request merged**
