### PR TITLE
Add deps fix to the 0.10 branch

### PR DESCRIPTION
**Pull request by Mixih**
### Checklist

- [ ] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [ ] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [ ] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [ ] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [ ] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [ ] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

**After you submit your pull request, DO NOT click the 'Update Branch' button**

### CODE REVIEW

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala/pull/3631/commits/284bd62180fb5ae3292af67b13dd701e0ea07316

**Comment by gkrishnan724** [comment]
ack 284bd62

**Comment by Asnelchristian** [comment]
reack https://github.com/coala/coala/pull/3631/commits/284bd62180fb5ae3292af67b13dd701e0ea07316

**Comment by Mixih** [comment]
@rultor merge

**Pull request merged**
