### PR TITLE
Addition of Visual Studio Code to the list of known editors

### PR DESCRIPTION
**Pull request by flowkraD**
Issue in focus: #5150 

Added VSCode to the list of known GUI Editors.

Clarifications:
- VSCode is has it's path linked to variable `code`, hence the name code. This is true for Windows, MacOS and Linux(Arch Linux, Ubuntu and Linux Mint are tested upon) and is evident from their documentation on [Windows](https://code.visualstudio.com/docs/editor/command-line) and [macOS](https://code.visualstudio.com/docs/setup/mac)

There is an internal command too, to set the path variable specifiaclly to `code` as can be seen from this gif:
VSCode Path

Guidance Required:
- There exists a way to open a file to a particular line and position in VSCode but doesn't follow the scheme like the rest of the editors. In order to open a file to a particular location, the command goes: 
`$code <file_name>:{line}:{column} -g`. Here the `-g` is mandatory. If `-g` is failed to be specified, a new file with peculiar extension is opened. 
For Ex: `.j:8:9` would be the extension of the file.
This is even specified in their docs found [here](https://code.visualstudio.com/docs/editor/command-line)
So the question arises should the `-g` be put as an args or should it be included in the file opening scheme itself.

Desription of args parameters:
- `-g` - Goto a specific line
- `-n` - Open new window
- `r` - Reuse current window
- `--wait` - Wait for the file to be closed before returning.

Any changes required will be implemented as soon as possible.

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by flowkraD** [comment]
Thanks @ananyaarun , I'll change it as soon as I can

**Comment by flowkraD** [comment]
I'm a bit lost on why the CI tests are failing - Is that supposed to happen or I've gone wrong somewhere? I have followed the exact format of the editor entry above mine and placed code alphabetically in the document. In case there is something to be changed, I would be happy to implement them, just need some direction (^_^)

**Comment by flowkraD** [comment]
Added reference for closing issue in the commit description. Thanks a lot @123vivekr

**Comment by flowkraD** [comment]
@jayvdb 
Added -g to `file_arg_template` as directed. I thought `-g` would be better than `-goto` as anyone using the command line does so save time in some or the other way and `-g` seemed logical.
I renamed `args` to `long_args` - i thought that's what you meant. 
In case anything needs to be changed further i would be glad to do it (^_^)

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
