### PR TITLE
DocstyleDefinition.py: Align init docstring

### PR DESCRIPTION
**Pull request by utkarshmttl**
DocstyleDefinition.py: Align init docstring

I have aligned the init docstring according to the codestyle given at http://api.coala.io/en/latest/Developers/Codestyle.html.

Closes https://github.com/coala/coala/issues/4645

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

### CODE REVIEW

**Comment by SanketDG** [comment]
> I have aligned the init docstring according to the codestyle given at http://api.coala.io/en/latest/Developers/Codestyle.html.

> Closes #4645

You should put this in the commit body too, see https://coala.io/commit

**Comment by adhikasp** [comment]
You shouldn't use first person adjective in your commit body (http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body)

The changes itself looks good :+1:

**Comment by palash25** [comment]
You should insert a newline between the commit message description and the issue reference for better readability.

**Comment by utkarshmttl** [comment]
@stellargo How should I proceed?

**Comment by swapagarwal** [comment]
ping

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by prnvdixit** [comment]
ack b50093add55b4ac8662a9bdffafc3f4728594110

**Comment by shreyans800755** [comment]
ack b50093a

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
