### PR TITLE
Indentation for  __init__ fixed. 

### PR DESCRIPTION
**Pull request by ayush1999**
Solves: #4645.
Changes the indentation in the `__init__` method to meet the required standards.

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by prnvdixit** [comment]
@ayush1999 Please refer to https://coala.io/commit 😄 - Your PR is not adhering to them 👍
Also, please squash your commits into one - Single change should get reflected in single commit 😄.

**Comment by khanchi97** [comment]
@ayush1999 now you have to squash your commits into one.

**Comment by khanchi97** [comment]
And i think in your commit you should have a shortlog and after that a short description about that.
you can take help from this http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by ayush1999** [comment]
@khanchi97  Can you tell me how can I squash from the terminal?

**Comment by khanchi97** [comment]
yeah you can learn how to squash commits into one from this link http://api.coala.io/en/latest/Developers/Git_Basics.html#squashing-your-commits

**Comment by prnvdixit** [comment]
Ughh... I missed that @ayush1999 is not assigned to this issue 😟 - No more commits before getting assigned to this issue please. 👍
Just ask by commenting on other PR https://github.com/coala/coala/pull/4646 if the assignee is still working on this? (Though I think there is "not" a lot to be done in that PR - But still ping him anyway) 😄

**Comment by ayush1999** [comment]
I don't think he is. He hasn't replied to a 12 day old ping.

**Comment by prnvdixit** [comment]
@ayush1999
I am not sure if that PR even needs any work at all - Probably a force push would be sufficient to pass all the tests.
I will still recommend to ping on the PR. Because, without assignment - this PR can't be reviewed. Just ping him and ask if he is still interested in resolving the issue, see if he responds - else, you can ask to get assigned to the issue. 😄
Next time, please ensure that you are assigned to an issue before starting working on that 👍.

**Comment by jayvdb** [comment]
dup of https://github.com/coala/coala/pull/4646

**Comment by prnvdixit** [comment]
@ayush1999 
You can pickup any other Newcomer issue from https://github.com/coala/coala/issues/ meanwhile 😄 - Just ensure that you are assigned to an issue before starting working on that as that actually saves your time. 👍

**Pull request closed without merging**
