### PR TITLE
Fixes #3259 - Modified: Writing_Good_Commits.rst

### LINKED ISSUE #3259: Developers/Writing_Good_Commits.rst: In order to do that we are ... (Reword)
_From @Udayan12167 on October 6, 2016 13:48_

_Copied from original issue: coala/documentation#149_

### PR DESCRIPTION
**Pull request by bansalnitish**
Closes #3259

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by bansalnitish** [comment]
@shashank-b @newbazz I have made the changes.

**Comment by bansalnitish** [comment]
@newbazz I have corrected the message.

**Comment by bansalnitish** [comment]
@ishanSrt I have made the changes.

**Comment by newbazz** [comment]
why is @adtac shown as assignee?

**Comment by ishanSrt** [comment]
>gitmate-bot assigned adtac 6 days ago

gitmate messed something up @newbazz 
cc @Makman2

**Comment by Makman2** [comment]
Filed issue at https://gitlab.com/gitmate/open-source/gitmate-2/issues/329

**Comment by Makman2** [comment]
Actually I'm wondering why there's some issue that wants this phrase changed. @bansalnitish just curious, do you think the old sentence reads bad?

**Comment by nvzard** [comment]
Personally, I like the old sentence :P

**Comment by Makman2** [comment]
Me too, that's why I'm asking :)

**Comment by bansalnitish** [comment]
Hi @Makman2, I feel the older sentence is not properly phrased. It reads:
``` 
We need good code. In order to do that...
```
It is not clear to do what since there is nothing mentioned about doing something in previous sentence. The previous sentence only specifies a need and ``in order to do that`` is not linking to it.

**Comment by Makman2** [comment]
> In order to do that *we are verifying that every
  change to our code (i.e. the commits) is making it better.*

Sounds pretty clear to me what has to be done :)

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5124/commits/2d08b6d11ecf17bd53b4aa882b75323957eab713

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
