### PR TITLE
rultor_secrets.sh.asc: Change key

### PR DESCRIPTION
**Pull request by adtac**

### CODE REVIEW

**Comment by sils1297** [comment]
@rultor merge

**Comment by adtac** [comment]
@rultor merge

**Comment by adtac** [comment]
@rultor merge

**Comment by adtac** [comment]
reack https://github.com/coala/coala/pull/2768/commits/17f2382d9ab2689cd0659296546c0dc90c44f6e0 https://github.com/coala/coala/pull/2768/commits/7ade464297af589100e2d62ce6e3e7ceee6c886a

**Comment by adtac** [comment]
@rultor merge

**Comment by sils1297** [comment]
You'll have to merge this one manually, rultor might take the file from the base branch not the latest.

**Comment by adtac** [comment]
Press the green button?

**Comment by adtac** [comment]
Squash and merge, right?

**Comment by adtac** [comment]
Not, squash and merge. How do I merge without the merge commit?

**Comment by adtac** [comment]
Don't worry, I didn't press the shiny green button :P

Anyway, let's see if this works.

**Pull request merged**
