### PR TITLE
Testing_Bears.rst: Update imports

### PR DESCRIPTION
**Pull request by hemangsk**
### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
- [x] I have followed the [guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference).
- [ ] I have [run all the tests](http://coala.readthedocs.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### Reviewers

Fixes: https://github.com/coala/coala/issues/3174

### CODE REVIEW

**Comment by Mixih** [comment]
Hmmmm, I would specify exactly what module you replaced in the commit body and add "import" to the title

**Comment by Mixih** [comment]
Oh, and to get the circle ack we need to merge this branch, enable circle ci on your fork.... you can login to circl with your github and just flip the switch next to this repo... This will give us a green build that allows us to merge.

**Comment by Mixih** [comment]
Never mind... DO NOT ENABLE circle on your fork.. It seems to use up coala's instances.

**Comment by adtac** [comment]
ack https://github.com/coala/coala/pull/3189/commits/6947b383c5adae2a73c0e041aeff4bf9435570a4

**Comment by adtac** [comment]
Ugh, circle is hanging...

@hemangsk could you do an empty `git commit --amend` and force push to retrigger the build?

**Comment by Mixih** [comment]
hmm circle is still dead on this one....

**Comment by sils** [comment]
please remove the colon after the `Fixes`, otherwise I think it'll not autoclose the issue

**Comment by sils** [comment]
otherwise good to go :)

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3189/commits/17b65dec6a73264f0f0a270d4e75669f4d956070

**Comment by sils** [comment]
Will cherry pick this later for merge because of this circle thing :/

**Comment by sils** [comment]
cherry picked to https://github.com/coala/coala/pull/3207

**Pull request closed without merging**
