### PR TITLE
default.py: Remove erroneous mention of docstrings

### PR DESCRIPTION
**Pull request by Sidsharik**
Removes docstrings and fixes tests to
ensure PEP257 adherence.

Fixes https://github.com/coala/coala/issues/4566

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Sidsharik** [comment]
I am not able to get you. Do you mean I need to replace docstrings with strings in my commit message?
@jayvdb

**Comment by jayvdb** [comment]
@Sidsharik , that is part of the required changes.  But you need to write a commit message which describes what was changed and why.

**Comment by jayvdb** [comment]
Ok, commit shortlog and body look good.

And the AppVeyor error looks like it was a transient problem.

However, this is not a bug in coala, so the commit should use `Closes` , not `Fixes`.

Also please do a manual rebase, so we can merge.
Check our git guide if you dont know how to do a manual rebase.

**Comment by nalinbhardwaj** [comment]
@sidsharik : That is not the right way to rebase manually. Please look at https://coala.io/rebase for the guide. coala has guides for most tasks, make sure to refer to them when doing changes.

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
