### PR TITLE
AppveyorCI: astroid not required

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by sils** [comment]
I would generally prefer commit hashes over GitHub URLs as references, also the commt message doesn't have an imperative tense verb, I'd go for "AppVeyor: Remove astroid package" or so.

**Comment by sils** [comment]
generally it seems good and I have no problem to merge it like this because those things are really nitpicky so I'll leave it to your discretion on wether you want to improve the message, discuss the issues or just merge it

**Comment by sils** [comment]
45aa8d4 is ready

**Comment by jayvdb** [comment]
reack 2fb1753

**Comment by jayvdb** [comment]
@rultor merge

**Comment by sils** [comment]
sorry but the branch is out of date

**Comment by sils** [comment]
@jayvdb I'll cherry pick it if you don't mind

**Comment by sils** [comment]
@jayvdb I have a collected PR on https://github.com/coala/coala/pull/3563

**Comment by sils** [comment]
merging with the others

**Pull request closed without merging**
