### PR TITLE
Linter.py: Replace deprecated link

### PR DESCRIPTION
**Pull request by abhishekbundela**
Updates deprecated link to new link.
Fixes coala#2976

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
hey it appears the issue you linked in the pull request is pointing to another pull request, not an issue, could you find the correct one please?

**Comment by Adrianzatreanu** [comment]
also please check coala.io/commit on writing a better commit message, this one is quite not according to our guidelines :(

**Comment by AbdealiJK** [comment]
Your commit message still doesn't meet the guidelines.
The first word should be a verb in imperative tense.

**Comment by AbdealiJK** [comment]
Also the tag in short log is needed

**Comment by sils** [comment]
Setting status to blocked as the newcomer issue is already assigned to someone else to not waste more time on double work.

**Comment by Makman2** [comment]
feel free to reopen and link commit to the right issue @abhishekbundela

**Comment by abhishekbundela** [comment]
I have replaced the invalid link. Please Merge PR.

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/2972/commits/e722d298b4c64d2d9be7b9f03d08a9b70a11e32c

**Comment by sils** [comment]
ack e722d29

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

You can help us a lot by filling out <http://coala.io/newform>!

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

We would really appreciate it if you could help us with

- some code reviews for other newcomers
- fixing at least a difficulty/low issue

We're all volunteers and we're currently struggling to keep this up. Helping all those newcomers is a lot of work and we do need your help so we can continue this for others!

**Pull request merged**
