### PR TITLE
Update release notes

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/3045/commits/0b659795c6d8b4ee02ff0d334d390c24554140ae

**Comment by sils** [comment]
0fa18b3 reack

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/3045/commits/13a3112e21a9f7b489340ccd741d8d59323347e6

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
