### PR TITLE
Update Newcomers_Guide.rst : Replaced "step 4" with "step 3"

### LINKED ISSUE #4509: Newcomer_Guide.rst: some changes in step 4
Step 4 of [Newcomer_Guide.rst](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-4-sending-your-changes) says :

> Before committing your changes, please check that you are indeed in a development branch created in  **step 4**.

 
It should be step 3 because in that step we are creating our development branch.

### PR DESCRIPTION
**Pull request by snakevenom04**
newcomers_guide.rst : Replace text "step 4" with "step 3"

Closes #4509

@

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

 Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by ihsavru** [comment]
Your commit message is not according to the guidelines. [See this](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html)
You can edit your last commit message using `git commit --amend`

**Comment by snakevenom04** [comment]
Ah yes, Thanks ! I ll update it right away

**Comment by yash-nisar** [comment]
Amend your commit message as [suggested](https://github.com/coala/coala/pull/4537#issuecomment-317268508) by `git commit --amend`, and your commit should contain an issue reference. To sum it up, do :
```
git commit --amend
``` 
and after the editor opens up, type in : 
```
Newcomers_Guide: Replace 'step 4' with 'step 3'

Closes https://github.com/coala/coala/issues/4509
```
You can refer to https://coala.io/commit for more information.

**Comment by jayvdb** [comment]
Issue was fixed by someone else who followed our guides.

**Pull request closed without merging**
