### PR TITLE
typo corrected

### PR DESCRIPTION
**Pull request by Stropek**
Incorrect article in Bear class description fixed.

Fixes https://github.com/coala/coala/issues/4520

### CODE REVIEW

**Comment by userzimmermann** [comment]
@Stropek But please change your commit message to match our guidelines. Should be in imperative form and starting uppercase. And a bit more verbose. And some location prefix also can't hurt ;) In this case something like:

`Bear: Fix typo in docstring`

**Comment by Stropek** [comment]
@userzimmermann is this fine now?

**Comment by Stropek** [comment]
Why when I squashed my commits a change by yash-nisar was added to my pull request? 
I used the command from https://api.coala.io/en/latest/Developers/Git_Basics.html:

$ git rebase -i master

**Comment by userzimmermann** [comment]
@Stropek Hmm... Somehow you also did a merge o.O 

Please try `rebase -i master` again and only keep the `Bear.py: Fix typo in docstring` commit

**Comment by Stropek** [comment]
@userzimmermann I think I've done it correctly now. Can you double check?

Thanks!

**Comment by userzimmermann** [comment]
@Stropek Oh oh! It's getting worse... You must get rid of all `typo corrected` and `Merge branch ...` and duplicate `Bear.py: Fix typo in docstring` commits. Can you paste the `rebase -i` menu here?

**Comment by Stropek** [comment]
@userzimmermann First of all, thanks for your help. I'd really like to figure out what I'm doing wrong here. Even though the change I made is super-tiny I would love to understand how the process works and looks like I'm not getting it frm the tutorial. 

I'm not sure what exactly you mean by `rebase -i` menu so I'll just list all steps that I'm doing and maybe you'll know what I'm doing incorrectly. 

`git remote -v`
```
origin  https://github.com/Stropek/coala.git (fetch)
origin  https://github.com/Stropek/coala.git (push)
upstream        https://github.com/coala/coala.git (fetch)
upstream        https://github.com/coala/coala.git (push)
```
`git status`
```
On branch replace-article
Your branch is up-to-date with 'origin/replace-article'.
nothing to commit, working tree clean
```
`git rebase -i upstream/master`
```
pick 55990c7 Bear.py: Fix typo in docstring
pick d527905 Bear.py: Fix typo in docstring
pick 042df3e Bear.py: Fix typo in docstring
pick 1c58381 Bear.py: Fix typo in docstring
pick d2264d5 typo corrected

# Rebase 2816dc6..5ff189c onto 2816dc6 (5 commands)
```

At this point I'm dropping first 3 'Fix typo in docstring' commits, picking the 4th one and squashing 'typo correct'.

What am I messing up here?

**Comment by userzimmermann** [comment]
@Stropek Ah! I see :) Don't squash! @troublemagnet This is just about one change in one commit

Basically all you actually had to do at the beginning was to `git commit --amend` your existing commit to just change the commit message and `git rebase master` afterwards. I don't know what you did that created the extra commits and merges. But what you can do now is only keeping `d2264d5 typo corrected`. And then you change the commit message, either during rebase process or with an additional `git commit --amend` afterwards

**Comment by Stropek** [comment]
@userzimmermann I did what you've written. Hopefully it's correct now.

btw. extra merges are there because each time I'm doing `rebase` I'm getting a prompt that I need to pull changes from my fork before I can push rebased version and this results in a merge.

**Comment by userzimmermann** [comment]
@Stropek Strange strange... ;) Aaah! Got it :D You just have to `push -f`orce to replace your existing remote branch commits! So update `master` again, rebase keeping only your first commit, rename it, and `push -f ...`

**Comment by Stropek** [comment]
@userzimmermann Hey man, sorry for the delay. I think I've finally got it right after taking a break from this for a bit. I didn't get earlier that I needed to skip `pull` all together and do `push -f` only. 

Hopefully it's fine now and I can move on to a _low_ issue now :P

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/4606/commits/4b65e1d0af8d9e224c5f675ae7250bd69bc1954e

**Comment by userzimmermann** [comment]
Hej @Stropek :) Teraz jest świetnie! ;) Great that you finally understood the process! But you need to rebase again, because our @rultor won't merge otherwise, as you can see below...

**Comment by userzimmermann** [comment]
@rultor merge

**Comment by userzimmermann** [comment]
@Stropek Oh! One little thing left :) Please also change your bottom line in the commit message to:

`Fixes https://github.com/coala/coala/issues/4520`

Just like in your PR summary! Currently you `Close https://github.com/coala/coala/pull/4606`, which is your PR itself :D

**Comment by Stropek** [comment]
@userzimmermann Sorry for long delay - I was on vacation and I've cut myself off from doing anything remotely related to work :) I've adjusted the commit message as you suggested. Does this mean that the last line of commit message is being used during merge process to do some actions automatically? If so, what exactly is automated?

**Comment by Stropek** [comment]
@rultor Can this be merged now?

**Comment by Stropek** [comment]
@rultor merge

**Comment by Stropek** [comment]
@rultor merge

**Comment by Stropek** [comment]
@userzimmermann Would you know why I'm getting this:
fatal: Not possible to fast-forward, aborting.
?

**Comment by Stropek** [comment]
@rultor merge

**Comment by Makman2** [comment]
@Stropek please don't merge your own PRs, only maintainers are allowed to do so.

**Comment by Makman2** [comment]
@rultor stop

**Comment by Makman2** [comment]
Also please use `Closes XXXX` instead of `Fixes XXXX` in your commit message, the referenced issue is not labeled with `bug` :+1:

**Comment by Makman2** [comment]
ack 7550e91

**Comment by Stropek** [comment]
@Makman2 So was the issue the fact that I used incorrect word in commit message (_fixes_ instead of _closes_)? Does it mean that rultor merges different types of tasks differently?

**Comment by Stropek** [comment]
@Makman2 Can I run rultor now?

**Comment by Makman2** [comment]
> @Makman2 So was the issue the fact that I used incorrect word in commit message (fixes instead of closes)? Does it mean that rultor merges different types of tasks differently?

No that has nothing to do with rultor, rultor merges always the same way. rultor failed because the CI checks weren't yet done. The "closes" vs. "fixes" will be used by us later for bug prediction.

**Comment by Makman2** [comment]
@rultor merge

**Comment by Makman2** [comment]
> @Makman2 Can I run rultor now?

Please only let maintainers do that :)

**Comment by Stropek** [comment]
@Makman2 Roger that.

Phew, that took much longer than I thought it would :P

**Pull request merged**
