### PR TITLE
Newcomers_Guide.rst: Mention smart questions

### PR DESCRIPTION
**Pull request by 44rdvark**
Add reference to "How To Ask Questions The Smart Way" guide.

Closes https://github.com/coala/coala/issues/4847

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

### CODE REVIEW

**Comment by newbazz** [comment]
@Makman2 ready for merge ;)

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala/pull/5052/commits/ea31d4f60c39fd00261791dfea3b31959a706de6

**Comment by yukiisbored** [comment]
@gitmate-bot Please merge

**Comment by yukiisbored** [comment]
@gitmate-bot ff

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
