### PR TITLE
ConsoleInteraction: Add break condition

### PR DESCRIPTION
**Pull request by firesans**
This fixes the handling of the loop break condition accordingly #5202

### CODE REVIEW

**Comment by sks444** [comment]
@firesans , you need to follow the [commit guidelines](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html) 
and squash your commits into one :)

**Comment by Naveenaidu** [comment]
As @sks444 said Add a head and a body to the commit. And the issue you are fixing should be reference by "Fixes <url>". Do change the commit head from ConsoleInteraction to ConsoleInteraction.py . Rest look good to me. ☺️

**Comment by Naveenaidu** [comment]
Just use git commit --amend. And do squash your commits.

**Comment by Naveenaidu** [comment]
@manankalra  Thanks! I'll be updating my comment now. :')

**Comment by manankalra** [comment]
@Naveenaidu No, you should not update comments if they have already been addressed. This can lead to misinterpretation of information to someone who is reading/reviewing them at a later stage.

**Comment by Naveenaidu** [comment]
@manankalra  Reverted back to the original comment. Sorry! Didn't know about that.

**Comment by harshhx17** [comment]
Instead of making a new commit, change the old commit....
Otherwise the bots will not accept the issue as your old commit still has the trailing whitespaces

**Comment by harshhx17** [comment]
You can see how to do that on this page: http://api.coala.io/en/latest/Developers/Git_Basics.html

**Comment by Makman2** [comment]
Closing due to inactivity.

**Pull request closed without merging**
