### PR TITLE
Added CI to Newcomers Guide 

### PR DESCRIPTION
**Pull request by Harshish**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Siddhartha1234** [comment]
Use imperative tense when you write a commit message  . Follow  http://coala.io/commit  . Use git commit --amend and force push :)

**Comment by Techievena** [comment]
@Harshish @Gourav2906 is already working on this issue. https://github.com/coala/coala/pull/3813 Next time you pick up an issue please make sure you get assigned to that issue so that we don't have multiple people working on the same issue.

**Comment by Gourav2906** [comment]
@Harshish  I am already working on this.

**Comment by Techievena** [comment]
@Harshish see the review not the comment. This has to be closed

**Comment by jayvdb** [comment]
Closing.  We have a newcomer processes, which requests that you join our gitter https://coala.io/chat and be assigned to a newcomer issue before submitting a PR for that issue.  Therefore, this issue belongs to @Gourav2906 .

@Harshish, you are more than welcome to follow the newcomer process again, especially joining us on gitter, and make sure you are assigned to your next issue.

**Pull request closed without merging**
