### PR TITLE
aspects/meta.py: Fixed typo error

### LINKED ISSUE #3865: aspects/meta.py: Typo error
Replace `int` -> `in` in `search for tastes int the sub-aspectclass`

difficulty/newcomer

### PR DESCRIPTION
**Pull request by GPhantom**
Fixes #3865 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by NiklasMM** [comment]
You need to rebase this branch such that only 87cedcb shows up in the PR

**Comment by GPhantom** [comment]
Thanks :+1:  @NiklasMM

**Comment by GPhantom** [comment]
Done :+1: @vijeth-aradhya

**Comment by NiklasMM** [comment]
Also put the full URL to the issue with the "Fixes" keyword into the commit message like so:

`Fixes https://github.com/coala/coala/pull/3888`

**Comment by adtac** [comment]
@GPhantom Your commit message is still not upto requirements. Using `Fixes` in the commit title isn't allowed. Please go through http://coala.io/commit and make sure every point is checked off.

I'll help you out here:

```
meta.py: Fix typo

<a sentence about the PR>

Fixes https://github.com/coala/coala/issues/3865
```

is a valid commit message.

Also, you need to rebase.

**Comment by GPhantom** [comment]
Done :+1: @adtac

**Comment by Techievena** [comment]
I think it should be `Closes`. Is fixing typo a bug fix?

**Comment by supergr35** [comment]
I agree with Techivana's message. Also, will need another rebase before merge.

**Comment by GPhantom** [comment]
Done :+1: @Techievena

**Comment by supergr35** [comment]
One last thing: the commit message should be in the imperative mood. Thus, `Replaced` ->`Replace` . After this and a rebase I believe it should be mergeable.

**Comment by GPhantom** [comment]
Changed it :+1: @supergr35

**Comment by supergr35** [comment]
I'm afraid this still needs a rebase. Are you rebasing like our documentation tells you to?

**Comment by GPhantom** [comment]
Why is rebase needed in this case? It is only one commit so the bots wouldn't complain. @supergr35

**Comment by supergr35** [comment]
See the thing is when we merge, if your branch is behind the coala master branch in terms of changes, it refuses to merge because fast-forwarding is not possible. Thus, you are required to rebase no matter how many commits you have, or where the change is :)

**Comment by GPhantom** [comment]
Rebase completed :+1: @supergr35

**Comment by supergr35** [comment]
ack 02c7c89

**Comment by NiklasMM** [comment]
Sorry @GPhantom you'll need to rebase again.

**Comment by NiklasMM** [comment]
reack 1a016a5

**Comment by NiklasMM** [comment]
@rultor merge

**Pull request merged**
