### PR TITLE
Writing_Good_Commits.rst: Fix grammar 

### PR DESCRIPTION
**Pull request by mk1299**
This fixes a grammatical error by changing the line
"At coala we are looking heavily at the maintainability of the code".
to
"At coala, we are looking heavily at the maintainability of the code."
Closes  coala#5927

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by mk1299** [comment]
@shashank-b I tried squashing the commits in my local fork using `git rebase -i HEAD~n` but for some reason it doesn't have history of my commits.Do you know any way of doing this from the website,I couldn't find anything on the internet.

**Comment by mk1299** [comment]
Hey @shashank-b! I squashed the commits and changed the commit message as described in the Newcomers' guide but the PR did not update.Would you suggest closing this one and opening another PR?I'm sorry for bothering you this much,it's my first oss contribution hence the struggle.

**Comment by shashank-b** [comment]
Hey @mk1299 
Try reading about force-push. That might be useful to you. I'd suggest you use that and don't create another PR since there are duplicate PRs for this issue already. While you're at it, I'd suggest that you amend the commit on your local branch to have a space between ':' and 'Fix' in the header.
And don't worry about bothering anyone here at coala :slightly_smiling_face:

**Comment by mk1299** [comment]
I used force push only but it did not update the PR,only my fork.
There already is a space between : and Fix,do you want me to add another one?

**Comment by shashank-b** [comment]
@mk1299, I guess you got confused between 2 different branches. You pushed your changes to `mk1299-patch-1` instead of `patch-1` (which is the actual branch from which this PR is created).

**Comment by mk1299** [comment]
@shashank-b Thanks a lot mate,that turned out to be the problem after all.Is it alright now?

**Comment by mk1299** [comment]
@li-boxuan Please review the changes.

**Comment by mk1299** [comment]
@shashank-b I have corrected it.Anything else?

**Comment by mk1299** [comment]
@li-boxuan Please review.

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack 2c942af

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
