### PR TITLE
gsoc: Merge Severity line output

### PR DESCRIPTION
**Pull request by Nosferatul**

### CODE REVIEW

**Comment by Nosferatul** [comment]
http://imgur.com/n17engK

**Comment by Nosferatul** [comment]
@jayvdb please take a look

**Comment by Nosferatul** [comment]
or maybe http://imgur.com/a/ouYw4

**Comment by yukiisbored** [comment]
can you remove the useless empty line after the message and before the message?

**Comment by Adrianzatreanu** [comment]
to be honest i like this one: http://imgur.com/n17engK

**Comment by Adrianzatreanu** [comment]
also the commit shortlog doesnt make much sense tbh

**Comment by Nosferatul** [comment]
this is how it looks http://imgur.com/a/p8BtZ

**Comment by Adrianzatreanu** [comment]
me likes this

**Comment by Adrianzatreanu** [comment]
ack 03cfa90

**Comment by Adrianzatreanu** [comment]
ack 5caebea

**Comment by Nosferatul** [comment]
reack 2bd16a5 360a624

**Comment by Nosferatul** [comment]
@rultor merge

**Pull request merged**
