### PR TITLE
.travis.yml: Add csslint

### PR DESCRIPTION
**Pull request by satwikkansal**
Add commands to install csslint required
by the CSSLint bear for the `css` section
of the `.coafile`

Fixes https://github.com/coala/coala/issues/3360

### Checklist

- [ ] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [ ] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [ ] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [ ] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [ ] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [ ] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

**After you submit your pull request, DO NOT click the 'Update Branch' button**

### CODE REVIEW

**Comment by satwikkansal** [comment]
I'm not able to figure out what is causing this error 
```
pytest.py: error: unrecognized arguments: --cov --cov-fail-under=100

  inifile: /home/travis/build/coala/coala/setup.cfg

  rootdir: /home/travis/build/coala/coala
```
in the travis builds

**Comment by vijeth-aradhya** [comment]
ack 49bdb745b91b05eadfa1d9a2dac3b68d18a8294a

**Comment by jayvdb** [comment]
needs rebase

**Comment by satwikkansal** [comment]
@jayvdb Rebased. It's strange that Travis builds are failing again after the Rebase and there's no visible error in the logs.

**Comment by sims1253** [comment]
@rultor merge

**Comment by sims1253** [comment]
travis is acting up and we are ignoring it atm

**Comment by jayvdb** [comment]
sorry, needs a rebase again

**Comment by sils** [comment]
I cherry picked this to https://github.com/coala/coala/pull/3706 so we can merge it in one go without so much rebase. You don't need to do anything and it's taken care of that this gets merged, thanks for your contribution!

**Pull request closed without merging**
