### PR TITLE
VERSION: Bump to 0.11 development

### PR DESCRIPTION
**Pull request by jayvdb**
Related to https://github.com/coala/coala/issues/3786

### CODE REVIEW

**Comment by jayvdb** [comment]
fwiw, I believe this is necessary before it is possible to easily fix our CI build problems at the moment, as coala-bears needs a new coala, and pip will never get the dev version until it has a higher number than the released version.

**Comment by Mixih** [comment]
on it

**Comment by Mixih** [comment]
ack dae6d53

**Comment by Mixih** [comment]
@rultor merge

**Comment by jayvdb** [comment]
reack aad7eb4

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
