### PR TITLE
Git_Basics.rst: Maximum line length of commit body change to 72

### LINKED ISSUE #5777: Git_Basics.rst: Correct maximum line length of commit body
Right now, it is mentioning 50 characters length for commit body which should be 72.

https://github.com/coala/coala/blob/master/docs/Developers/Git_Basics.rst#adding-the-files-and-commiting

### PR DESCRIPTION
**Pull request by bhawesh96**
Character length of commit body is changed from 50 to 72.

Closes #5777

@PrajwalM2212

### CODE REVIEW

**Comment by bhawesh96** [comment]
@rishabhgarg25699 Thanks for providing me with this information. I will see to it that I abide by the guidelines from next time.

**Comment by manankalra** [comment]
@bhawesh96 I think the commit body isn't needed here as it's redundant. Feel free to remove it. You can alter the shortlog to _Change commit body character limit from 50 to 72_ if it's under the max limit.

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5783/commits/1236eb0d9b6d18fbc80c2417d12076da4b6f4ae8

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
