### PR TITLE
ConfigurationGathering.py

### PR DESCRIPTION
**Pull request by ankit01ojha**
Fixes https://github.com/coala/coala/issues/3395

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [x] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by sils** [comment]
Hi,

it seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading <http://coala.io/commit>!

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by sils** [comment]
@Udayan12167 is this going to be a problem for you?

**Comment by sils** [comment]
please take a quick look

**Comment by ankit01ojha** [comment]
@yash-nisar I first had a commit message ConfigurationGathering.py:Change variable name default_sections to base_section but it exceeded the limit so I asked on gitter and after the suggestions I have wrote this commit message as the name of my file is quite long (26 characters) :)

**Comment by fneu** [comment]
@ankit01ojha I'd strongly favor a description that at least somehow describes the change you are actually making. Please consider a shortlog like `ConfigurationGathering: rename default_section`, which should fit the 50 char requirement. Since I have not been part fo the Gitter conversation I leave this up to you, though.

In any way please describe the change (rename) at least in the commit message body. It should be obvious what changed in your commit by looking at the commit message, a link to the issue is great but not enough.

The change itself looks fine though. Thank you for contributing :)

**Comment by fneu** [comment]
@ankit01ojha There is also #3438 still open by you and it appears that both PRs address the same issue.

Are you aware that you can update a PR by (force) pushing to the respective branch?

In any way please close one of them (probably #3438)

**Comment by ankit01ojha** [comment]
@fneu I wrote the commit as you told me but its not passing the tests but earlier it passed 5 tests. Could you please tell me why this happened? :)

**Comment by fneu** [comment]
travis could apparently not install clang and coala on circleci failed because csslint was not installed on the test environment. I have no idea why but it doesn't sound like it's your fault ¯\\_(ツ)\_/¯

@yash-nisar is right about starting the shortlog with a capital letter and please use the commit body he proposed :)

**Comment by ankit01ojha** [comment]
@sils can it be merged now?

**Comment by yash-nisar** [comment]
As I mentioned earlier, a commit body would be preferred describing the change. In this case something similar to `The variable name default_sections has been changed to base_sections` would help us to determine the changes that you have performed. Everything else seems perfect ! :smile:

**Comment by ankit01ojha** [comment]
@yash-nisar Is this ok now ?

**Comment by yash-nisar** [comment]
Looks good to me. :smile:

**Comment by ankit01ojha** [comment]
@yash-nisar so,  can it be merged now :)

**Comment by yash-nisar** [comment]
unack 471acb5db8190b9dc8587d4a8c655db2071d238b

**Comment by ankit01ojha** [comment]
@yash-nisar Now I think its even the branch, so , please have a look :)

**Comment by yash-nisar** [comment]
One of our maintainers will further review your code and if everything goes well, your PR may get merged. We have a lot of PRs open ATM, so it is difficult for us to merge PRs instantly. :)

**Comment by ankit01ojha** [comment]
@yash-nisar  OK, Thanks :)

**Comment by yash-nisar** [comment]
As @sils mentioned, 
> don't bother with rebasing any PRs, we'll batch merge a number of acked PRs because it's simpler with those masses of things

**Comment by harshit890** [comment]
u can write ur shortlog as ConfigurationGathering.py: Rename default_sections

**Comment by ankit01ojha** [comment]
@harshit890 I tried that one as you said but many of the tests started failing, don't know why?
IMO its fine :)

**Comment by harshit890** [comment]
was ur shortlog exact same...as long as the shortlog is less or equal to 50 alphabets the commit error don't occur

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3533/commits/8b52b41c34ff08cf1fa48388017dee97c8e335fe

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :) You've done your first step to become a coala developer.

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

We would really appreciate it if you could help us with

- [telling us about your experience](http://coala.io/newform)
- [some code reviews](http://coala.io/reviewing) for other newcomers
- fixing at least [a difficulty/low issue](http://coala.io/low)
- fill our [usability survey](http://coala.io/usability)

If you've done those and tell us about it so we can promote you to a coala developer!

We're all volunteers and we're currently struggling to keep this up. Helping all those newcomers is a lot of work and we do need your help so we can continue this for others!

**Pull request merged**
