### PR TITLE
SpacingHelper.py: Fix Typo

### PR DESCRIPTION
**Pull request by iBvishal**
Closes the typo and changes it
from 'isnt' => 'isn't'

Closes https://github.com/coala/coala/issues/5962

### CODE REVIEW

**Comment by anubhawbhalotia** [comment]
LGTM. A slight improvement can be done in the commit message. You should write 'Closes' instead of 'Fixes'. :)

**Comment by arnav-mandal1234** [comment]
From next time make sure to get yourself assigned an issue before submitting a PR. I think maintainers won't approve this as you have not been assigned to it.

**Comment by gaocegege** [comment]
@iBvishal Could you please fix the commit message?

**Comment by iBvishal** [comment]
yes, I'll fix the commit message and make a pull request.

**Comment by KVGarg** [comment]
@iBvishal Please don't close the PR u-necessarily. Requesting you to please re-open the PR and make the changes in this PR. You can use `git commit --amend` to add changes in your last commit which will make a clean PR.

**Pull request closed without merging**
