### PR TITLE
Sils/chep

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by sils** [comment]
1454794c Move requirements to dependency_management
3b7932f5 SpaceConsistencyTestBear.py: Edit param options
reack

**Comment by sils** [comment]
@rultor merge

**Comment by Mixih** [comment]
Merge failed and rebase needed

**Comment by sils** [comment]
@Mixih could you not mark PRs WIP that just need a rebase? I (and others should do that too) regularly look after the approved PRs and cherry pick them into one.

**Comment by sils** [comment]
29c28590 Move requirements to dependency_management
3ee7bf2e SpaceConsistencyTestBear.py: Edit param options
reack

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
crap :/

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by Mixih** [comment]
needs merge still

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3330/commits/4055dc1e36e852df28e97c05344fe2f77f267558

**Comment by sils** [comment]
reack https://github.com/coala/coala/pull/3330/commits/a3124fc2d98ee6728d7bea88730ea63e8d97121e

**Comment by Mixih** [comment]
moved to https://github.com/coala/coala/pull/3420

**Pull request closed without merging**
