### PR TITLE
ConsoleInteraction: Remove format_str (deprecated)

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by Mixih** [comment]
Blocked because: official plugins need fixing

**Comment by sils** [comment]
Marking WIP in the meantime.

**Comment by sils** [comment]
@RohanVB are all plugins fixed yet?

**Comment by RohanVB** [comment]
Only official editor still using `format_str` is coala-vim now I suppose.

**Comment by Mixih** [comment]
ack  	0a188c3

**Comment by Mixih** [comment]
ack 0a188c3

**Comment by Mixih** [comment]
@rultor merge

**Pull request merged**
