### PR TITLE
requirements.txt: Upgrade dependency_management

### PR DESCRIPTION
**Pull request by jayvdb**
Require dependency_management 0.3.1,
allowing Maven and Distribution-based requirements.

### CODE REVIEW

**Comment by nemaniarjun** [comment]
ack 6def4a2

**Comment by Mixih** [comment]
reack dcd92f4

**Comment by Mixih** [comment]
@rultor merge

**Comment by Mixih** [comment]
ah, it's out of sync again.

**Comment by jayvdb** [comment]
This is why we need https://gitlab.com/coala/cobot/issues/31

**Comment by jayvdb** [comment]
reack 533e3f8

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
