### PR TITLE
CachingUtilities.py: Remove unused local variable

### PR DESCRIPTION
**Pull request by HemabhKamboj**
Closes https://github.com/coala/coala/issues/5642

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by HemabhKamboj** [comment]
ok, looking the code again, can't capture that a removal of a variable is failing the test.

**Comment by jayvdb** [comment]
@HemabhKamboj , please read the errors by gitmate here on your PR.
Please read and follow https://coala.io/git closely.

**Comment by RaiVaibhav** [comment]
The only problem is  you didn't `squash commit` and commit head, test is not failing because of your changes.

**Comment by ksdme** [comment]
You can also find out squashing guide at https://api.coala.io/en/latest/Developers/Git_Basics.html#rebasing.

**Comment by MacBox7** [comment]
@HemabhKamboj please reply and fix this soon otherwise you will be unassigned. For any help ask on coala group.

**Comment by HemabhKamboj** [comment]
@MacBox7 will do it by today

**Comment by HemabhKamboj** [comment]
image

I followed the instructions of @MacBox7 as he said on Gitter and fetched from coala/master. Now, squashing all new changes to my initial commit 9cae7e80 is saying 'Cannot squash without previous commit'. Should I squash the other commits now?

**Comment by ksdme** [comment]
Please reword your commit message.

**Comment by ksdme** [comment]
Read the commit guidelines at coala.io/commits, you are missing a proper shortlog.

**Comment by ksdme** [comment]
A couple of issues with your commit message:

- `This fixes the typo` That was not a typo.
- `lines 48 and 89` No point in adding line numbers in commit message.
- Missing period in commit body.
- `Fixes`, this was not a but, you should use `Closes`.

**Comment by MacBox7** [comment]
You are good to go. Just some minor issue as @ksdme  pointed out.
- Commit body is not needed remove it.
- Fixes => Closes
- Removes => Remove

I hope you now know that you can use =>
`git commit --amend`
`<Do the changes>`
`git push -f origin Hemabh`
to the changes.

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5653/commits/f904a97c2b7468b8d8e8d85024acd4567d0e4275

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
