### PR TITLE
Fix may28 breakages

### PR DESCRIPTION
**Pull request by jayvdb**
Workarounds for https://github.com/coala/coala/issues/4277, https://github.com/coala/coala/issues/4280 and https://github.com/coala/coala/issues/4282 .

One of the commits can be removed if https://github.com/Kuniwak/vint/pull/217 is merged.

Another is https://github.com/sphinx-doc/sphinx/issues/3814

### CODE REVIEW

**Comment by meetmangukiya** [comment]
Wow, such green

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala/pull/4283/commits/6785f4aff68503e1ccbb16420fe614a23e78f6f9

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala/pull/4283/commits/638bff9cd85bedb7e2e8c6184b41f547eca4f97c

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala/pull/4283/commits/b793d136c707bfd3832a189d36d66e946afc40d9

**Comment by yukiisbored** [comment]
@rultor Please merge xoxo

**Pull request merged**
