### PR TITLE
Supersede aspects with aspectclasses

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by userzimmermann** [comment]
ack ab38e70b9e4d49cba940e099261c72e29c9360c2

**Comment by sils** [comment]
unack ab38e70

**Comment by userzimmermann** [comment]
unack ab38e70b9e4d49cba940e099261c72e29c9360c2

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3040/commits/96e20031ad311e8a47b158ce3dfce648668f8cdd

**Comment by sils** [comment]
reack 91d226e

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/3040/commits/9a7890d1dcab2da8ee592bca21cf7fe94e7b3bc7

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/3040/commits/91d226eb0d41726c69786562b4474c17bd8ecc7c

**Comment by userzimmermann** [comment]
@rultor merge

**Pull request merged**
