### PR TITLE
Writing_Good_Commits.rst: Fix typo

### PR DESCRIPTION
**Pull request by Anonymous26**
This fixes the typo and changes
it from Fixes --> Closes.

Closes https://github.com/coala/coala/issues/5195

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Naveenaidu** [comment]
Use git commit --amend. It would help :smile:

**Comment by monsij** [comment]
@Naveenaidu I don't think a commit body is necessary as because it's a very straightforward change :smile:

**Comment by Naveenaidu** [comment]
@monsij Shouldn't the commit mention which issue it closes 😅

**Comment by Anonymous26** [comment]
In the comment it is mentioned that is closes #5195

**Comment by Naveenaidu** [comment]
@Anonymous26 You need to mention which issue it closes inside the commit body also. 
The commit message should look like:- 
```
This fixes the typo and changes
 Fixes --> Closes.

Closes https://github.com/coala/coala/issues/5195
```
:smile:

**Comment by jayvdb** [comment]
irony: a commit to fix commit messages has an invalid commit message.

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5204/commits/a29d9c9ba07dc7893b822caa592d50c09e80e02f

**Comment by jayvdb** [comment]
ack a29d9c9

**Comment by Anonymous26** [comment]
Is everything okay now ?

**Comment by jayvdb** [comment]
yup; all good. however the bot is being lazy.

**Comment by jayvdb** [comment]
ack a29d9c9

**Comment by jayvdb** [comment]
ack a29d9c9

**Comment by jayvdb** [comment]
hmm.  it isnt our lucky day.  I'll try to merge it again tomorrow.

**Comment by Anonymous26** [comment]
okay no prob.

**Comment by nkprince007** [comment]
ack https://github.com/coala/coala/commit/a29d9c9ba07dc7893b822caa592d50c09e80e02f

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
