### PR TITLE
WIP Newcomers_Guide.rst: Correct grammatical errors

### PR DESCRIPTION
**Pull request by AlexandruGhimisi**
Closes https://github.com/coala/coala/issues/3619

### Checklist

- [ ] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [ ] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [ ] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [ ] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [ ] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [ ] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

**After you submit your pull request, DO NOT click the 'Update Branch' button**

### CODE REVIEW

**Comment by RohanVB** [comment]
ack 7aebd0eeb046a1c865d8d93a79d6b1e7120e1776

**Comment by supergr35** [comment]
Marking WIP because tests are failing.

**Comment by gaocegege** [comment]
Hi, maybe you could reset these four commits to one because there is only one file changed 😃

**Comment by gaocegege** [comment]
Hi, you could ask for help in https://gitter.im/coala/coala 😃

**Comment by gaocegege** [comment]
I think you could pull this branch to local, and use `git reset HEAD~4` to reset all of your commits, then add and commit again, and `git push -f` to force push finally.

**Comment by RohanVB** [comment]
@AlexandruGhimisi still working on this? Ping us on https://gitter.im/coala/coala if you need any help.

**Comment by AlexandruGhimisi** [comment]
Thanks everyone for reviewing this. I did something wrong and I had no option but to start from the beginning. I did another Pull Request here: https://github.com/coala/coala/pull/3891 . I will close this one. Sorry for the inconvenience.

**Pull request closed without merging**
