### PR TITLE
OpenEditorAction.py: Add Brackets editor

### PR DESCRIPTION
**Pull request by XLAR-8**
Addition of Brackets Code editor to
the list of editors known to coala .

Closes <https://github.com/coala/coala/issues/5829>

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by XLAR-8** [comment]
@jayvdb  please review this request .

**Comment by XLAR-8** [comment]
@jayvdb I have rectified the issue you reopened #5848
<https://github.com/coala/coala/pull/5848>. please review it.

**Comment by XLAR-8** [comment]
@srivama  previously this commit got passed but it showed error that i should not make new pull but work on this one only.

**Comment by srivama** [comment]
No worries! Look the bot says that your commit head has more than 50 characters, which is the max length limit for the commit head. Try changing your commit head to something like `OpenEditorAction.py: Add Brackets editor`, and in the commit body you can mention the link of the issue it closes, simple :smile: 
Just keep in mind, you don't have to do a new commit, you just need to amend the earlier one. You can use `commit -a --amend` and edit your previous commit message. Try it out, then I'll walk you through squashing your commits :wink:

**Comment by srivama** [comment]
Go through `coala.io/git` and read about squashing the commits. As John pointed, you have two commits in your PR, and they need to be squashed into one.

**Comment by XLAR-8** [comment]
@stellargo ,( continuous-integration/appveyor/pr — AppVeyor build failed) this is the error I am getting .
Is it because my commit message is not in properly written? I think there is some other reason .

**Comment by stellargo** [comment]
Read the logs, it isn't a commit message error. I would recommend first anyway correct the commit message and run CI again to see if problem persists :)

**Comment by XLAR-8** [comment]
@shikharvaish28  please see if it is correct .
i read How To Write a Good Commit Message guide and make out this from it.

**Comment by srivama** [comment]
@XLAR-8 Did you forget to push the changes? Can't see any new commit after my review

**Comment by shikharvaish28** [comment]
@XLAR-8 You've actually forgot to push the changes.

**Comment by shikharvaish28** [comment]
> @srivama there is no need to push anymore as problem is only with my commit message which can be edited any time without push.

Can you please tell me how you changed the commit message? It will help us to identify where you're stuck 😄

**Comment by srivama** [comment]
Yes, you'll have to amend your commit message and push again. I've already mentioned the commit changes above :wink: If your'e still confused or have any queries, we can take it on the gitter im rather than creating a mess here :)

**Comment by XLAR-8** [comment]
@shikharvaish28 , see there is option at rigth top corner to edit commit anytime.(click on those 3 dots)

**Comment by stellargo** [comment]
So it seems you may have changed your commit message locally but you have to push the changes again. (Hint: -f option will be useful)

**Comment by shikharvaish28** [comment]
@XLAR-8 You've misinterpreted us. You have changed the PR message instead of commit message.
screenshot 2018-10-24 at 9 56 16 pm
Just read once [this article](https://api.coala.io/en/latest/Developers/Git_Basics.html#adding-the-files-and-commiting) to understand what is commit message and commit description
The above image is of the stuff we want you to change. If you know how to change it, go ahead but, in case you don't, just feel free to ask on the gitter channel. We'll be more than happy to help you 😄

**Comment by jayvdb** [comment]
@XLAR-8 as this is the sixth PR, and still poor progress, I am closing this one and unassigning you from the issue.  I recommend you do some more git study courses outside of coala, as our resources and mentoring isnt working.

**Comment by XLAR-8** [comment]
@jayvdb  i am almost there i understood thngs i think i can complete this task . can i be reassigned to this again

**Comment by jayvdb** [comment]
No.  Sorry.  Hopefully this process has helped you get an understanding of the things you need to learn in order to participate in an open source org according to their guidelines.  Please come back after do a bit more practise outside of coala.  And remember, if you join a different org, their guidelines will be different, so please take the time to read their guidelines carefully.

**Pull request closed without merging**
