### PR TITLE
tests/aspects: Change the position of end braces

### LINKED ISSUE #3931: tests/aspects: Closing braces must be in same line as the last line of block/condition
There are instances of 
```
if (
    condition
   ):
```
whereas coala always follows this codestyle
```
if (
    condition):
```

### PR DESCRIPTION
**Pull request by RJ722**
Move closing braces to the the same line as the end of
block/condition, as is the general codestyle of coala

Closes #3931

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by RJ722** [comment]
Did it!
Thanks @Techievena

**Comment by Techievena** [comment]
You haven't pushed yet

**Comment by RJ722** [comment]
I am sorry, I changed it in the PR message, silly of me! :stuck_out_tongue_winking_eye:

**Comment by RJ722** [comment]
> Remove the : after Closes in the commit message

Should we file an issue for auto-checking the `:` in commit messages.?

**Comment by NiklasMM** [comment]
> Should we file an issue for auto-checking the : in commit messages.?

Could be worth a discussion, yes.

Btw: You still haven't pushed :)

**Comment by supergr35** [comment]
ack ab572e7

**Comment by RJ722** [comment]
@rultor merge

**Comment by Techievena** [comment]
@RJ722 I don't think you can merge. Moreover you haven't rebased.

**Comment by RJ722** [comment]
Did rebasing, Thanks @Techievena

**Comment by RohanVB** [comment]
ack e1adbfb1ff396af43d53a931b0791933a4f2974c

**Comment by RJ722** [comment]
>Could be worth a discussion, yes.

@NiklasMM please have a look at #4007

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
