### PR TITLE
docs/conf.py: Generate from local source

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by Makman2** [comment]
reack 3a734aa

**Comment by jayvdb** [comment]
unack 37156f5
unack 3a734aa

**Comment by jayvdb** [comment]
You "reack 3a734aa" but I dont see someone else ack'ing that commit here.  Was it done somewhere else?

Is there an issue raised about this CI problem?

**Comment by Makman2** [comment]
Yeah the reacked commit comes from here: https://github.com/coala/coala/pull/3711

And no issue yet, shall I create one and link to it?

**Comment by Makman2** [comment]
removing the doctest-fix commit 37156f5, definitely obsoleted by the latest master.

**Comment by jayvdb** [comment]
Yes, please create an issue.  The underlying problem is that a second copy of coala is installed, which is a build time perf hit, and that should be fixed, not worked around.

**Comment by Makman2** [comment]
We do install two versions in CI? :O

Still this is no workaround, this allows to install the docs from the repo, not from the installed packages. Creating an issue for both^^

**Comment by jayvdb** [comment]
The commit message should at least start with ` docs/conf.py: ...` as it affects any use of sphinx, not just invocation via `setup.py docs`

**Comment by jayvdb** [comment]
ack 9daff0e

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
