### PR TITLE
package.json: Fix indentation

### PR DESCRIPTION
**Pull request by rasyidf**
package.json: Fix indentation

fix indentation by removing leading space

Fix https://github.com/coala/coala/issues/4056

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
```
Note
It is important that you do not make your changes on the master branch. To start working on an issue, you first need to create a new branch where you will work.

::
$ git checkout -b <branchname>

```
You can go through documentations for help. http://api.coala.io/en/latest/Developers/Newcomers_Guide.html

**Comment by prachi1210** [comment]
@rasyidf You can edit your commit body to this 
```
Fixes indentation by removing leading whitespace 
Closes <issue_link>
```

**Comment by JohnMoutafis** [comment]
ack 384461c

**Comment by JohnMoutafis** [comment]
needs rebase @rasyidf

**Comment by rasyidf** [comment]
what does 'need rebase mean?'

**Comment by JohnMoutafis** [comment]
@rasyidf Have a look here and follow the instruction http://api.coala.io/en/latest/Developers/Git_Basics.html#rebasing :smile:

**Comment by jayvdb** [comment]
While the change is approved, the rebase seems to be a problem.

**Comment by jayvdb** [comment]
Unassigning due to inactivity

**Pull request closed without merging**
