### PR TITLE
Constants.py: Add more true/false strings

### PR DESCRIPTION
**Pull request by erickzhao**
There are now more valid strings for 'true' and 'false'.

Add true strings: 'okay', 'ok', 'okey-dokey', 'yea', 'ya', 'ye',
'yessir', 'tru', 'uh-huh', 'yep', 'alright', 'alrighty', 'hell yeah',
'affirmative', 'certainly', 'definitely', 'absolutely', 'roger',
'righto', 'ja', 'da', 'si', 'oui', 'amen', 'totally', '10-4'.

Add false strings: 'nix', 'nop', 'nay', 'uh-uh', 'hell no'
'fat chance', 'not a chance in hell', 'not in a million years'
'out of the question', 'no siree', 'no way', 'nein', 'njet', 'nee'
'non', 'hakuna'.

Closes https://github.com/coala/coala/issues/1969

PTAL and maybe suggest more constants or veto some off?

### CODE REVIEW

**Comment by Asnelchristian** [comment]
This is good :+1:

**Comment by Asnelchristian** [comment]
use present tense in your commit body,

**Comment by sils** [comment]
+1 for the strings :) Love it!

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by erickzhao** [comment]
@Asnelchristian it's been changed!

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/2865/commits/728b7b02da8ca8f91b91c67784872244c0820a77

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
