### PR TITLE
Writing_Linter_Bears.rst: Fix typo

### PR DESCRIPTION
**Pull request by Pradhvan**
Fix typo in Writing_Linter_Bears.rst

Closes https://github.com/coala/coala/issues/5236

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Pradhvan** [comment]
@alphadose Hi, sorry for closing the last PR, https://github.com/coala/coala/pull/5228 and opening a new PR, https://github.com/coala/coala/pull/5229. I know it's a bad practice won't happen again :-)

**Comment by Pradhvan** [comment]
@sangamcse did the changes what you requested :smile:

**Comment by Makman2** [comment]
I migrated the issue to this repo as this is where you modified files in. Please reference https://github.com/coala/coala/issues/5236 instead :)

**Comment by Makman2** [comment]
Otherwise looks good.

**Comment by Makman2** [comment]
unack d191518bfaf30f0d78b0fd82c045249041160d4b

**Comment by Makman2** [comment]
You don't have to mention inside the commit body that this was migrated from somewhere else :)

**Comment by Pradhvan** [comment]
@Makman2 I did the changes you requested, please review :smile:

**Comment by Pradhvan** [comment]
@sangamcse I did another PR but still the Travis build is failing

**Comment by Pradhvan** [comment]
Can you review it @Makman2 @sangamcse  :smile:

**Comment by Vedarth** [comment]
@Pradhvan whenever you use `git commit --amend` use `git push -f` to force push it.

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
