### PR TITLE
Formatting: Add tastes to `FileLength` aspect

### PR DESCRIPTION
**Pull request by pareksha**
This adds `min_file_length` and `include_blank_lines`
as tastes to `FileLength` aspect.

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jschwarzwalder** [comment]
The description of minimum line length is not clear.

In some languages will it always return 1 since it is  possible to combine multiple lines all into one line.

For example what would the min line length be of this code sample?

```javascript 
function fizzBuzz()
{ 	
//for each number between 1 &100
for(var i=1;i<=100;i++)
{
   //print Fizz if divisible by 3
 	 	if(i%3 === 0)
  {
 			 print('Fizz'); 	
  	}
   //print Buzz if divisible by 5
 		if(i%5 === 0)
  {
 		  print('Buzz');
 		}
   // otherwise print the number
 		if(i%3 !== 0 && i%5 !== 0)
  {
 			 print(i);
 		}
 	}
 }

**Comment by pareksha** [comment]
@jschwarzwalder you are exactly on point. This is the thing me and John have been debating on, all this time. Most probably, implementation of line-counting algorithms will be required to correctly predict the complexity of the code and accordingly show the number of lines. 

I had proposed `min_line_length` and `include_blank_lines` tastes as part of the `FileLength` aspect considering the current design of the bear (`LineCountBear` https://github.com/coala/coala-bears/blob/master/bears/general/LineCountBear.py) and it feels now that the bear itself needs a redesign on this plus supporting aspects on top of it.

I think you should see https://github.com/coala/cEPs/pull/148#discussion_r191038337 and furthermore https://github.com/coala/cEPs/pull/148#discussion_r192719097 to know more.

Lay your opinions too on this. 
And IMO this PR needs to be closed.

**Comment by pareksha** [comment]
Yes, `min_file_length` is compatible with the present usability of the bear and so, it is ok for now. I also agree that `include_blank_lines` is sort of problematic for now. Once the bear is migrated, we can think of stretching its functionality.

I have removed `include_blank_lines`. Please review :smiley:

**Comment by jayvdb** [comment]
@pareksha , please remove "This is part of GSoC 2018 project." (or any other reference to GSoC) from commit message, and create issues for your PRs, and using them in your commit messages.

That information is not relevant to the reader of the commit.

Your issues should refer to the cEP PR, or to the cEP once it is merged.

**Comment by jschwarzwalder** [comment]
If the only use case currently is to detect if the file length is 0, then why not make a taste for is_empty?

I would still have many questions about what `min_file_length` means. If we include it, it should qualify what would be counted. 

If the `min_file_length` ignores **comments** and **blank lines** that can be helpful to know how many actual lines of code exist, but without both those qualifiers It might be too ambiguous for developers to use. 

Does it minify the code? Does it simply count the current number of existing lines? Does it give suggestions for potential ways to reduce the number of lines with things the ternary operations?

**Comment by jayvdb** [comment]
Python has a requirement of `__init__.py` files, and these files are often empty. c.f. https://github.com/coala/coala/issues/2821

A min length of 1 will break coala repos, but we could fix that by adding a module docstring to every empty `__init__.py`.  c.f. https://github.com/coala/coala/issues/5359

**Comment by jayvdb** [comment]
`max_file_length` defines a rule for a hard *physical line* count maximum.

The `LineCountBear` would implement this taste by detecting files which exceed it, and producing an *error*.  That bear is a detection bear, not a fixing bear.

We do not have any bear which attempts to fix files which exceed a maximum line count.  That would be difficult.

We do not have any bear which attempts to fix files which have insufficient line count.  However this is more feasible to implement.  We could have a bear which automatically fixed a *minimum* line count **for Python**, by automatically adding a dummy docstring.  It would also be possible to fix it for any scripting language by adding a 'hashbang', but that would be dumb as the otherwise empty file probably isn't runnable.

**Comment by jayvdb** [comment]
Also please investigate the `suggested_values`.  What is it used for?  Why are you using this specific value for it.  It is not intuitive.

**Comment by pareksha** [comment]
`suggested_values` are more or less used to suggest values (not all values that the user can put, but what the user should put to get the desirable/better results) as I see here https://github.com/coala/coala/blob/master/coalib/bearlib/aspects/Formatting.py#L253 and at many other places too. What I meant here by `(1,)` was that the values can be 1 or any other `int` but now I am also feeling that there should be more than one suggested value (and not just the default value). So, I think `suggested_values` in both `min_file_length` and `max_file_length` need to be changed to have more integers.  

How about `(499, 999, 4999, 9999,)` in `max_file_length`  
and `(1, 50, 100,)` in `min_file_length` as suggested_values?

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5475/commits/bd23043f0242966d6d1c38753572fbbff11cf57d

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
