### PR TITLE
typo corrected

### PR DESCRIPTION
**Pull request by Stropek**
Bear.py: Fix typo entrypoint

This entrypoint is just a simple fix for a typo in documentation

Closes https://github.com/coala/coala/issues/4520

### CODE REVIEW

**Comment by gureks** [comment]
Needs rebasing. See [this](http://api.coala.io/en/latest/Developers/Git_Basics.html#rebasing)

**Comment by Stropek** [comment]
Hey guys,
I thought that doing [rebase ](http://api.coala.io/en/latest/Developers/Git_Basics.html#rebasing) would sync changes done in the meantime on master to my branch leaving only my small change in this PR, but it seems that now all the changes done in the meantime to master are part of it as well. 
Should I have done something else than rebasing?

**Comment by Nosferatul** [comment]
You added some commits that aren't yours, please remove them. You didn't rebase  properly, check http://api.coala.io/en/latest/Developers/Git_Basics.html for more details :smile:

**Comment by Stropek** [comment]
Hmm... I was sure I followed those instructions step by step. Must have done something wrong I suppose. I'll redo everything once more.

**Comment by Makman2** [comment]
If you need some specific help, you can also drop by at the [gitter channel](https://gitter.im/coala/coala), that is usually easier than discussing it in this PR thread here ;)

**Comment by Stropek** [comment]
That's a good advice, thanks!

**Pull request closed without merging**
