### PR TITLE
.editorconfig: Correct typo

### PR DESCRIPTION
**Pull request by monsij**
This corrects the typo error and changes it from fies --> files

Closes https://github.com/coala/coala/issues/5108

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

-  [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
-  [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by ishanSrt** [comment]
Full stop expected in commit body

**Comment by Makman2** [comment]
gitmate-bot accidentally predicted the issue as a bug, but such typos in documentation (and especially in code-comments) aren't bugs from coala's standpoint and I've removed the `bug` label from the issue. Could you please change `Fixes` to `Closes`? ;)

**Comment by Makman2** [comment]
unack 20a12a95ccff2cb58bb88689632c5adaebe57721

**Comment by monsij** [comment]
May I close this PR as I had accidentally made a commit with improper base?

**Comment by kriti21** [comment]
@monsij you can still remove the unwanted commits from here and rebase again.

**Comment by sangamcse** [comment]
Why did you close it @monsij? You should do whatever changes you want in the same branch and re-push it.

**Comment by monsij** [comment]
When I reverted the commits,it got closed accidentally

**Comment by sangamcse** [comment]
No problem. After required changes are done, re-push it from your `Update` branch.

**Pull request closed without merging**
