### PR TITLE
coalib/bearlib/aspects/__init__.py: Fix doc string syntax

### LINKED ISSUE #3329: Wrong doc string syntax in coalib.bearlib.aspects.Root
The doc string of the `Root` aspectclass has a formatting issue at https://github.com/coala/coala/blob/master/coalib/bearlib/aspects/__init__.py#L61

You can see the wrongly rendered result at https://api.coala.io/en/latest/coalib.bearlib.aspects.html#module-coalib.bearlib.aspects

### PR DESCRIPTION
**Pull request by gRSsomani**
This ensures the correct formatting.

Fixes #3329

### CODE REVIEW

**Comment by RohanVB** [comment]
@gRSsomani I noticed you pushed your commit from the master branch. It's recommended that you push from another branch, which is branched off your local master branch as done here : [fix](http://stackoverflow.com/questions/16288176/your-branch-is-ahead-of-origin-master-by-3-commits)

Also, since GitCommitBear is flagged you'll have to do rebase, amend your commit and delete the part of the shortlog(first line of the commit message) which has characters other than the given regex: ([^:]|[^:]+: [A-Z0-9].*).

After that, you can push :)

**Comment by gRSsomani** [comment]
@RohanVB In that case, Do I have to reset the changes made on my master, and submit a new pull request from a new branch and close this?
I guess, I have made only trivial changes. Do I need to do that now or keep in mind from the next time for making a new branch?

**Comment by RohanVB** [comment]
@gRSsomani it should be fine for now, but if you're working on multiple issues its better to keep the master branch in your fork in sync with the coala master branch :)

**Comment by sims1253** [comment]
ack 2e121a0

**Comment by sims1253** [comment]
@rultor merge

**Pull request merged**
