### PR TITLE
Newcomers_Guide.rst : Add smart question link

### LINKED ISSUE #4929: mention a link in smart question in newcomers guide

### PR DESCRIPTION
**Pull request by priyanshsaxena**
Added a link to guide newcomers to ask questions directly in community.

Closes #4929

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by priyanshsaxena** [comment]
@manankalra @Makman2

**Comment by priyanshsaxena** [comment]
@manankalra you might want to look it up again. @Makman2 can this now be acked ?

**Comment by newbazz** [comment]
It is not about `asking question directly in community` it is about `how to ask question ` in the community ;)

**Comment by priyanshsaxena** [comment]
@Makman2 I got a connection-reset error with Travis in a previous commit.

**Comment by priyanshsaxena** [comment]
@Makman2 @newbazz does this look good ?

**Comment by Makman2** [comment]
ack 53e6200bb68217b2fae4ecef63a821d500b5d8e8

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
