### PR TITLE
comma added to line 54 of Writing_Linter_Bears.rst

### PR DESCRIPTION
**Pull request by tab1tha**
This PR closes https://github.com/coala/coala/issues/5943

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Gromy1211** [comment]
Hi, I think you may refer to https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html and change your commit message ;)

**Comment by abhishalya** [comment]
@tab1tha You have multiple commits, squash them into one. Also follow the [commit guidelines](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html) properly. After creating a commit, just run `coala --non-interactive` and make sure that it doesn't throw any issues with your changes.

**Comment by tab1tha** [comment]
@abhishalya Please help.I do not know why it isstill failing.Should I remove the underscores from the file name?

**Comment by jayvdb** [comment]
Please rebase your commit on top of master and re-push.

**Comment by BharathKumarRavichandran** [comment]
I think the PR can be closed since the head fork repository has been deleted.

**Comment by giftcup** [comment]
Okay then.

**Comment by abhishalya** [comment]
Closing as the PR was abandoned.

**Pull request closed without merging**
