### PR TITLE
Pin minimum pip & setuptools

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes https://github.com/coala/coala/issues/3745 and https://github.com/coala/coala/issues/3748

### CODE REVIEW

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3752/commits/d1f709d32af4e85ea8031ce5cbad19d30b2378f6 https://github.com/coala/coala/pull/3752/commits/caa73143762cf3d3e0f7e88931eb85c68b2b39ca

**Comment by jayvdb** [comment]
Not exactly the same commits as this PR, but in a similar commit I am [seeing a failure](https://travis-ci.org/jayvdb/coala/jobs/202311555#L1167).
Marking WIP for now until I work it out.

**Comment by jayvdb** [comment]
Immediately after down-grading from setuptools 33.1.1 to setuptools 17.1, `pip list` says `setuptools (12.0.5)`, but `python -c "import setuptools; print(setuptools.__version__)"` says 17.1

Then of course the next time it encounters `setuptools>=17.1`, it feels it needs to upgrade it again, as it believes setuptools is 12.0.5.

https://travis-ci.org/jayvdb/coala/jobs/202334550

**Comment by jayvdb** [comment]
In regards to my last comment, we need pip 9 to safely down-grade setuptools in Travis.
The alternative to downgrading setuptools would be to create a test which sets up a venv with the desired old setuptools.  I can do it, if the current approach in this PR isnt acceptable but that is quite a lot of work, but it still isnt a good guarantee s the test wouldnt cover any new usage of pkg_resources or setuptools .

**Comment by Nosferatul** [comment]
ack b3b0269

**Comment by Nosferatul** [comment]
ack 8a46b6e

**Comment by Nosferatul** [comment]
ack e64f3c9

**Comment by Nosferatul** [comment]
@jayvdb rebase and merge if it's ok. Looks good to me

**Comment by sils** [comment]
marking approved, I'll do a round of cherry picks later

**Comment by jayvdb** [comment]
I'll rebase and merge asap. I have a few branches hanging off this branch
and it is easier for me if i resync them all together.

**Comment by jayvdb** [comment]
reack 4a7db2e 1ca9633 3ab79af

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
