### PR TITLE
OpenEditorAction.py: Add 'nvim' to list of editors

### PR DESCRIPTION
**Pull request by sbhayana26**

### CODE REVIEW

**Comment by satwikkansal** [comment]
@sbhayana26 Few things
- Please follow the [commit guidelines](http://coala.io/commit), and please squash your changes into one commit (because one commit per atomic change ;)
- All those gitmate comments are due to violation of the coding style we follow. To avoid these in future, make sure to run coala locally before pushing your changes.
- Both of the above points were mentioned in the checklist [above](https://github.com/coala/coala/pull/4096#issue-221276561). So please don't ignore them from next time onwards :)
- If there's not already an existing issue corresponding to this PR, please create one (as this is required in commit message and also it allows other maintainers to discuss and avoid some some changes that might not be required)

Hope it helps :)

**Comment by sbhayana26** [comment]
I still cannot figure out what needs to change. Please help, somebody!

**Comment by jayvdb** [comment]
@sbhayana26, come onto http://coala.io/chat and ask for help fixing this PR.

**Comment by mubaris** [comment]
Since I fixed the issue, this PR should be closed.

**Comment by Makman2** [comment]
Indeed :+1:

**Pull request closed without merging**
