### PR TITLE
Newcomers_Guide.rst: Fix promotion link markup

### PR DESCRIPTION
**Pull request by Nshul**
This fixes the typo in markup
by adding '_' after the Google promotion link.

Fixes https://github.com/coala/coala/issues/4880

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by sks444** [comment]
ack d67ded4b1975650630def6ad52a08331a5cdc4c9

**Comment by prnvdixit** [comment]
unack d67ded4b1975650630def6ad52a08331a5cdc4c9

**Comment by Nshul** [comment]
@prnvdixit according to coala commit guidelines
```
Should use the **Fixes** keyword if your commit fixes a bug, or **Closes** if it adds a feature/enhancement.
```
I dont think that this is either an enhancement or a feature, i thought it to be as a typo bug.

Considering
```
In some situations, e.g. bugs overcome in documents, the difference between Fixes and Closes may be very small and subjective. If a specific issue may lead to an unintended behaviour from the user or from the program it should be considered a bug, and should be addresed with **Fixes**.
```

and in the examples provided for correction in typo they have used **Fixes**.

**Comment by Nshul** [comment]
I will modify the Fixes from commit description to 'fixes'

**Comment by Nshul** [comment]
image

I checked my git log and apparently i have written 'fixes' and not 'Fixes'. what should i do?

**Comment by sks444** [comment]
@Nshul, You can change your commit message to "Promotion link is now working as it was missing '_' in the end." or you can replace 'fixes' with 'corrects'.

**Comment by Nshul** [comment]
Okay. I have done the necessary changes. Please review it once again.
Apologies for any inconvenience and thank you for your time.

**Comment by RaiVaibhav** [comment]
@Nshul  appreciate your work :+1: 
Commit Head is enough for explanation (it's good if you added the description here :+1: ), no more changes needed here IMO  LGTM :)
ack 60b0c024c28185c345110e94a02dc9d70ec32d84

**Comment by SanketDG** [comment]
@rultor merge

**Comment by prnvdixit** [comment]
@Nshul Yeah... that has been quite troubling thing to explain for me as well :wink:

Quoting from https://github.com/coala/documentation/issues/465#issuecomment-325203455,
> Bugs are defined as code-problems, like "a function shall not throw an exception when I give 3 as input". Everything else aren't bugs :)
Though for newcomers, the main guideline is: If an issue is labeled as a bug, use Fixes XXXX. If it's not labeled as bug, use Closes.

Since, https://github.com/coala/documentation/issues/465 is labeled "difficulty/low" now, may I ask you to resolve that yourselves since you are possibly aware of what changes needs to be done :+1:

**Comment by Nshul** [comment]
@prnvdixit thanks

**Pull request merged**
