### PR TITLE
README.rst: Update version badge

### PR DESCRIPTION
**Pull request by Yash17Agrawal**
It shows proper version.

Fixes https://github.com/coala/coala/issues/3099

### CODE REVIEW

**Comment by Yash17Agrawal** [comment]
new Head message is
README.rst: Update latest version badge
but still it is showing Shortlog of HEAD commit is 4 character(s) longer than the limit (54 > 50).
can any1 explain?

**Comment by Mixih** [comment]
@Yash17Agrawal you didn't fix it yet.

**Comment by Yash17Agrawal** [comment]
b1703f6 doesnt show it?
README.rst: Update version badge

It shows proper version

Fixes #3099

**Comment by sils** [comment]
missing fixes note

**Comment by aptrishu** [comment]
ack e322e0a

**Comment by aptrishu** [comment]
@rultor merge

**Comment by aptrishu** [comment]
@Yash17Agrawal  fill https://coala.io/newform (if not filled already)

**Comment by Yash17Agrawal** [comment]
@aptrishu thanks !

**Pull request merged**
