### PR TITLE
DocumentationComment.py: Refactor line to line number

### PR DESCRIPTION
**Pull request by mansiagarwal451**
Fixes https://github.com/coala/coala/issues/4644

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by aptrishu** [comment]
How about
shortlog Refactor docstring
body - refactor line to line number

better than using line no.

**Comment by prnvdixit** [comment]
ack 7556b14b46d945437cfbde4de0791647f6f61c0c

**Comment by mansiagarwal451** [comment]
Thanks @prnvdixit! 😄

**Comment by aptrishu** [comment]
ack 7556b14b46d945437cfbde4de0791647f6f61c0c

**Comment by aptrishu** [comment]
@rultor merge

**Comment by aptrishu** [comment]
@rultor merge

**Comment by aptrishu** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :) You've done your first step to become a coala developer.

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

We would really appreciate it if you could help us with

- [telling us about your experience](http://coala.io/newform)
- [some code reviews](http://coala.io/reviewing) for other newcomers
- fixing at least [a difficulty/low issue](http://coala.io/low)
- fill our [usability survey](http://coala.io/usability)

If you've done those and tell us about it so we can promote you to a coala developer!

We're all volunteers and we're currently struggling to keep this up. Helping all those newcomers is a lot of work and we do need your help so we can continue this for others!

**Pull request merged**
