### PR TITLE
Update Get Involved URL

### PR DESCRIPTION
**Pull request by IamRaviTejaG**
Correct the 'Get Involved' URL from README.rst

Closes https://github.com/coala/coala/issues/4710

### CODE REVIEW

**Comment by atultherajput** [comment]
@IamRaviTejaG
I am not sure as I am also new to coala community but I think you can ignore Travis CI test result for this PR.

**Comment by atultherajput** [comment]
ack 8ea4a43

**Comment by atultherajput** [comment]
Close this PR first https://github.com/coala/coala/pull/4711

**Comment by atultherajput** [comment]
And one more thing DO NOT make your changes on the master branch of your forked repository, always create a new branch while working on any issue. Read http://coala.io/newcomer for details and follow branch naming convention according to this http://coala.io/git

**Comment by atultherajput** [comment]
unack 8ea4a43

**Comment by Logan1x** [comment]
@IamRaviTejaG  are you still working on it if you are not i would like too?

**Comment by IamRaviTejaG** [comment]
@Logan1x Yes, I'm working on this. Just created a new PR. :smile:

**Pull request closed without merging**
