### PR TITLE
Sils/ignao

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by sils** [comment]
no idea what the dependency ci error is about, I disabled the service as it never found us anything and has no docs on if it needs configuration

**Comment by jayvdb** [comment]
ack 41d92f125 a9c70f4d443d

**Comment by jayvdb** [comment]
Re  	a7f4af4 , the old setting `format_str` is being removed.
Did it not work before ?
Is nobody using it?

**Comment by sils** [comment]
HM, it was not documented that this existed, there night be people using
that

**Comment by jayvdb** [comment]
ack a7f4af4021

**Comment by sils** [comment]
@rultor merge

**Comment by jayvdb** [comment]
@sils 

> HM, it was not documented that this existed, there night be people using that

coala-atom is using it, and this is one of the reasons it is broken.  A quick grep shows that `coala-vim` is also broken by this!

**Comment by sils** [comment]
yeah we have a PR to atom already, the other plugins need attention as well indeed.

**Pull request merged**
