### PR TITLE
Review.rst: Change cobot to corobo

### LINKED ISSUE #4879: Change cobot to corobo in Review.rst
For changing label we do `corobo mark wip <url>` but in documentation it is given `cobot mark wip <url>`

Replace `cobot` with `corobo` in [Review](http://api.coala.io/en/latest/Developers/Review.html).
Relevant file can be found [here](https://github.com/coala/coala/blob/master/docs/Developers/Review.rst)

### PR DESCRIPTION
**Pull request by Grox-Ni**
This corrects corobo's name

Closes #4879

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

### CODE REVIEW

**Comment by prnvdixit** [comment]
ack 2576342aa6ea94de4208a2a144b5266816600300

**Comment by stellargo** [comment]
ack 2576342aa6ea94de4208a2a144b5266816600300

**Comment by RaiVaibhav** [comment]
@Grox-Ni All changes are :+1:  , can you please provide full issue link in commit message.

**Comment by RaiVaibhav** [comment]
@stellargo  @prnvdixit  why does gitmate bot passes  when full issue link is not provided in commit message. :confused:

**Comment by Grox-Ni** [comment]
It's full link now😛

**Comment by RaiVaibhav** [comment]
Wating for CI to pass :wink:

**Comment by RaiVaibhav** [comment]
@Grox-Ni repush without any change , strange behaviour of `codecov`

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/4931/commits/ff64f5b7b7fb40fcf3a053dde555265c016f14f2

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
