### PR TITLE
DefaultArgParser: Modify help string

### PR DESCRIPTION
**Pull request by satwikkansal**
The --output option is used to write the results
into the given file, not the logs.

Closes https://github.com/coala/coala/issues/3475

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [x] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by pratyushprakash** [comment]
@satwikkansal ```Closes``` should be changed to ```Fixes```

**Comment by pratyushprakash** [comment]
ack 72aaebed95498ff1477d55ab1fa9a96f200be409

**Comment by Mixih** [comment]
@satwikkansal rebase and we can merge. Also, we recommend you to look into a difficulty/low issue now that you've fixed a newcomer issue. They are quite a bit more rewarding!

**Comment by nemaniarjun** [comment]
reack 73c8393

**Comment by nemaniarjun** [comment]
reack 73c8393

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
oh btw. actually the `Fixes` should have been a `Closes` but not a biggie

**Pull request merged**
