### PR TITLE
bearlib/__init.py: Fix typo in docstring

### PR DESCRIPTION
**Pull request by pratyushprakash**
Changes ``nondeterministic`` to ``non-deterministic``.

Closes https://github.com/coala/coala/issues/2838

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Hey, the change is fine but a rebase is required :)

**Comment by pratyushprakash** [comment]
@Adrianzatreanu Thanks for your help! I was about to push the button

**Comment by Adrianzatreanu** [comment]
ack 45a504802cfcd3a0c3196ba16c9939b84de2d9a7

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
