### PR TITLE
.coafile: Add YAMLLintBear

### PR DESCRIPTION
**Pull request by bekicot**
Enable YAML linting and fix files that have
line length problems.

Closes https://github.com/coala/coala/issues/4372

### CODE REVIEW

**Comment by jayvdb** [comment]
Depends on https://github.com/coala/coala/issues/4375 being fixed.

**Comment by jayvdb** [comment]
https://github.com/coala/coala/pull/4376 has been merged.  You can now rebase.

**Comment by jayvdb** [comment]
https://github.com/coala/coala/pull/4394 has also been merged.  This patch is getting much smaller .. ;)

**Comment by Makman2** [comment]
No recent activity and no responds on reviews, closing. Feel free to reopen if you wanna continue to work (but please only with an assignment ;) )

**Pull request closed without merging**
