### PR TITLE
setup.cfg: Change [pytest] to [tool:pytest] on line 5

### PR DESCRIPTION
**Pull request by jasemj**
### Checklist

- [X] I have rebased properly. Please see [our tutorial on rebasing](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing).
- [X] I have gone through the [commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html) and I've followed them.
- [X] I have followed the [guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
- [X] I have followed the [guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
- [X] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference).
- [ ] I have [run all the tests](http://coala.readthedocs.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### Reviewers

Add [tool:pytest] becuase [pytest] deprecated and conflicts
with pytest in disutils.

Fixes https://github.com/coala/coala/issues/3097

### CODE REVIEW

**Comment by aptrishu** [comment]
Tests are failing. marking it wip.

**Comment by aptrishu** [comment]
Squash your commit into a single commit and fix you Gitmate issues.

**Comment by Adrianzatreanu** [comment]
ack 8eac257e11dd1a89404e46dfc2ffe3fcca00c828

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
