### PR TITLE
Update ConfigurationGathering.py; Fixes #5025

### LINKED ISSUE #5025: ConfigurationGathering.py: Fix docstring of function warn_config_absent()
return values of True and False are interchanged

difficulty/newcomer

### PR DESCRIPTION
**Pull request by shikhar-scs**
I am a Short Term Contributor

As suggested by @ishanSrt [here](https://github.com/coala/coala/issues/5025) I have made the required changes in the ` coalib/settings/ConfigurationGathering.py` file
### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

Please Review

### CODE REVIEW

**Comment by ishanSrt** [comment]
Please follow the commit guidelines

**Comment by jayvdb** [comment]
Dont work on issues without being assigned.  in this case, we already have a PR.

**Comment by ishanSrt** [comment]
@jayvdb reopen this PR and assign @shikhar-scs to the issue as he was the first to call for assignment

**Comment by shikhar-scs** [comment]
Actually I had asked for the issue first (and was waiting to be assigned )and then @ppatel221 filed a PR without any permissions. So, I was asked to file a PR again [here](https://github.com/coala/coala/issues/5025#issuecomment-355076522). Nevermind, I will look for another issue.

**Comment by shikhar-scs** [comment]
As mentioned by @Makman2 at #5025, this issue has been assigned to me, @jayvdb could you please re open this PR

**Comment by Makman2** [comment]
Reopened ;)

**Comment by Makman2** [comment]
Why closing?

**Comment by shikhar-scs** [comment]
I messed up a bit while squashing and pulling. I've opened a new PR

**Comment by Makman2** [comment]
You can always fix your PR without closing it, please refrain next time from opening another PR for the same issue^^

**Pull request closed without merging**
