### PR TITLE
aspects/taste.py: change an to to in line 58     fixes https://github…

### PR DESCRIPTION
**Pull request by nikita1412**
….com/coala/coala/issues/3869

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Techievena** [comment]
I am sorry about the issue. I have updated it. Please change it accordingly. Also you need to follow the commit guidelines. See https://coala.io/commit

**Comment by Techievena** [comment]
Please squash your commits into one. https://api.coala.io/en/latest/Developers/Git_Basics.html#squashing-your-commits

**Comment by nikita1412** [comment]
@Techievena I have squashed the commits .i.e I have followed the steps in the link.

**Comment by nikita1412** [comment]
@Techievena Hope the amended commit message now satisfies the commit guidelines.Looking forward to your response.

**Comment by Techievena** [comment]
Great going @nikita1412!!! :smile:  but you need to understand that you should never include line number in your commit message. Commit message is needed for maintaining coala codebase and keeping track of changes and line number is surely going to change with addition of new code to the file. Also `Type` --> `type`

**Comment by nikita1412** [comment]
@Techievena done the required changes and I added line number to add more specifcation for the changes made but yes your point is correct so removed it.
what next ? I want to apply for GSOC'17.

**Comment by Techievena** [comment]
Oops missed it `Fixes` --> `Closes` as this is not a bug fix.

**Comment by Techievena** [comment]
Write a strong proposal and continue contributing to the codebase to gain familiarity.

**Comment by adtac** [comment]
@nikita1412 cheers, thanks for the PR. This is mergeable except that it requires a rebase. Please see http://coala.io/rebase for more details.

**Comment by adtac** [comment]
CircleCI should pass the next time you push.

**Comment by Techievena** [comment]
ack d7c09df

**Comment by nemaniarjun** [comment]
@nikita1412 @Techievena 
Can the commit message be more clear?
Something like
```
This now correctly implies that there is 
no need to specify cast type for new taste.
```
?
Just a recommendation :D

**Comment by supergr35** [comment]
@nemaniarjun @nikita1412 @Techievena 
I would even go so far as to say that
`Imply that there is no need
to specifiy cast type for new taste`
Is a good shortlog, as this message is in the imperative mood and describes why this change is necessary. This will also need a rebase.

**Comment by nikita1412** [comment]
@Techievena @supergr35 @nemaniarjun commit has been amended as mentioned by @supergr35 and I have also rebased the repo.
One point I want to mention is mostly I have worked in industry,no one really cared this much for the commit message.You all giving so much time for it is commendable.May be this is the reason,open source project grows.
Appreciate your efforts.

**Comment by jayvdb** [comment]
ack 1deff62

**Comment by jayvdb** [comment]
@rultor merge

**Comment by jayvdb** [comment]
Welcome aboard @nikita1412

**Pull request merged**
