### PR TITLE
README: Change pip requirement to >=6

### PR DESCRIPTION
**Pull request by mamakancha**
### Check list

- [ ] I have rebased properly.
      [Please see this for a tutorial.](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing)
- [x] I have gone through the
      [commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html)
      and I've followed them:
 - [x] I have followed the
       [guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
 - [x] I have followed the
       [guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
 - [ ] I have included the issue URL with the  `Fixes` keyword if the
       commit fixes a *real bug* and the `Closes` keyword if it adds a
       feature/enhancement.
       [See more here.](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference)
- [x] I have [run all the tests](http://coala.readthedocs.io/en/latest/Developers/Executing_Tests.html)
      and they all pass. If any CI (below) is not green, please fix them. If
      GitMate issues appear you will have to amend your commits, pushing new
      commits on top is not sufficient!

### Reviewers

Fixes https://github.com/coala/coala/issues/2934

### CODE REVIEW

**Comment by mamakancha** [comment]
I have again made a pull request. Tried to fix https://github.com/coala/coala/issues/2934

**Comment by sils** [comment]
Hi, you haven't rebased correctly, see tutorial. You have a merge commit.

**Comment by sils** [comment]
Hey,

we use some bug prediction in coala which relies on the `Fixes` keyword in commit messages. To get good results from that we need to use `Closes` for normal issues instead of `Fixes` which should only be used for real bugs. (See also [the commit message docs](http://coala.io/commit).) Use a closes here!

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by sils** [comment]
astonishing - why didn't gitmate pick this up :(

**Comment by mamakancha** [comment]
Not a problem. I plan to stay here for long. Will do the needful :)
Thanks for the suggestions!

**Comment by mamakancha** [comment]
I have a doubt. After amending my commit message, do I have to submit a new pull request?

**Comment by sils** [comment]
No, just force push like described in the docs

**Comment by mamakancha** [comment]
I have changed "Fixes" with "Closes" in my commit message and pushed it.
Also I have followed the commands for rebasing.
Am I good to go or are there still any issues in the above mentioned activities? :(

**Comment by sils** [comment]
hey @mamakancha you didn't force push it up, huh? The PR is the same as before. If you have done all that's needed you only need to `git push -f`

**Comment by mamakancha** [comment]
Hi. I checked out the branch in which I had made the changes and then tried to push by `git push -f`
and got "Everything up-to-date" message. What should I do now?

**Comment by sils** [comment]
Please read up on the rebase and git remotes so you understand what's going on, this PR is not rebased on our repository.

**Comment by Adrianzatreanu** [comment]
hey, this is not a bug so Closes should work instead of Fixes.

also, you need to rebase correctly :D you have stolen a commit from someone else i think

**Comment by mamakancha** [comment]
@sils  I am not able to figure out what has gone wrong . Should I repeat the whole process from the scratch and submit a new pull request?

**Comment by mamakancha** [comment]
@Adrianzatreanu Hi. I am not clear about the commit part. From whom have I stolen? It should be a mistake for sure. Tell me so that nothing of this sort happens in future.

**Comment by sils** [comment]
I think a rebase should get rid of the accidentally "stolen" commit. No need to repeat the process from scratch, nothing an interactive rebase (google that :)) can't solve

**Comment by mamakancha** [comment]
Hi. Sorry for being away for a while. Right now I am closing this pull request since I won't be able to contribute for until next week due to my college examinations. If the issue doesn't get closed by then, I will surely fix it up as soon as possible. If not, I will try to fix other (beginner)issues.

**Pull request closed without merging**
