### PR TITLE
Linter.py : Replace Double Quotes

### PR DESCRIPTION
**Pull request by starkblaze01**
This ensures that it replace Double Quotes with Single Quotes in Docstrings where needed. 

Closes https://github.com/coala/coala/issues/4940

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
Also, it's not advice able to close your PR's multiple times. 
In case you have any issues related to git. 
You can ping in the gitter channel. 
And we'll help you out.

**Comment by starkblaze01** [comment]
@mridubhatnagar ,Thanks for guiding. Are these changes in Commit Message suitable. Please Review

**Comment by mridubhatnagar** [comment]
>Linter.py: Replace double quotes

>Replaces double quotes with 
>singal quotes.

>Closes https://github.com/coala/coala/issues/4940

**Comment by starkblaze01** [comment]
@mridubhatnagar 
Pardon for the trouble.
kindly review the current changes.

**Comment by mridubhatnagar** [comment]
LGTM. Just last and minor change. 
In commit body add full stop after quotes. 
I shall ack it then  :)

**Comment by starkblaze01** [comment]
Done. 👍

**Comment by mridubhatnagar** [comment]
ack  cbe32a4

**Comment by mridubhatnagar** [comment]
@starkblaze01 for future references. Just a reminder whenever you
work on an issue. Please branch off from the master and create a separate 
branch. Why you should not work on master branch the reason for it is 
here http://api.coala.io/en/latest/Developers/Newcomers_Guide.html

**Comment by starkblaze01** [comment]
Thanks for the guidance, I will take care of it next time.

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Pull request merged**
