### PR TITLE
Linter: Use super check_prerequisites

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by sils** [comment]
@ramoska

**Comment by ramoska** [comment]
ACK 643d295cc68573094ec5f6c7b3e8a3839b9ff90f

**Comment by sils** [comment]
@ramoska pushed another commit because tests are failing sometimes because due to us adding lxml dep installation step takes longer and sometimes times out

**Comment by fneu** [comment]
ack https://github.com/coala/coala/pull/4467/commits/32157eb4c681bc16b5ee6f4ecc317ad6a4c8aa18

**Comment by ramoska** [comment]
ACK 32157eb4c681bc16b5ee6f4ecc317ad6a4c8aa18

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
