### PR TITLE
Linter_Bears_Advanced.rst: Fix typo

### PR DESCRIPTION
**Pull request by rajvaibhavdubey**
This changes value=2 -> value2.

Closes https://github.com/coala/coala/issues/5165

### CODE REVIEW

**Comment by monsij** [comment]
Why did you closed the pr? @rajvaibhavdubey

**Comment by rajvaibhavdubey** [comment]
@MacBox7 approved the changes , That's why is close the PR @monsij

**Comment by MacBox7** [comment]
@rajvaibhavdubey approving changes doesn't mean that it has been merged. Other reviewers would also review them and finally, the moderator will merge it.

**Comment by Makman2** [comment]
ack 942dcde766fbc1b3490af835542211b08f6fb4d0

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
