### PR TITLE
Update ConfigurationGathering.py Fixes #5025

### LINKED ISSUE #5025: ConfigurationGathering.py: Fix docstring of function warn_config_absent()
return values of True and False are interchanged

difficulty/newcomer

### PR DESCRIPTION
**Pull request by shikhar-scs**
Short Term Contributor

As suggested by @ishanSrt at #5025, I have made the required changes.

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by ishanSrt** [comment]
follow the commit guidelines http://coala.io/commit

**Comment by shikhar-scs** [comment]
@newbazz yeah sure I'll do that asap

**Comment by shikhar-scs** [comment]
@newbazz I've corrected the commit message, Please review

**Comment by shikhar-scs** [comment]
Done. Please have a look at the commit message now.

**Comment by ishanSrt** [comment]
Your commits should convey exactly what you are doing without the addition of redundant details 😉

**Comment by shikhar-scs** [comment]
Have a look at it now

**Comment by shikhar-scs** [comment]
> Swaps -> Swap

done

**Comment by Makman2** [comment]
ack 1898937c9be8d54da7081f64813f71deaa622251

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot ff

**Comment by shikhar-scs** [comment]
Thanx a lot @Makman2 for merging this

**Pull request merged**
