### PR TITLE
requirements.txt: Update dependency_management version

### LINKED ISSUE #3484: requirements.txt: Upgrade dependency_management version to 0.2.0
Currently, the version is `0.1.7`
Update to dependency_management `0.2.0`

### PR DESCRIPTION
**Pull request by vijeth-aradhya**
Update dependency_management from `0.1.7` to `0.2.0`

Closes #3484 

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [ ] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by Mixih** [comment]
hmm, as it's a requirements upgrade, I'd want a ticket(issue) just in-case we get a ticket based release note writing system. Thanks!

**Comment by vijeth-aradhya** [comment]
Alright I'll create an issue and reference it here :+1:

**Comment by Mixih** [comment]
also, this need to be applied at coala-bears, otherwise many things will break. x-ref the prs please so we can merge them together.

note to maintainers: do not merge until the one in coala-bears is approved, otherwise we can get dependency hell.

**Comment by vijeth-aradhya** [comment]
Can I know what exactly should be changed in `coala-bears` about `dependency_management` so that I can x-ref the PRs?
Thanks!

**Comment by Mixih** [comment]
^ Not needed, we have inheritance set correctly

**Comment by Mixih** [comment]
ack 79f996f

**Comment by Mixih** [comment]
@rultor merge

**Comment by Mixih** [comment]
@rultor merge

**Pull request merged**
