### PR TITLE
Adding CI to Newcomers Guide

### PR DESCRIPTION
**Pull request by Harshish**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

Fixing https://github.com/coala/coala/issues/3755

### CODE REVIEW

**Comment by Shade5** [comment]
I think 
```
Before we get to the next step add 
`CI <http://api.coala.io/en/latest/Developers/Adding_CI.html>`_
 to your fork.
```
Would fit better

**Comment by jayvdb** [comment]
Why does this PR have two commits?
You haven't followed our newcomer documentation, [step 8](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-8-review-process).

**Comment by RohanVB** [comment]
It appears you made the second commit on Github, not local+push. Please rebase, squash the extra commit and push :)

**Comment by Harshish** [comment]
I am a bit lost here.I squashed and sent the pull request but I don't understand what I am doing wrong.It would be great if someone could help me out.Sorry for being such a noob.

**Comment by sgsh123** [comment]
Hi,

While even I am new to this I think the problem occurring is that though you squashed the commits locally as you had already uploaded two separate commits to this pull request remotely this request took in the squashed commit as a new commit. I think the best solution would be to close this pull request and start a new one with only a single commit.

Also the Gitmate errors are occurring as you have not push a space after the : in the shortlog and because your shortlog is exceeding the character limit.
 
Hope this helped!

**Comment by Shade5** [comment]
Did you recommit locally?
What does `git log -5` say ?

**Comment by Harshish** [comment]
Thank you very much for your help and support as suggested by @sgsh123 I will close this pull request and send a new one. Apologies for any inconvenience caused.

**Comment by aptrishu** [comment]
Hi @Harshish , Do you need help with rebasing ? Please ask us on our channel(https://gitter.im/coala/coala).
You should rectify your current PR rather than opening a new one. This is how you learn, newcomer issues are all about getting yourself acquainted with the workflow..

**Comment by Harshish** [comment]
Alright @aptrishu I will keep that in mind from  now :)

**Pull request closed without merging**
