### PR TITLE
AppVeyor CI: Allow builds on forks

### PR DESCRIPTION
**Pull request by jayvdb**
Exclude only branch 'sils/*'.

Closes https://github.com/coala/coala/issues/3516
Related to https://github.com/coala/coala/issues/3664

### CODE REVIEW

**Comment by Udayan12167** [comment]
ack a9cec67

**Comment by Udayan12167** [comment]
@rultor merge

**Comment by jayvdb** [comment]
reack 8a3f55e

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
