### PR TITLE
Makman2/merge together

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by Makman2** [comment]
reack db532ea 3a95d0a 5c7e2ee b3e8956 67699a4

**Comment by nemaniarjun** [comment]
You can add this too, I think? https://github.com/coala/coala/pull/3469 :D

**Comment by Makman2** [comment]
@nemaniarjun it's again pending review because there was something changed, commit wasn't acked yet and sils seems to be responsible

**Comment by nemaniarjun** [comment]
It was just a rebase I think?

**Comment by Makman2** [comment]
then it has to be reacked by the rebaser :+1:

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3594/commits/db532ea232eeb70c25f9c7a2e25e204fe2fdfd20

**Comment by sils** [comment]
ack db532ea

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
