### PR TITLE
Newcomers_Guide.rst: Remove bolding from heading

### PR DESCRIPTION
**Pull request by sidharthskumar**
removed double quotes that enclosed -pull request and also unwanted
underline

Fixes https://github.com/coala/coala/issues/4442

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by sidharthskumar** [comment]
I think I have followed the guide ; about the commit body there's isn't much to be written since i have  mentioned what I have done and the commit log was suggested by John and what else should be changed ?

**Comment by IpshitaC** [comment]
ack fc5b5baa8342308bede6ad7b76dda6c856f8d2d4

**Comment by jayvdb** [comment]
ack fc5b5baa

**Comment by jayvdb** [comment]
@rultor merge

**Comment by sidharthskumar** [comment]
@IpshitaC @jayvdb thank you so much for merging my second newcomer issues :D . Looking forward to low issues 👍

**Pull request merged**
