### PR TITLE
Release notes now published at api docs

### PR DESCRIPTION
**Pull request by aaqaishtyaq**
Release Notes are now published at api docs.
I was not familiar with reStructuredText.
I was initially trying to add ```Release Notes``` in 
```rst
.. toctree::
   :caption: Home
   :hidden:

   Welcome <self>
   Homepage <http://coala.io/#/home>
   Release Notes <release_notes>
   Code of Conduct <http://coala.io/coc>
```
but it was giving out every title in this toctree, which is not suitable so I shifted ```Release Notes``` to it's own ```toctree```.
Also to commit ```release_notes.rst``` i have to exclude it from ```.gitignore```.
Closes: #5724 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Man-Jain** [comment]
Don't ask for review in Pull Request description. It is useless, either ask in gitter channel or in PR comments.

**Comment by aaqaishtyaq** [comment]
@Man-Jain I'll keep in mind next time.

**Comment by jayvdb** [comment]
@aaqaishtyaq , you need to fix this PR, otherwise there is no next time.

**Comment by aaqaishtyaq** [comment]
@jayvdb looks good now?

**Comment by aaqaishtyaq** [comment]
@jayvdb Squash both commit into one. Also changed commit message and description as suggested by @Man-Jain

**Comment by Man-Jain** [comment]
@aaqaishtyaq The commit body contains more than 72 characters per line. You will have to fix that.

**Comment by aaqaishtyaq** [comment]
@Man-Jain do not repeat what gitmate-bot is saying. I can read that.
FYI Already fixed that, just see commit message.

**Comment by Man-Jain** [comment]
@aaqaishtyaq Yeah you did. My bad. Sorry

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5727/commits/9e8066e698386bc037cdacaa22c56fc34fa5b70b

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
