### PR TITLE
Newcomers_Guide.rst: Correct grammatical errors

### PR DESCRIPTION
**Pull request by AlexandruGhimisi**
Closes https://github.com/coala/coala/issues/3619

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by RohanVB** [comment]
ack 54910ec12039cf4b9781231f52ac926e8e10c1fa

**Comment by adtac** [comment]
@AlexandruGhimisi requires rebase :)

See http://coala.io/rebase if you need any help.

**Comment by supergr35** [comment]
Once again, this will need a rebase before it is merged.

**Comment by AlexandruGhimisi** [comment]
@supergr35 Done.

**Comment by RohanVB** [comment]
d53ba72c8a4c9a6bddcd27c12a9b74151c585a27 is ready

**Comment by PierceAndy** [comment]
ack d53ba72

**Comment by NiklasMM** [comment]
Sorry mate, you'll have to rebase again :sweat_smile:

**Comment by AlexandruGhimisi** [comment]
Done. How many times do I have to do it ?

**Comment by NiklasMM** [comment]
reack c2640a0

**Comment by NiklasMM** [comment]
@rultor merge

**Comment by NiklasMM** [comment]
@AlexandruGhimisi well, your branch goes out of sync the moment we merge another PR. So ideally just once, if a maintainer pays attention and merges it right away

**Pull request merged**
