### PR TITLE
Replaced Comma with Colon

### PR DESCRIPTION
**Pull request by Gitcat711**
In Step 2 of newcomer guide #4793

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by adtac** [comment]
Hi,

It seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.io/commit !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by adtac** [comment]
unack https://github.com/coala/coala/pull/4798/commits/67e6ae64173bc30788301f5fe231003817bc085a

**Comment by Gitcat711** [comment]
I am happy for the positive criticism & taking the minors changes into
consideration. I will surely try to create better commits, and will try to
contribute with extra efforts.
Really grateful for the effort people take to literate noon like me. Thanks
again :P

**Comment by Makman2** [comment]
As mentioned, the issue is reserved for coming GCI participants. Also you started working without an assignment. Please make sure next time to get assigned to an issue (not marked with `initiatives/gci`), we won't accept PRs until then. Closing.

But feel free to pick another issue ;)

**Pull request closed without merging**
