### PR TITLE
.coafile: Modify circleci config file location

### LINKED ISSUE #5375: Change .coafile as circle.yml no more exists
In the yml section of the .coafile we have circle.yml which no more exists
Change it to its new path

### PR DESCRIPTION
**Pull request by souravbadami**
Related to #5375.

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by palash25** [comment]
If you change the commit message according to the guidelines I think the CIs should pass

**Comment by souravbadami** [comment]
@palash25 -- Updated. I hope it does.

**Comment by palash25** [comment]
@souravbadami please read the whole commit guidelines doc first. It still has a few problems. Or you can just read the comments by the gitmate-bot and make the fixes accordingly.

**Comment by souravbadami** [comment]
@jayvdb -- Can we merge this ?

**Comment by souravbadami** [comment]
@jayvdb -- Yeah, modified and pushed!

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5681/commits/4b005e3e43a5a4e82572869a23febbcfae6bd1ad

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
