### PR TITLE
Add pytest-profiling

### PR DESCRIPTION
**Pull request by jayvdb**
See https://travis-ci.org/jayvdb/coala/jobs/394414992#L814

### CODE REVIEW

**Comment by RaiVaibhav** [comment]
One question why does it need:sweat_smile: ,one disadvantage it that `pytest-pofiling` display only first `20` profiled data on the basis of cumulative time, the only reason I see to use the `pytest-profiling` is because of its `--profile-svg` feature which I find very useful but we can add something which store some image during every `run`.

**Comment by RaiVaibhav** [comment]
Although changes looks good :+1:

**Comment by jayvdb** [comment]
> ,one disadvantage it that pytest-pofiling display only first 20 profiled data on the basis of cumulative time

[sofixit](http://enwp.org/sofixit)

**Comment by RaiVaibhav** [comment]
got it :laughing:

**Comment by jayvdb** [comment]
unack 99b042a
moban first, then update commit message here, etc.

**Comment by RaiVaibhav** [comment]
Sorry I didn't see the mail :+1:

**Comment by jayvdb** [comment]
@RaiVaibhav , please approve the moban patch.

**Comment by jayvdb** [comment]
reack https://github.com/coala/coala/pull/5548/commits/909853f047ddf7edb9b9882fadf472d5ed6e15d4

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
