### PR TITLE
Update sphinx versions in docs-requirements and remove CI workaround pip install docutils==0.13.1

### PR DESCRIPTION
**Pull request by userzimmermann**
Latest `sphinx` and `sphinx-argparse` releases contain lots of improvements and fixes, as further pointed out in https://github.com/coala/coala/issues/4329#issue-233901346 , https://github.com/coala/coala/pull/4334#issuecomment-306745505 , and https://github.com/coala/coala/pull/4334#issuecomment-307787288 , and make the `docutils` downgrade workaround obsolete

Closes https://github.com/coala/coala/issues/4329 and https://github.com/coala/coala/issues/4331

### CODE REVIEW

**Comment by jayvdb** [comment]
IMO this is blocked on https://github.com/coala/coala-bears/pull/1569 ; we dont want to be running different versions of sphinx on two repos that are so tightly coupled.

**Comment by userzimmermann** [comment]
@jayvdb https://github.com/coala/coala-bears/pull/1569 is strange, since it is about updating `sphinx` to `1.5.5`, which is actually currently used in `coala`, and that PR's failing https://circleci.com/gh/yash-nisar/coala-bears/106?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link even ignores that and runs `1.4.9`

**Comment by userzimmermann** [comment]
@jayvdb So... After merging https://github.com/coala/coala-bears/pull/1819 , this should be safe to be merged too :) Then both repos' CI build docs with `sphinx-1.6.2`

**Comment by userzimmermann** [comment]
Took over the `docutils` downgrade workaround removal commit from https://github.com/coala/coala/pull/4334 and closed the latter in favor of this one

@jayvdb Let's merge that finally :)

**Comment by sils** [comment]
I'm rebasing this for you to #4430 and merging it

**Pull request closed without merging**
