### PR TITLE
InvalidFilterException: Change base class

### PR DESCRIPTION
**Pull request by richer6605**
Change base class from Exception to LookupError.

Closes https://github.com/coala/coala/issues/4873

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

### CODE REVIEW

**Comment by userzimmermann** [comment]
@richer6605 And BTW: Most important is to adapt the commit message, not the PR summary ;)

**Comment by richer6605** [comment]
@userzimmermann Thanks :) I'll adjust both the commit messae and PR quickly.

**Comment by richer6605** [comment]
@userzimmermann Modified both the commit and PR message. Please check, thx!

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/4910/commits/7d4d0787da7da2287585a26e35274a73aa8d0e86

**Comment by userzimmermann** [comment]
@rultor merge

**Comment by userzimmermann** [comment]
@richer6605 You're welcome :)

**Pull request merged**
