### PR TITLE
Newcomers_guide: Fixes Indentation Issue

### PR DESCRIPTION
**Pull request by maykillmore**
This ensures that `$git checkout -b <branchname>` appears as inline code.

Closes https://github.com/coala/coala/issues/3276#event-960532489

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Siddhartha1234** [comment]
Write the commit message in an imperative tense i.e change it from "Fixes" to "Fix" and do not exceed 72 characters.

**Comment by Sanny26** [comment]
Commit message should have a short log, body and issue reference as mentioned at http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html
Yours has only 'Change made' message. Maybe you can do a git commit --amend

**Comment by yash-nisar** [comment]
PING @maykillmore

**Comment by yash-nisar** [comment]
Still on it @maykillmore ?

**Comment by yash-nisar** [comment]
Same case here @SanketDG

**Comment by yash-nisar** [comment]
@Adrianzatreanu @SanketDG Still no work being done on this.

**Comment by jayvdb** [comment]
Commit message not fixed; closing.

**Pull request closed without merging**
