### PR TITLE
Fix docs/_static/custom.css file lint errors

### PR DESCRIPTION
**Pull request by satwikkansal**
### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [x] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by andreidinu** [comment]
I think you should squash your commits as they are related to the same issue. Take a look here: [](url)http://api.coala.io/en/latest/Developers/Git_Basics.html?highlight=squashing. You should also change the title to a more verbose one. We can see the issue you fixed in the commit message too.

**Comment by satwikkansal** [comment]
@andreidinu IMO we should keep both the commits as both the commits are related to different files and solving somewhat different issues :)

**Comment by sils** [comment]
Fixes -> Closes

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3489/commits/da898002c0c6e119591b37f064d8a41b23e2c61b

**Comment by sils** [comment]
unack https://github.com/coala/coala/pull/3489/commits/3377247a8e719e293f896787bce60dbaf2387fa3

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3489/commits/99b9879fb4b09b6c4a01c0ba97278e2a47820f45 https://github.com/coala/coala/pull/3489/commits/dc780525a23e50a2b3b0b8bf8d49137bcc2d7ebe

This is good to go, one rebase left to do, then ping us for merge :)

**Comment by sils** [comment]
dc78052 ack

**Comment by satwikkansal** [comment]
@sils Done rebase :)

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3489/commits/9229e228f68ec38757873b56bd9024eec9986513

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3489/commits/265ea5885332ba0a4c43aa83b6420c30f46c3292

**Comment by sils** [comment]
@rultor merge

**Comment by jayvdb** [comment]
Note this isnt working properly.  https://github.com/coala/coala/issues/3360#issuecomment-274298207 reopened.

**Pull request merged**
