### PR TITLE
Included terminal command to install Git via XCode on MacOS

### LINKED ISSUE #3843: Git Basics: Mention Xcode for MacOS
Following on from https://github.com/coala/coala/issues/3256 , the macos note should mention that git may be installed via Xcode.

https://www.atlassian.com/git/tutorials/install-git#mac-os-x

Xcode has other useful tools for developers, so it should be a preferred and recommended way to get these tools.

### PR DESCRIPTION
**Pull request by Rddhima-R**
Git_Basics.rst: add how to install Git via XCode on MacOS

closes #3843

### CODE REVIEW

**Comment by impmihai** [comment]
Use `git commit --amend` to update your last commit instead of creating a new commit for every change. Then push that with `git push --force`.

**Comment by Rddhima-R** [comment]
@impmihai yep just realized my mistake! Thanks!

**Comment by jayvdb** [comment]
Please squash your commits; see our newcomer and git guides, and ask for help on gitter if required.

**Comment by supergr35** [comment]
Your commit message right now is a bit....strange. Please follow our documentation.

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/3866/commits/c3eb00f5fd9f39e7e36c496cb1d0497eae190159

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
