### PR TITLE
Move coalib.misc.Annotations into coalib.settings

### PR DESCRIPTION
**Pull request by Abhisek-**
- Move typechain(in coalib.misc.Annotations) to coalib.settings as
  all type modules are in coalib.settings.
- Move the corresponding test moudule(tests.misc.AnnotationsTest) to
  tests.settings

Fixes https://github.com/coala/coala/issues/3049

### CODE REVIEW

**Comment by Mixih** [comment]
You will probably have to open a commit in coala-bears to make sure this change does not break any bears... Please mention that pull in this pull so we know when we can merge.

**Comment by Abhisek-** [comment]
I think `coala-bears` doesn't use `typechain` function anywhere. I did `git grep typechain` and nothing came actually. Am I missing something ??

**Comment by sils** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.io/git) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

(Be sure to use coala-bears on the coala-bears repository :))

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3197/commits/18ea3c401308eb777d416b80f63c904a75bccfe8

**Comment by sils** [comment]
@Abhisek- ok thats true, I'll take care of getting this merged. No actuin from you required but don't press the "update branch" button again :)

**Comment by Abhisek-** [comment]
Okay @sils , I didn't know that. I won't do it again

**Comment by sils** [comment]
cherry picked to https://github.com/coala/coala/pull/3207

**Comment by sils** [comment]
it's alright, everyone does it first tie :P

**Pull request closed without merging**
