### PR TITLE
ConsoleInteraction.py : Fix error message

### PR DESCRIPTION
**Pull request by sanjeethboddi**
This fixes error message from
enter a valid letter. -> enter a valid letter or number.

Fixes https://github.com/coala/coala/issues/5219

### CODE REVIEW

**Comment by palash25** [comment]
@sanjeethboddi Fix the issue raised by gitmate-bot your circle build is failing because of that.

**Comment by virresh** [comment]
Also keep in mind fixes/closes are keywords in Github

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5293/commits/8a8b1d2cc42f7258df964b8ad56bc897d9632c12

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
