### PR TITLE
Add link to Code of Conduct to docs

### PR DESCRIPTION
**Pull request by Mariatta**
Closes https://github.com/coala/coala/issues/3551

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [ ] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by hemangsk** [comment]
ack c882f91

**Comment by Mariatta** [comment]
@rultor merge

**Comment by hemangsk** [comment]
ack 3a906fa

**Comment by Mariatta** [comment]
@rultor merge

**Comment by aptrishu** [comment]
rebase needed..

**Comment by jayvdb** [comment]
After rebase and push, please reack your own commit and merge it.

**Comment by Mariatta** [comment]
reack 57a21a4

**Comment by Mariatta** [comment]
@rultor merge

**Comment by Mariatta** [comment]
reack 57a21a4

**Comment by Mariatta** [comment]
@rultor merge

**Pull request merged**
