### PR TITLE
Add pytest-travis-fold

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by arjunsinghy96** [comment]
ack https://github.com/coala/coala/pull/4088/commits/f7d20de4c7c37da7c385c6e2d7d74875b4fd7fed

**Comment by jayvdb** [comment]
Fwiw, here is an example of an error
https://travis-ci.org/jayvdb/coala/builds/220924263

**Comment by adtac** [comment]
@cherry-pick-bot

**Comment by yukiisbored** [comment]
@cherry-pick-bot cherry pls

**Comment by yukiisbored** [comment]
@cherry-pick-bot

**Comment by yukiisbored** [comment]
@cherry-pick-bot

**Comment by jayvdb** [comment]
reack https://github.com/coala/coala/pull/4088/commits/e942c2072c6ebddd6139c673c5e0b0ed24324fa0

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
