### PR TITLE
Testing_Bears.rst: Update settings snippet

### PR DESCRIPTION
**Pull request by mohitkyadav**
Changed settings={'max_number_of_lines': int=20} to settings={'max_number_of_lines': 20}

Fixes https://github.com/coala/coala/issues/3873

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by mohitkyadav** [comment]
@prnvdixit done :+1:

**Comment by IpshitaC** [comment]
ack dd57124c79c788d3e7bd1b71e05f0d7f6448273c

**Comment by shoorik007** [comment]
coll

**Comment by Makman2** [comment]
Commit message body a bit redundant (the change is immediately visible in the commit diff), but doesn't really harm ;)

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
