### PR TITLE
package.json: Remove extra spacing

### PR DESCRIPTION
**Pull request by Nickatak**
This pull request removes extra spacing on the closing bracket for dependencies in package.json.  It ensures consistency in whitespace.

Fixes https://github.com/coala/coala/issues/4056

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Nickatak** [comment]
YAY, it worked! :D I screwed it up, and then fixed it, and then screwed it up again, and then fixed it :D

**Comment by Nickatak** [comment]
Changed: 
`Fixes #4056` => `Closes #4056`
in commit-body (it is the body? Or is it the tail? I'm trying to get a hang of all the terminology x_X)

**Comment by Makman2** [comment]
It's the body ;) The commit consists of the shortlog (the first line) and the body (following the first line). There's no commit tail (though I like this word, if git would be newer this might have become established :D)

**Comment by Makman2** [comment]
ack 9cc9fd6b18a4e9f1778d10b1e6e98f65013421ae

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
