### PR TITLE
Smell.py: Fix docstring bracket typo

### PR DESCRIPTION
**Pull request by rajendraarora16**

### CODE REVIEW

**Comment by rajendraarora16** [comment]
@newbazz updated!

**Comment by rajendraarora16** [comment]
[#5121](https://github.com/coala/coala/pull/5121)

**Comment by newbazz** [comment]
Dont close PRs.

**Comment by Makman2** [comment]
Please fix it up here.

**Comment by rajendraarora16** [comment]
@newbazz Sorry for the late response, I was facing git memory issues on windows. Are we good to go now? :)

**Comment by newbazz** [comment]
@rajendraarora16 nope see other PRs commit messages and compare it with that of yours

**Comment by sangamcse** [comment]
@newbazz I think he has deleted his branch. 😞

**Comment by jayvdb** [comment]
@pareksha, can you check if this is still a problem, and create an issue about it.

**Comment by pareksha** [comment]
@jayvdb yes this is still a problem. I have created https://github.com/coala/coala/issues/5364.

**Pull request closed without merging**
