### PR TITLE
dep.sh: Enforce only two containers in Circle CI

### LINKED ISSUE #4137: Error if circle containers is >2
https://github.com/coala/coala/issues/3352 prevented less than 2 containers, but allows more, which waste resources

Opened via [gitter](https://gitter.im/coala/coala/?at=590020ba587a245e244b95ea) by @jayvdb

### PR DESCRIPTION
**Pull request by aryanshar**
Restricting the number of containers in Circle CI to 2
Closes #4137

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by palash25** [comment]
Please reference the issue in your commit message.

**Comment by aryanshar** [comment]
Already rebased before sending a PR!

**Comment by damngamerz** [comment]
ack 6fa75dd35685c1a644a7c264ccd85374864348cd

**Comment by yukiisbored** [comment]
@rultor merge

**Comment by yukiisbored** [comment]
@aryanshar Hey, can you rebase this PR?

**Comment by aryanshar** [comment]
@yukiisbored  Yeah Rebased Now !

**Comment by yukiisbored** [comment]
reack

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala/pull/4684/commits/0a01ef75580a42aca8f8335a6aab9ec2b78c6344

**Comment by yukiisbored** [comment]
@rultor please merge

**Pull request merged**
