### PR TITLE
Development_Setup.rst: Fix Broken Links

### LINKED ISSUE #5556: Fix broken links in Development_Setup.rst
There are two broken links in  [Development Setup Notes](https://api.coala.io/en/latest/Developers/Development_Setup.html):

1. In _venv_ section:
> Now you can activate the environment and start [the next part](https://api.coala.io/en/latest/Developers/Development_Setup.html#id1).

Which should probably point to _Repositories_ section(?)

2. In _Using virtualenv_ section:
> After this, you can start [installing from git](https://api.coala.io/en/latest/Developers/Development_Setup.html#id1).

Which should point to _Installing from Git_ 

It looks like issue for newcomers.

### PR DESCRIPTION
**Pull request by starkblaze01**
This fix Broken Links in venv and
virtualenv section. 
Fixes #5556 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by chhabrabhishek** [comment]
Hey! I think your code is quite satisfying but your commit message is incorrect based on the community commit guidelines. So I suggest you to please change your commit message.
You can refer to http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html for correcting your commit. Also use Fixes/Fix instead of closes because you are dealing with a bug issue.

**Comment by starkblaze01** [comment]
Hello, thanks for pointing this out.
I have replaced closes - - > fixes in comment. 
Also, I have gone through the link which you provided.
Can you please suggest any more changes if needed.

**Comment by chhabrabhishek** [comment]
You don't have a commit message body like shown in the examples provided in the link.
And nor you have added which issue you have closed in your commit message.
Please note that the commit messages here are multiline. 
First you have to add the file name with changes.
Second you must add description of the changes
Third you must add which issue you have fixed.
I suggest you to check how to add multiline commit messages.

**Comment by starkblaze01** [comment]
@chhabrabhishek, Thanks for the guidance, I have made necessary changes, please review it.
Can you also please help me with why one test is failing?

**Comment by jayvdb** [comment]
That was a transient error - a timeout in installation.

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5557/commits/236508696c6dff915fd18bfafaade77c41cf5527

**Pull request merged**
