### PR TITLE
deps.sh: Modify `<` to `!=` operator in the deps.sh

### LINKED ISSUE #4137: Error if circle containers is >2
https://github.com/coala/coala/issues/3352 prevented less than 2 containers, but allows more, which waste resources

Opened via [gitter](https://gitter.im/coala/coala/?at=590020ba587a245e244b95ea) by @jayvdb

### PR DESCRIPTION
**Pull request by girishramnani**
This change will enforce the use of only 2 circle CI containers while testing and hence saving resources. 
Closes #4137 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by SanketDG** [comment]
@girishmahani, change looks good, except for the commit message.

The commit message shouldn't explain the syntax here, but the gist of the issue you are solving.

Something like "Enforce only two containers in Circle" would work better you think? :smile:

**Comment by girishramnani** [comment]
Yeah, totally agree. Will change ASAP.

**Comment by girishramnani** [comment]
Done

**Comment by SanketDG** [comment]
Now you have an extra commit, please remove that. Please come to https://coala.io/chat if you have any problems

**Comment by girishramnani** [comment]
Would this do?

**Comment by SanketDG** [comment]
Yep, commit's gone now.

Now two things:

1. Please mention the full issue url at the end of the commit message (https://coala.io/commit)
2. Rebase (https://coala.io/rebase)

**Comment by girishramnani** [comment]
Done

**Comment by SanketDG** [comment]
ack 93f9072

**Pull request closed without merging**
