### PR TITLE
circle.yml: Add csslint

### PR DESCRIPTION
**Pull request by damngamerz**
Add csslint to circle-ci

Closes https://github.com/coala/coala/issues/3707

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by damngamerz** [comment]
This was the build failure i was getting before fixing!!
screenshot from 2017-02-06 19-27-15
After applying this patch!
screenshot from 2017-02-06 20-53-25

**Comment by supergr35** [comment]
ack 166d8ce

**Comment by jayvdb** [comment]
@rultor merge

**Comment by sils** [comment]
rebasing this for your convenience and to get this merged right now :) https://github.com/coala/coala/pull/3714

**Pull request closed without merging**
