### PR TITLE
appveyor.yml: Remove everything related to LLVM

### PR DESCRIPTION
**Pull request by harshhx17**
Closes https://github.com/coala/coala/issues/5207

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by harshhx17** [comment]
Thanks @monsij  
IMHO the commit body would have increased redundancy for this commit since many changes were not there. If you still feel that it is necessary, I can always make it :wink:

**Comment by alphadose** [comment]
ack f9745c160db702ee89a5ba5ae9581c7ec58af7ee

**Comment by harshhx17** [comment]
@Makman2  Can you please review this :smiley:

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5209/commits/d40db24bba6e0e1e4ddd9f6cffb9a1d5abf8990e

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5209/commits/78e6ef6e39ebb58a1cbc666d19d039ce14829bc9

**Comment by jayvdb** [comment]
ack 78e6ef6

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
