### PR TITLE
Settings.py: fixed typo

### PR DESCRIPTION
**Pull request by ojasgulati**
line_number -> start_line_number

Closes https://github.com/coala/coala/issues/5983

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by kushthedude** [comment]
@ojasgulati 
First of all you didn't let yourself get assigned to the issue .  You made the PR , Let it be but your work was to just change a line. , Why you are committing changes that are not included in the issue , Please follow `coala guidelines for contribution` before making any PR or contribution

**Comment by KVGarg** [comment]
Hi @ojasgulati Looks like your editor has done auto-formatting of the files. Please take a look at the settings and try to push only the required changes.
We won't be able merge the PR until you revert the auto-formatted changes. As maintainers are busy, which is causing the invites to the contributors tool late. I can understand that you want to contribute and waiting for invitation. But you've to wait for some more time. For now, you can push the correct files with changes making sure that no files are being auto-formatted by your editor. Later on once you receive the invitation, we can look forward to merge it. And, if you interested in solving any other issue please don't create a PR for it until its been assigned to you. Maybe other contributors have already solved it. So, please take of this thing in future to avoid such happenings. And, since you have opened this PR let it be open, don't close it. But take care in future :innocent: Enjoy learning + coding :+1:

**Comment by ojasgulati** [comment]
@kushthedude @KVGarg Sorry for the late reply and also for not assigning myself to issue first, I will keep this in mind 😅. I was busy with some other work. I will make changes as mentioned. 
Cheers 😃

**Comment by ojasgulati** [comment]
Sure

**Comment by abhishalya** [comment]
@ojasgulati If you still want to work on this PR, please update it as per the reviews and we'll get it merged, else, you should close this PR, the clutter on the issue is already too much.

**Comment by abhishalya** [comment]
Closing due to inactivity.

**Pull request closed without merging**
