### PR TITLE
#2836, #2847

### PR DESCRIPTION
**Pull request by vreethesh**
Fixes issue https://github.com/coala/coala/issues/2836

### CODE REVIEW

**Comment by sils** [comment]
Hey,

we use some bug prediction in coala which relies on the `Fixes` keyword in commit messages. To get good results from that we need to use `Closes` for normal issues instead of `Fixes` which should only be used for real bugs. (See also [the commit message docs](http://coala.io/commit).)

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by manu-chroma** [comment]
Hey @vreethesh, it appears you had opened [another PR](https://github.com/coala/coala/pull/2837) previously to solve this issue. 
Please close that one. 

Also, your commit message still uses ``fixes`` rather than ``closes``. https://github.com/coala/coala/pull/2857#issuecomment-252865399

**Comment by manu-chroma** [comment]
Do away with the body of the commit specifying line number. Seems redundant.

**Comment by vreethesh** [comment]
@manu-chroma Can be reviewed now. All changes you mentioned have been made.

**Comment by adtac** [comment]
@vreethesh it's just `Closes https://github.com/coala/coala/issues/2836`, not `Closes issue https://github.com/coala/coala/issues/2836` if I'm not mistaken. (I generally hate being this pedantic, but the whole point of this Fixes/Closes thing is for a machine to parse so it'd be helpful if they follow a format.)

**Comment by jayvdb** [comment]
Completed in https://github.com/coala/coala/pull/2869

**Pull request closed without merging**
