### PR TITLE
added "sudo" in installing commands in documentation ( Add `sudo` to the installation guides #4428)

### PR DESCRIPTION
**Pull request by charul97**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Makman2** [comment]
You have accidentally committed unresolved commits, and now git's markers are appearing in the final files. Could you resolve that and squash all commits together? :)

**Comment by charul97** [comment]
E   ValueError: line 25 of the docstring for Bear_Installation_Tool.rst lacks blank after >>>: '>>>>>>>  50014063c6072673d841148d389b9e3b7bbd915c'.
Unable to get through this error although I have already added the blank space.

**Comment by aryanshar** [comment]
Hi @charul97 , I see you,ve got conflicts while rebasing. you have to keep only certain blocks of code in the conflict region
marked within >>>> and <<<< and after resolving the conflicts.. you have to git add those files
and run git rebase --continue

**Comment by Makman2** [comment]
I would recommend to start from ground-up again, copying the relevant parts you've modified by hand, create a new branch and modify again. (If you create a new branch you don't lose your old changes here :+1:)
If you have next time conflicts, don't forget to remove the markers by hand in your editor :+1:

**Comment by charul97** [comment]
I have done reset --hard so that I can now commit again from start rather than making a new branch. I hope it's fine?

**Comment by Nosferatul** [comment]
how's for you easier, it should be fine. Next time when you have this kind of problem you can try to rebase interactive and edit the commits that you need. ( `git rebase -i` )

**Comment by charul97** [comment]
okay, cool :)

**Pull request closed without merging**
