### PR TITLE
Update .coafile

### PR DESCRIPTION
**Pull request by vishal3410**
Issue link - https://github.com/coala/coala/issues/5389

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by anctartica** [comment]
please follow the commit guidelines: https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html :)

**Comment by vishal3410** [comment]
@anctartica Thanks for guidance :)

**Comment by ishanSrt** [comment]
change your commit according to https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by pareksha** [comment]
Hey @anctartica I see you haven't followed the commit guidelines. I cannot see the shortlog and issue link in your commit message. Use ``git commit --amend`` to change your commit message.

**Comment by vishal3410** [comment]
@ishanSrt  , I have changed the commits please check

**Comment by ishanSrt** [comment]
@vishal3410 your commit has unnecessary changes. Are you using the same branch for different issues? Please remove all the extra stuff.

**Comment by ishanSrt** [comment]
@vishal3410 that question is more suited for google and stackoverflow. So fix it! 😉

**Comment by ishanSrt** [comment]
@vishal3410 please go through the newcomer's guide once more and see a git tutorial. Closing PRs is highly discouraged 😕

**Comment by vishal3410** [comment]
Accidently closed trying to reopen

**Comment by jayvdb** [comment]
@vishal3410 , if you commit new changes to your branch, this PR might re-open.

But maybe because you deleted the branch, it may be irreversible.

**Comment by vishal3410** [comment]
so should i submit a new pr ?

**Comment by jayvdb** [comment]
No, do not create a new PR.

You will need to rebase, and repush, and this PR should re-open magically (or I may have to re-open it after you've done that).

Come onto https://coala.io/chat if you need help with that.

**Pull request closed without merging**
