### PR TITLE
LineParser.py: Edit docstring

### PR DESCRIPTION
**Pull request by meetarora29**
### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
- [x] I have followed the [guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference).
- [x] I have [run all the tests](http://coala.readthedocs.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### Reviewers

Edited the param explanations to begin with a
capital letter and end with a dot.

Closes https://github.com/coala/coala/issues/2983

### CODE REVIEW

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/2992/commits/baf316f647ae4a409da230cc34baf291515ff714

**Comment by sils** [comment]
thanks @tulphoon

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
@meetarora29 try to be a bit more precise with the commit message -> `Add periods to docstring` tells me more than just `Edit docstring`, merging this as it is fine for this commit anyway ;)

**Comment by meetarora29** [comment]
@sils Okay, thanks. I'll keep that in mind :)

**Pull request merged**
