### PR TITLE
ConsoleInteraction.py: Move join_names to gitlab

### LINKED ISSUE #3486: move ConsoleInteractions.join_names to coala_utils (on gitlab)
difficulty low

Opened via [gitter](https://gitter.im/coala/community/?at=586f56a4af6b364a29387435) by @sils

### PR DESCRIPTION
**Pull request by vijeth-aradhya**
Move join_names method to coala_utils/string_processing

Closes #3486

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [ ] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### Reviewers

@sils

### CODE REVIEW

**Comment by adtac** [comment]
Um, we can't just remove the function here (tests fail) - don't we need to import it from `coala_utils`? And that can happen only when it's merged over there (gitlab link btw?).

**Comment by adtac** [comment]
And if you're waiting for that to be implemented, I suggest adding a `WIP` to the start of this PR's title.

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3490/commits/f2fdd134136861c218b1fa766a3284c5ca74fd70

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
urgh why didn't mark gitmate that pending review

**Pull request merged**
