### PR TITLE
Testing_Bears.rst: Properly format code examples

### PR DESCRIPTION
**Pull request by ayushin78**
Testing_Bears.rst: Properly format code examples

Closes coala#3774

### CODE REVIEW

**Comment by yash-nisar** [comment]
The changes look good to me !
ack 5ceebcfa67f0f7813401325c7119d82622300620

**Comment by yash-nisar** [comment]
ack 5ceebcfa67f0f7813401325c7119d82622300620

**Comment by Adrianzatreanu** [comment]
this is fine but requires a rebase :) if you need help with that, "cobot explain rebase" might help you if used in the gitter chat

**Comment by userzimmermann** [comment]
@ayushin78 Please do the rebase so that we can merge this :)

**Comment by userzimmermann** [comment]
Oops! Clicked on the `Update branch` button out of pure curiosity :D 

@ayushin78 Sorry! But on the other hand one more reason for rebasing ;)

**Comment by Makman2** [comment]
Closing due to inactivity.

**Pull request closed without merging**
