### PR TITLE
requirements: Upgrade coala-utils to latest

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by Nosferatul** [comment]
ack 9b511cc

**Comment by Nosferatul** [comment]
@rultor merge

**Comment by sils** [comment]
@rultor stop

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
sorry, wrong PR :P

**Comment by sils** [comment]
I thought this was https://github.com/coala/coala-bears/pull/990 which was outdated because I merged a PR in that very second you posted the merge command ;)

**Pull request merged**
