### PR TITLE
package.json: Fixes Indentation

### PR DESCRIPTION
**Pull request by Vedarth**
Fixes indentation by removing leading whitespace

Closes https://github.com/coala/coala/issues/4056

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by yashovardhanagrawal** [comment]
like
>Fixes indentation by removing leading whitespace
>
>Closes #4056

**Comment by yashovardhanagrawal** [comment]
unack https://github.com/coala/coala/pull/4895/commits/06ace9541ffde4868ce3e6972b11a238815432ea

**Comment by yashovardhanagrawal** [comment]
ack https://github.com/coala/coala/pull/4895/commits/11b91c181594327a38e1e6725850dfe6ec47eb27

**Comment by jayvdb** [comment]
unack 11b91c1

**Comment by Vedarth** [comment]
@jayvdb Sorry for the mistake. I didn't know I had to do that as well. Is it alright now?

**Comment by Vedarth** [comment]
@jayvdb I have made the changes you asked but it is failing the tests now.

**Comment by Vedarth** [comment]
@jayvdb Where do you want the `*.json` files in `.coafile` ?
Also, should I change quotation marks?

**Comment by Vedarth** [comment]
@jayvdb I did not change the quotation marks in my commit, yet I am getting an error related to that.

**Comment by jayvdb** [comment]
@Vedarth , the messages by the bot are caused by your change.  Read the bots error messages, as they provide a clue where you've made the mistake.  Also try reading the documentation.

**Comment by Makman2** [comment]
Closing due to inactivity.

**Pull request closed without merging**
