### PR TITLE
README.rst: Add openhub badge to README

### PR DESCRIPTION
**Pull request by yuxiangdai**
Adds an Openhub badge/GIF to the README

Closes https://github.com/coala/coala/issues/4317

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by shreyans800755** [comment]
@yuxiangdai 
Commit looks good.
Can you please update the shortlog: `openhub` -> `OpenHub`

**Comment by shreyans800755** [comment]
unack df2016f

**Comment by yuxiangdai** [comment]
Hi, I didn't mean to commit the merge. How do I fix this?

**Comment by shreyans800755** [comment]
@yuxiangdai 
Next time, make sure you don't click on `Update Branch` button over here, it looks white button, but its a danger red button. :smile: 
To fix this:
`git reset --hard HEAD^`
This command will put you back to your original commit.
Now, you need to pull other commits:
First make sure you have set your origin as `https://github.com/coala/coala` and then run:
`git pull --rebase origin master`

If this rebase gives you any merge conflicts, resolve it manually and then complete the rebase and push it again over here.

You can have a look at coala.io/git.
If you still need any assistance, feel free to ping me on gitter.

**Comment by jayvdb** [comment]
Continued at https://github.com/coala/coala/pull/4361

**Pull request closed without merging**
