### PR TITLE
Development_Setup.rst: Unused target "dev-notes"

### PR DESCRIPTION
**Pull request by IamRaviTejaG**
Removed unused target .. _dev-notes: at line #1

Closes https://github.com/coala/coala/issues/4222

### CODE REVIEW

**Comment by khanchi97** [comment]
According to GitcommitBear the Bad word you have used is `Unused` and you can take help from http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by IamRaviTejaG** [comment]
Hi @khanchi97. I updated the commit message and removed the 'unused' word. But the CircleCI test still fails.

**Comment by khanchi97** [comment]
Hi @IamRaviTejaG I think the problem is you can only use `present tense` in your commit shortlog.Acc. to http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by SanketDG** [comment]
@IamRaviTejaG remove the last commit and instead do a rebase

**Pull request closed without merging**
