### PR TITLE
Fix documentation status badge

### PR DESCRIPTION
**Pull request by Mariatta**
Change back badge image url to readthedocs

Fixes https://github.com/coala/coala/issues/3437

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [ ] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by Makman2** [comment]
what the... why does CircleCI run test on your account... can't restart them... @Mariatta would you mind to repush-force your commit without any changes to retrigger a new build? :)

**Comment by Makman2** [comment]
ack fdd03ea80a081b45a53da9f99483f87e0b284e2d

**Comment by sils** [comment]
5a39d74 reack

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
