### PR TITLE
Collectors: Add separate get_all_bears function

### PR DESCRIPTION
**Pull request by userzimmermann**
Need it for https://github.com/coala/bearsh

@sils

### CODE REVIEW

**Comment by userzimmermann** [comment]
@sils Test is tricky! Is it possible to hack `bear_test_module()` to something like this:

```python
    def test_get_all_bears(self):
        with bear_test_module() as bears:
            self.assertSetEqual(
                set(get_all_bears()),
                {bears.DependentBear,
                 bears.EchoBear,
                 bears.LineCountTestBear,
                 bears.JavaTestBear,
                 bears.SpaceConsistencyTestBear,
                 baers.TestBear})
```

**Comment by userzimmermann** [comment]
Found a much better `test_get_all_bears` solution :D

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3305/commits/534de6c0560e2fe755604dc100aee33d15dcdfeb

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
