### PR TITLE
DefaultArgParser.py: tests for --limit-files

### PR DESCRIPTION
**Pull request by dob9601**
This ensures that there are tests for the --limit-files argument
available that users can use as examples
if need be

Closes https://github.com/coala/coala/issues/4887

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by dob9601** [comment]
I’m aware that this PR has failed most of the checks but am afk at the moment. I will be able to fix this PR either later today or tomorrow morning.

**Comment by dob9601** [comment]
@newbazz I haven’t finished making fixes yet - once all fixes have been made i’m going to squash the commits

**Comment by newbazz** [comment]
@dob9601 yeah thats ok but why dont you do "git commit --amend" everytime you want to commit.

**Comment by dob9601** [comment]
@newbazz I am away from my computer right now and using a mobile client with greatly reduced functionality

**Comment by dob9601** [comment]
@nvzard do you know where the unit tests for the other arguments are? I couldn’t see them so presumed that the creator of the PR wanted the description of arguments updated (there was something that looked vaguely like a unit test in there but wasn’t)

**Comment by newbazz** [comment]
@dob9601 in `tests/parsing/DefaultArgParserTest.py`

**Comment by dob9601** [comment]
Thanks @newbazz

**Comment by SanketDG** [comment]
@dob9601 The `--limit-files` argument acts as an additional filter, so let's say you have all html (`**.html`) in your `--files` arugment and you want to have only those that start with a and end with c, then you pass `a**c` to `--limit-files`

Let me know if its clear.

**Pull request closed without merging**
