### PR TITLE
Sils/trusty

### PR DESCRIPTION
**Pull request by sils**
taking over https://github.com/coala/coala/pull/2827 from @jayvdb 

@AbdealiJK can you review?

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
ack 377fa17dd265fe2e64d59066fdd4e635e42afc61

**Comment by Adrianzatreanu** [comment]
ack a7ae97df5299f5f18b5c9bf6cfad1cea00859d9d

**Comment by Adrianzatreanu** [comment]
rebase needed :)

**Comment by sils** [comment]
reack

5bba24e Circle CI: Avoid staticfloat's julia PPA on trusty
e9ccac5 coafile: Allow spaces before colon

**Comment by sils** [comment]
reack  bb3fac2 Circle CI: Avoid staticfloat's julia PPA on trusty
960b37b coafile: Allow spaces before colon

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
