### PR TITLE
Collectors.icollect: Cache results of globs

### PR DESCRIPTION
**Pull request by underyx**
By adding a very simple caching mechanism to stop `icollect` from doing the same exact work for multiple sections, coala's runtime on a real world project went from 55.73s to 14.06s.

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [ ] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [x] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

**After you submit your pull request, DO NOT click the 'Update Branch' button**

### Reviewers

- @sils 
- @fneu

### CODE REVIEW

**Comment by underyx** [comment]
Marked WIP as there are no tests yet.

**Comment by fneu** [comment]
sils and I consider the design ok, for the reasons you gave on Gitter. Also it seems like everything is already covered by our existing tests, I think this can go through as-is.

**Comment by fneu** [comment]
ack https://github.com/coala/coala/pull/3641/commits/33393c50c3d827f4daeae5ff60b7faadcdc25f0c

**Comment by fneu** [comment]
unack commit message

**Comment by fneu** [comment]
@underyx if you remove the WIP in the commit message and maybe mention the issue (if applicable) we are good to go.

**Comment by sils** [comment]
unack 33393c5

**Comment by underyx** [comment]
Wow, I really didn't expect it to be this easy :D

Alright, ready for merging then I guess!

**Comment by fneu** [comment]
almost.

> sets of iles.

you get to put an extra f into the commit message :)

**Comment by underyx** [comment]
As always, the typos :D

@fneu done

**Comment by fneu** [comment]
ack https://github.com/coala/coala/pull/3641/commits/b7a5c9e0eeddc83e1bb6bae8ab442e037dd1e8cf

**Comment by jayvdb** [comment]
@rultor merge

**Comment by sils** [comment]
reack https://github.com/coala/coala/pull/3641/commits/9c1a7c847df15920508f993b8bd102ffdcc7f182

**Comment by sils** [comment]
just discussing with @userzimmermann would be way simpler to just use `lru_cache` on `glob` and use that

**Comment by sils** [comment]
and deprecate iglob, logging the eprecation and defining iglob to just return `iter(glob(...)` so we don't have unneeded code and make use of the cache always

**Comment by fneu** [comment]
maybe stupid questions but why wouldn't `lru_cache` work on `iglob` and return the respective iterator?
I'm not sure getting rid of iglob is a good idea, at least not without checking that it won't bite us.

**Comment by sils** [comment]
@fneu you know how iterators are mutable objects? If you cache the iterator you're not going to be happy with the result the second time.

**Comment by fneu** [comment]
yeah that's exactly why I'm asking, I know you cannot iter them twice. I had hoped `lru_cache` would save copies of mutables.

in any way we can't really let `iglob` return `iter(glob)`. It's literally implemented the other way around right now (`return list(iglob(pattern))`). We cannot easily, and shouldn't, change how glob works internally, and moving everything into `glob`, making a list there, and letting `iglob` iter that is insane.

So I'd guess we leave `iglob` be and add caching to `glob` only then? I would kinda make sense to have both options available, iterator vs caching. Probably add to the docstrings of both when you should use the other one.

**Comment by sils** [comment]
@fneu point here is: iglob only exists for backwards compatability

**Comment by fneu** [comment]
@sils have you looked at the code? Or is there some major work on it going on that I missed? The whole thing is built on top of iterators yielding from each other. `iglob` iters `_iter_alternatives` and yields from '_iglob', which in turn yields from several relative glob functions.

I see zero benefit in removing the ability to use results as they are coming in, especially since there is a noticable performance hit especially on recursive globs. Even if we run every glob multiple times because of sections and need a cached list and therefore `glob` in all places and never `iglob`: what do we gain?

**Comment by sils** [comment]
I cherry picked this to https://github.com/coala/coala/pull/3706 so we can merge it in one go without so much rebase. You don't need to do anything and it's taken care of that this gets merged, thanks for your contribution!

**Pull request closed without merging**
