### PR TITLE
Add description for arg_parse

### LINKED ISSUE #2811: ConfigurationGathering.py: Missing method parameter in the docstring
Method name : gather_configuration is missing a parameter named arg_parser in the doc string.

### PR DESCRIPTION
**Pull request by anu0012**
This PR fixes #2811

### CODE REVIEW

**Comment by srisankethu** [comment]
Follow this guide to change your commit message -> http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by srisankethu** [comment]
you need to change the commit message not the title. You can do that by using `--amend` flag. You need to issue reference too -> http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference

**Comment by anu0012** [comment]
@srisankethu I have requested a new PR with updated commit message. Can you please check whether it is correct or not ?

**Comment by srisankethu** [comment]
@anu0012 Y did you close this PR?

**Comment by anu0012** [comment]
@srisankethu I thought I have to create new one after changing commit message.

**Comment by srisankethu** [comment]
Are you doing these changes from the Github or  through git?

**Comment by anu0012** [comment]
git

**Pull request closed without merging**
