### PR TITLE
Testing_Bears.rst: Correct the formatting

### PR DESCRIPTION
**Pull request by zhongLxyz**
This commit fixes some formatting issues in the doc file.

Closes https://github.com/coala/coala/issues/3774

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by adtac** [comment]
Hi, @zhongLxyz 

Thanks a lot for the contribution. The change looks alright. However it looks like the email address associated with your Github account is from the one committed with. Can you please use the same email address in both places?

**Comment by prnvdixit** [comment]
@stellargo We should use "Fixes" only on the issues marked "bug". 😃 There is already a PR in wip status for amending this in Newcomer's guide https://github.com/coala/coala/pull/4705 😄

**Comment by stellargo** [comment]
@prnvdixit well the idea behind it was to have new bears, new code, etc for closes as far as I remember. This is closer to solving a bug than adding new code i guess, then again i am not sure :P

**Comment by prnvdixit** [comment]
@stellargo I had discussed this earlier on channel - and I think we agreed that documentation changes (making already working and tested code adhere to the standards) are not bugs. Still, I think it's safe to assume that only those PRs which are patching issues labelled "bug" should use "Fixes".... Still, any maintainer would be in better position to clear this. :smiley:

**Comment by stellargo** [comment]
@prnvdixit ohhh ok seems perfect then :)

**Comment by prnvdixit** [comment]
ack 869cf57d6b75af846ee743d9fc967545c529f600

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@rultor merge

**Comment by adtac** [comment]
@jayvdb circle and travis are still running :3

**Pull request merged**
