### PR TITLE
Update git installation command

### PR DESCRIPTION
**Pull request by nikhil-seth**
Changes git installation command from git-all to git

Issue Fixed : https://github.com/coala/coala/issues/4903

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
ack 50866c2

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
unack b56e993

**Comment by Makman2** [comment]
Please use the full link for the issue reference:
```
Closes https://github.com/coala/coala/issues/4903
```
instead of
```
Closes #4903
```

**Comment by manankalra** [comment]
Hey, I'm new to the community and would like to work on this issue. Can I assign it to myself right away using corobo?

**Comment by prnvdixit** [comment]
@manankalra Actually, it's the PR that you have commented on. If he doesn't make the changes in some days, ping some maintainer on issue thread please.
I don't think much is required to be changed in this PR - ping @nikhil-seth, please do the required changes.

**Comment by nikhil-seth** [comment]
@prnvdixit What all changes are pending?

**Comment by prnvdixit** [comment]
@nikhil-seth See Mischa's comment above - https://github.com/coala/coala/pull/4951#issuecomment-351871039

**Comment by nikhil-seth** [comment]
@Makman2 I've amended the changes but it still shows like "#4903"

**Comment by ishanSrt** [comment]
@nikhil-seth it will show the short url in the browser but you shouldn't use that in the commit message.
ack https://github.com/coala/coala/pull/4951/commits/9493e4903f2e3278fb404f53524e6707481641af

**Comment by Makman2** [comment]
ack 9493e49

**Comment by Makman2** [comment]
@nikhil-seth 
> I've amended the changes but it still shows like 

Like @ishanSrt said, that's okay, GitHub will automatically display the short version regardless if it's a full link. However, when you fetch the history with `git`, you'll see the difference.

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
LLVM installer fetch times out, we have to rebuild later.

**Comment by Makman2** [comment]
@gitmate-bot ff

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
