### PR TITLE
Add a link of linter API documentation for resolve issue #3408

### PR DESCRIPTION
**Pull request by rishikksh20**
### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [x] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by sils** [comment]
code itself looks good, can you squash your commits? The second only fixes an issue you introduced in the first one, we don't want that to appear in our history.

**Comment by Mixih** [comment]
See http://api.coala.io/en/latest/Developers/Git_Basics.html#squashing-your-commits for instructions to squash your commits.

**Comment by rishikksh20** [comment]
@NiklasMM I combined all commits into  single commit.

**Comment by NiklasMM** [comment]
ack e57bf7f

**Comment by Mixih** [comment]
@rultor merge

**Comment by sils** [comment]
please rebase :)

**Comment by rishikksh20** [comment]
@sils I rebased the repo .

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/3450/commits/f8759f2a476946f02f47ff73d53fe9cc775b06d3

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :) You've done your first step to become a coala developer.

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

We would really appreciate it if you could help us with

- [telling us about your experience](http://coala.io/newform)
- [some code reviews](http://coala.io/reviewing) for other newcomers
- fixing at least [a difficulty/low issue](http://coala.io/low)
- fill our [usability survey](http://coala.io/usability)

If you've done those and tell us about it so we can promote you to a coala developer!

We're all volunteers and we're currently struggling to keep this up. Helping all those newcomers is a lot of work and we do need your help so we can continue this for others!

**Comment by rishikksh20** [comment]
Thanks @sils I am looking forward to this.

**Pull request merged**
