### PR TITLE
languages: Add a Text language

### PR DESCRIPTION
**Pull request by Kawzeg**
A plain text language without delimiters

Closes https://github.com/coala/coala/issues/5904

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by palash25** [comment]
@Kawzeg you need to modify existing [tests](https://github.com/coala/coala/blob/master/tests/collecting/CollectorsTest.py#L425-L434) in order for this PR to pass 

Please read the CI logs

**Comment by Kawzeg** [comment]
That should do it, I hope.

**Comment by palash25** [comment]
Not sure why appveyor is failing. Try an empty force push that will run the appveyor job again and it might pass.

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5906/commits/4ce0d3b17d44d5d8de095ee7fc47dbd1b29aa1d4

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
