### PR TITLE
Development_Setup.rst: Remove target "dev-notes"

### PR DESCRIPTION
**Pull request by IamRaviTejaG**
Remove target '.._dev-notes:' at line 1.

Closes https://github.com/coala/coala/issues/4222

### CODE REVIEW

**Comment by SanketDG** [comment]
Can you remove the "#" at "line #1" Its causing a bad reference to another pR

**Comment by IamRaviTejaG** [comment]
@SanketDG Done!

**Comment by SanketDG** [comment]
ack c9c9247

**Comment by SanketDG** [comment]
@rultor merge

**Pull request merged**
