### PR TITLE
aspects: Typo error for classnames in pydoc

### LINKED ISSUE #3827: aspects: Typo error for classnames in pydoc
`:class:coalib.bearlib.aspectclasses.Taste.` This should be something like `:class:coalib.bearlib.aspects.Taste.` . Also replace similar instances of aspectclasses with aspects in the pydoc.

### PR DESCRIPTION
**Pull request by dushyantRathore**
Fixes #3827

### CODE REVIEW

**Comment by Udayan12167** [comment]
I think you can squash all your commits together and make a commit which says `aspects: Change classnames to aspects`. 4 separate commits are not required in the situation.

**Comment by jayvdb** [comment]
Needs rebase

**Comment by supergr35** [comment]
Needs another rebase

**Comment by NiklasMM** [comment]
Can you rebase once more please?

**Comment by supergr35** [comment]
This is probably getting tedious, but this'll need another rebase.

**Comment by NiklasMM** [comment]
reack cbd03f9

**Comment by NiklasMM** [comment]
@rultor merge

**Pull request merged**
