### PR TITLE
Writing_Good_Commits.rst: Reword line

### PR DESCRIPTION
**Pull request by srikanth100**
Drop the word 'only' from the statement 'It should
describe only one change and not more.'.

Closes https://github.com/coala/coala/issues/3258

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Techievena** [comment]
@yash-nisar for acking a PR you gotta comment here. gitmate won't consider reviews as acking

**Comment by srikanth100** [comment]
Should i change the commit again or will this suffice?

**Comment by Techievena** [comment]
just edit the commit message using `--amend` and repush it. 😄

**Comment by srikanth100** [comment]
Done :) please review it :)

**Comment by Techievena** [comment]
ack c05ee45

**Comment by yash-nisar** [comment]
Rebase required

**Comment by Adrianzatreanu** [comment]
this is approved but requires a rebase. please use "cobot explain review" in chat in case youre having trouble, or simply ask us :)

**Comment by srikanth100** [comment]
@Adrianzatreanu @yash-nisar Rebase in the sense git rebase --master?

**Comment by impmihai** [comment]
Yes

**Comment by impmihai** [comment]
ok, looks like something happened. Come on gitter, i will help you :D

**Comment by srikanth100** [comment]
@impmihai i kinda had merge conflicts and trouble with rebasing... :D it was messed up. Is it fine now?

**Comment by impmihai** [comment]
It looks fine to me now 👍

**Comment by srikanth100** [comment]
Is there anything else to be done? @Adrianzatreanu @yash-nisar

**Comment by yash-nisar** [comment]
Looks good to me :) ack 689f86fa9db4991d1a07e5c54f48eb3f8e80f92e

**Comment by adtac** [comment]
ack https://github.com/coala/coala/pull/3734/commits/689f86fa9db4991d1a07e5c54f48eb3f8e80f92e

**Comment by adtac** [comment]
@rultor merge

**Pull request merged**
