### PR TITLE
Re: Change `rtd` for stability

### LINKED ISSUE #5970: Rtd broken
https://readthedocs.org/projects/coala-api/

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

### Notes for reviewers
This PR fixes #5970 

This PR is a remake of "Anmolbansal1" PR #5980 

I've gone through some issues and found that this issue ain't fixed. So I thought I could remind you all on this and get this closed. Thanks @Anmolbansal1 for the PR made. If there's any change needed let me know

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by abhishalya** [comment]
Please add info about the corresponding issue, what the change does, etc. You can follow the commit guidelines as mentioned in the PR checklist.

**Comment by alphaX86** [comment]
Alright one sec.... Updating PR description...

**Comment by alphaX86** [comment]
The issue is fixed it's not related to rtd site. It's based on something else now, @abhishalya IG #5970 can be closed since it's not on ReadTheDocs but something related to repo itself. Will report this soon in new issue

**Comment by abhishalya** [comment]
The issue is about fixing it, and the build there still fails. We would only know all the issues once we are able to get a green build there.

**Comment by alphaX86** [comment]
I agree bro. But I found that it isn't the repo's fault, something is causing issue due to indent error (as far as I tested) but still searching the root cause. One thing is clear, #5970 isn't a fault now. It's on files (searching in progress)

**Pull request closed without merging**
