### PR TITLE
Update range to source_range function SourceRange

### PR DESCRIPTION
**Pull request by kirankonduru**
Fixes https://github.com/coala/coala/issues/3398

### Checklist

- [ ] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [ ] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [ ] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [ ] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [ ] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [ ] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by Mixih** [comment]
please fix gitmate issues. (you can avoid this in the future by running coala before pushing)

**Comment by kirankonduru** [comment]
@Mixih Working on it

**Comment by Mixih** [comment]
squash commit please.. all three are part of the same thing

**Comment by kirankonduru** [comment]
@Mixih I dont know the reason but even after squashing the commits they are not getting grouped together

**Comment by aptrishu** [comment]
@kirankonduru Hey, Ask your queries on our channel (https://gitter.im/coala/coala). Someone will help you. :)

**Comment by Mixih** [comment]
you have a merge commit... you will need to remove that before squashing

**Pull request closed without merging**
