### PR TITLE
Newcomers_Guide.rst: correct grammatical mistake

### PR DESCRIPTION
**Pull request by lollichop**
This corrects the grammatical error and changes it from "to to" --> "to".

Closes https://github.com/coala/coala/issues/5087

### CODE REVIEW

**Comment by vibhanshuvaibhav** [comment]
Use `Closes` in place of `Fixes` as it just adds a feature/enhancement and does not fix a bug.

**Comment by newbazz** [comment]
Yeah my bad, and change the title from Fix a typo to `correct grammatical mistake`

**Comment by vibhanshuvaibhav** [comment]
@newbazz  This pull request is being submitted from the fork's master branch. It should be submitted from a different branch.

**Comment by newbazz** [comment]
@vibhanshuvaibhav ohh ya my bad ;P

**Comment by newbazz** [comment]
@lollichop close this PR and file a new one from another branch.

**Pull request closed without merging**
