### PR TITLE
CSharp.py:Add fields for CSharp lang support

### PR DESCRIPTION
**Pull request by rishikksh20**
This commit add fields string_delimiters and comment_delimiters

Fixes https://github.com/coala/coala/issues/3514

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [x] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by nemaniarjun** [comment]
Basically good, but you need to change your commit message shortlog (the first line)
Look at https://coala.io/commit

**Comment by Asnelchristian** [comment]
uhm your test are failing, @rishikksh20

**Comment by Asnelchristian** [comment]
but this looks good

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala/pull/3524/commits/ae69158771785a21db33967f1f7fe4a6dade51bc

**Comment by Asnelchristian** [comment]
@rultor merge

**Comment by Asnelchristian** [comment]
we don't past tense in commit log, modify your commit body to use present tense

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala/pull/3524/commits/cb2ea278995c8640852ae48182cc4404a26fffe2

**Comment by Asnelchristian** [comment]
@rultor merge

**Pull request merged**
