### PR TITLE
DocBaseClass.py: move class to new file

### PR DESCRIPTION
**Pull request by troublemagnet**
Rename the existing DocBaseClass.py to DocumentExtraction.py
and move the DocBaseClass to a new DocBaseClass.py

Closes https://github.com/coala/coala/issues/4507

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by troublemagnet** [comment]
@SanketDG Sir Can you tell me why travis-ci build failed?

**Comment by SanketDG** [comment]
@troublemagnet thanks for the PR!

However your commit message is not correct, the first letter after the tag should be capitalized.

**Comment by troublemagnet** [comment]
@SanketDG fixed :)

**Comment by SanketDG** [comment]
@troublemagnet almost done.

So the file name has to be `DocumentationExtraction.py`

**Comment by SanketDG** [comment]
@troublemagnet do you need help with this? You need to squash your three commits

See this https://asciinema.org/a/11269

**Comment by troublemagnet** [comment]
I'm so sorry. Actually I'm traveling. I'll get working on this tomorrow for sure. Really sorry for the delay.

**Comment by hemangsk** [comment]
@troublemagnet no worries, thanks a ton for the PR. so I'm labelling it as work in progress for now, don't worry as soon as you push next time, this label 'work in progress' will get removed by gitmate-bot. :) 👍

**Comment by troublemagnet** [comment]
I tried squashing but kind of screwed up things. I'll open a new PR.

**Pull request closed without merging**
