### PR TITLE
README: Fix pypi issue

### PR DESCRIPTION
**Pull request by Asnelchristian**
pypi is not rendering README.rst

### CODE REVIEW

**Comment by adtac** [comment]
ack https://github.com/coala/coala/pull/2767/commits/fffbb704ecf37ae1ca21d74d94f2c4439c1118b7

**Comment by Asnelchristian** [comment]
reack https://github.com/coala/coala/pull/2767/commits/14febcc25938b670702784b00f3a5fe0ef752050

**Comment by Asnelchristian** [comment]
reack https://github.com/coala/coala/pull/2767/commits/8ba2f40485e9d06c25cd450198f06b281414fdc7

**Comment by Asnelchristian** [comment]
reack https://github.com/coala/coala/pull/2767/commits/2ba64c09cbc4aa7563ad45a89ed9107baf76a0c1

**Comment by Asnelchristian** [comment]
@rultor merge

**Comment by Asnelchristian** [comment]
@rultor merge

**Comment by Asnelchristian** [comment]
@rultor stop

**Comment by adtac** [comment]
reack https://github.com/coala/coala/pull/2767/commits/0a3ab8952d11b121d097847e213ad88894541a53

**Comment by Asnelchristian** [comment]
reack https://github.com/coala/coala/pull/2767/commits/0a3ab8952d11b121d097847e213ad88894541a53

**Comment by adtac** [comment]
@rultor merge

**Pull request merged**
