### PR TITLE
Add arg_parser doc

### PR DESCRIPTION
**Pull request by amrandahvur**
ConfigurationGathering.py: Add arg_parser doc

Add parameter arg_parser and its definition in the docstring

Closes https://github.com/coala/coala/issues/2811

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Hi,

it seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.io/commit !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by adtac** [comment]
Please remove the merge commit.

**Comment by sils** [comment]
A rebase will get rid of it

**Comment by amrandahvur** [comment]
Working on it

**Comment by amrandahvur** [comment]
@adtac Removed, Please Check if my commit message is appropriate

**Comment by sils** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.io/git) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Comment by amrandahvur** [comment]
@sils Done. Please Check ?

**Comment by sils** [comment]
Hey @amrandahvur do you think that gitmate comment is useful? We're doing this on all PRs upon opening now. (That you're getting this multiple times is a bug.) Anything you'd change in addition?

**Comment by sils** [comment]
ack https://github.com/coala/coala/pull/2850/commits/e53e52a5fd610d73f85146445c4045e1693f8360

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

You can help us a lot by filling out <http://coala.io/newform>!

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

We would really appreciate it if you could help us with

- some code reviews for other newcomers
- fixing at least a difficulty/low issue

We're all volunteers and we're currently struggling to keep this up. Helping all those newcomers is a lot of work and we do need your help so we can continue this for others!

**Comment by amrandahvur** [comment]
@sils Yes, I agree, its a very good initiative. However, I am unable to check the boxes on the checklist. Please check upon that. Otherwise, Its a great initiative and will definitely help the newcomers like me. :D

**Comment by amrandahvur** [comment]
@sils Also, Should i click on "Delete Branch" after it has been merged ? Is it also evil just like "Update Branch" ?

**Comment by sils** [comment]
we don't care, it's on your fork, update branch is evil because it adds a
merge commit. After the merge what you do with your branch doesn't affect
the repo anymore

**Comment by amrandahvur** [comment]
@sils Thank You :D

**Pull request merged**
