### PR TITLE
Writing_Good_Commits.rst: Change font size

### PR DESCRIPTION
**Pull request by hemangsk**
### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
- [x] I have followed the [guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference).
- [x] I have [run all the tests](http://coala.readthedocs.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### Reviewers

Ensures that "More Examples" has font size of a subheading.
Replaces - with ~.

Fixes http://github.com/coala/coala/issues/3139

### CODE REVIEW

**Comment by aptrishu** [comment]
ambiguity in commit message 
`Replaces with - with ~.`

**Comment by hemangsk** [comment]
Removed ambiguity in commit message.

**Comment by Mixih** [comment]
Instead of  `Ensures that "More Examples" has font size of a subheading.
Replaces - with ~.`, try `Ensures that "More Examples" has font size of a subheading by replacing - with ~.`
;)

**Comment by aptrishu** [comment]
Change the commit shortlog to something like `Change font size of L139` . Also in your `Fixes ` section in commit message change http to https .

**Comment by Mixih** [comment]
I'd even suggest just saying you changed it form a heading to a sub heading so it's even clearer.

**Comment by aptrishu** [comment]
1. Fix the Gitmate issues. (break the line in commit body into two lines, for more info see https://coala.io/commit)
2. change the commit shortlog(header).

**Comment by aptrishu** [comment]
ack 7cf78fb

**Comment by aptrishu** [comment]
@rultor merge

**Pull request merged**
