### PR TITLE
Review.rst: Indent correctly Review file

### PR DESCRIPTION
**Pull request by DanRadulescu962**
New indentation of block 5 of the file as it
considered block 6 to be the start of a new
list

Fixes https://github.com/coala/coala/issues/3249

### Checklist

- [ ] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [ ] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [ ] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [ ] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [ ] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [ ] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by Nosferatul** [comment]
`Fixes` -> `Closes` . Run coala locally to resolve the problems for gitmate-bot

**Comment by Mixih** [comment]
Don't open new pulls for the same issue!!!! Instead, amend you commits(see the git guide for more info)

**Comment by Mixih** [comment]
amend previous pull please

**Comment by Mixih** [comment]
Eh good enough...

**Comment by Mixih** [comment]
ack 7b722e

**Comment by Mixih** [comment]
ack 74b722e

**Comment by Mixih** [comment]
ack 74b722e

**Comment by Mixih** [comment]
@rultor merge

**Pull request merged**
