### PR TITLE
Change pip requirement : pip>=6

### PR DESCRIPTION
**Pull request by mamakancha**
### Check list

- [x] I have rebased properly.
      [Please see this for a tutorial.](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing)
- [x] I have gone through the
      [commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html)
      and I've followed them:
 - [x] I have followed the
       [guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
 - [x] I have followed the
       [guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
 - [x] I have included the issue URL with the  `Fixes` keyword if the
       commit fixes a *real bug* and the `Closes` keyword if it adds a
       feature/enhancement.
       [See more here.](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference)
- [x] I have [run all the tests](http://coala.readthedocs.io/en/latest/Developers/Executing_Tests.html)
      and they all pass. If any CI (below) is not green, please fix them. If
      GitMate issues appear you will have to amend your commits, pushing new
      commits on top is not sufficient!

### Reviewers

Fixes Issue : https://github.com/coala/coala/issues/2934#event-843617803

### CODE REVIEW

**Comment by mamakancha** [comment]
I have fixed the issue : https://github.com/coala/coala/issues/2934#event-843617803 

The requirement of this issue was to change the pip requirements in README.srt which has been done by me successfully

**Comment by AbdealiJK** [comment]
Hey, as you can see gitmate complained about your commit message. Please re-read the commit message guidelines and fix it up

**Comment by mamakancha** [comment]
"Shortlog of HEAD commit does not match given regex"
Can somebody explain me this?

**Comment by Adrianzatreanu** [comment]
Yes, its on coala.io/commit.

Basically, you need to do something like: ``file_name: Action that is being done``

**Comment by mamakancha** [comment]
I am closing the current pull request and will be making a new pull request in order to try to rectify the errors.

**Pull request closed without merging**
