### PR TITLE
Compatibility.py: Added comment

### PR DESCRIPTION
**Pull request by shreyateeza**
Added comment explaining JSONDecodeError available from Python 3.5.x

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
Hi @shreyateeza ,

In case you are stuck somewhere with git. Or need any help.
You can ask us here. Or on gitter. And we'll be happy to help 
you out. :)

Once the changes requested are done. This PR would be
good to merge.

**Comment by shreyateeza** [comment]
closes #4943

**Comment by mridubhatnagar** [comment]
@shreyateeza. Why you have closed this PR?

**Comment by shreyateeza** [comment]
Sorry for this. But I have opened a new pull request #4956 .

**Comment by prnvdixit** [comment]
@shreyateeza Please, don't close PRs - In case, you need any help regarding git just ping on gitter channel, someone would be around to help you. 👍
Closing a PR is rarely needed 😄

**Pull request closed without merging**
