### PR TITLE
Required changes made

### LINKED ISSUE #5123: RELEASE_NOTES.rst : Typo Error
Spelling mistakes like 'availibility', 'ben', 'modifyable', 'seperation', 'libary' along with some grammatical errors are present in file coala/RELEASE_NOTES.rst

### PR DESCRIPTION
**Pull request by richa208**
This fixes the typo errors in RELEASE_NOTES.rst
Fixes #5123 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by monsij** [comment]
Also change  Fixes #5123 to Closes #5123 as the issue isn't a bug.

**Comment by monsij** [comment]
@richa208  Change commit shortlog from typo errors to Correct typo as it has to be in imperative mood.

**Comment by ishanSrt** [comment]
@richa208 You are still not using `Fixes` in your commit body. You need to use `Fixes` for bugs and typos in both shortlog and the last line of your commit 😉

**Comment by anctartica** [comment]
yes use `git commit --amend`

**Comment by anctartica** [comment]
yes use `git commit --amend`

**Comment by richa208** [comment]
@ishanSrt I didn't use fixes because as given here http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html , bugs are those which lead to some unintended behaviour from program. So as there were only typo errors in this issue, which cause no such behavior, I thought use of closes would be fine.
But if still I made a mistake I would be very happy to correct it :smiley:

**Comment by ishanSrt** [comment]
@richa208 you got that correct! Apart from that you also have to use `Fixes` for typos. You can see that if you go through the link you provided properly and see all the examples. 👍

**Comment by ishanSrt** [comment]
I might warn you `typos` are not to be confused with other kinds of grammatical or sentential errors

**Comment by richa208** [comment]
Thanks @ishanSrt for the tips :smiley:

**Comment by richa208** [comment]
@Makman2 Can you please look into the failing build?

**Comment by newbazz** [comment]
Try 
`git commit --amend --allow-empty`
`git push -f`

**Comment by Makman2** [comment]
Not a bug, please use "Closes" instead of "Fixes" in your commit message :+1:

**Comment by Makman2** [comment]
unack 71fb232fa52e32889186bc7e837c96e1e34c4c39

**Comment by richa208** [comment]
Hi @Makman2 
Kindly review this PR and suggest any other changes needed.

**Comment by Makman2** [comment]
ack 31be69bc070fe7d76b4de3a18b4d3006dedc44e8

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
