### PR TITLE
Newcomers_Guide.rst: Fix step number typo

### PR DESCRIPTION
**Pull request by rattandeep1998**
This changes the step number from
4 --> 3 in line 306.

Closes https://github.com/coala/coala/issues/4509

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by rattandeep1998** [comment]
Updated. 
Please review it again.
Thanks !!

**Comment by shreyateeza** [comment]
@rattandeep1998 Check the items in the checklist. Also correct fixes --> closes in the comment above. :)

**Comment by rattandeep1998** [comment]
@shreyateeza 
I have checked the items on the checklist. Thanks for pointing it out. :+1: 
Also, I have already changed the commit language from fixes --> closes. This is the link to the same : 
https://github.com/coala/coala/pull/4983/commits/18e9cf2910b24b3a394a236e1fc6b8b4e28dad2b

Thanks !!

**Comment by shreyateeza** [comment]
@rattandeep1998  I meant to say that change fixes --> closes in the comment above. I know that you have amended the commit.

**Comment by shreyateeza** [comment]
@rattandeep1998 Are you getting it?

**Comment by rattandeep1998** [comment]
@shreyateeza 
Yeah, done that :smiley: 
Since its my first PR on the code base, I'll definitely get to learn from here. 
Thanks, again !!

**Comment by RaiVaibhav** [comment]
ack 18e9cf2910b24b3a394a236e1fc6b8b4e28dad2b

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by rattandeep1998** [comment]
@makman2 Any updates regarding this ??
Sorry to ping you up again. 😉
Since its my first PR, can you please let me know the follow up procedure from here and can I take up another issue meanwhile ?
Thankyou !!

**Comment by sangamcse** [comment]
@rattandeep1998 Yes you can work on another issue. Before that, rebase your repository. 
You can read this. It has steps for rebasing http://api.coala.io/en/latest/Developers/Git_Basics.html.

**Comment by rattandeep1998** [comment]
@sangamcse 
That's ok. Cool !! 👍
But shouldn't my this PR be merged before I rebase my local fork ?

**Comment by sangamcse** [comment]
Don't worry about getting merged. You rebase your repository. It won't affect other things. You should check that link. You will be able to understand it. Once it is rebased, you are good to go with other issues.

**Comment by rattandeep1998** [comment]
@sangamcse
Cool. ✌️
Thanks :)

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
https://github.com/coala/coala/pull/5005 takes over.

**Comment by rattandeep1998** [comment]
@Makman2 Any updates regarding this PR ??
Also, how to proceed further from here.
Thanks !!

**Comment by sangamcse** [comment]
@rattandeep1998 This PR is already merged to the master branch of coala. All you need to do now is `git push upstream`. This will update your local repository.

**Pull request closed without merging**
