### PR TITLE
Documentation: Clarify repository install

### PR DESCRIPTION
**Pull request by MikeTheReader**
The 'Installing from Git' section was ambiguous around the repositories
it was referring to. Removed the -e flag from the base repository
install commands and added reference to the forked repository.

Fixes https://github.com/coala/coala/issues/4265

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by underyx** [comment]
Great, thank you so much! Sorry I didn't notice your PR earlier 🙃 

It seems to be perfect on the first try, congrats — that's pretty rare!

I'll just approve it right now:

ack https://github.com/coala/coala/pull/4268/commits/f78e1648b273ce4709e500d7163cf251030ce308

**Comment by underyx** [comment]
ack https://github.com/coala/coala/pull/4268/commits/f78e1648b273ce4709e500d7163cf251030ce308

**Comment by supergr35** [comment]
unack f78e164

**Comment by supergr35** [comment]
Almost perfect, but the problem is in the commit message. Use `Closes` instead of `Fixes` please 👍

**Comment by supergr35** [comment]
ack 76e3a1f

**Comment by sims1253** [comment]
ack 76e3a1f0e8a2e49964303fe47ed71bb986609c51

**Comment by jayvdb** [comment]
merged in https://github.com/coala/coala/pull/4301

**Pull request closed without merging**
