### PR TITLE
coalib/output/ConsoleInteraction.py: Modifies the docstring

### LINKED ISSUE #5843: require_setting docstring contains strange " and following"
In require_setting we see

```
    :param arr:          A list containing a description in [0] and the name
                         of the bears who need this setting in [1] and
                         following.
```

"and following" should be removed.

### PR DESCRIPTION
**Pull request by sourabh1031**
This removes the unnecessary words in the docstring

Closes #5843

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by ayan-b** [comment]
Edit your PR message and add 
```
This removes the unnecessary words in the docstring

Closes #5843
```
on top, as this is the usual convention. Everything else looks good. :+1:

**Comment by sourabh1031** [comment]
Thanks @AkshJain99 for reviewing but please tell me what is the mistake it is written in present and it is following the guidelines as well

**Comment by sourabh1031** [comment]
> Edit your PR message and add
> 
> ```
> This removes the unnecessary words in the docstring
> 
> Closes #5843
> ```
> 
> on top, as this is the usual convention. Everything else looks good. +1



> Edit your PR message and add
> 
> ```
> This removes the unnecessary words in the docstring
> 
> Closes #5843
> ```
> 
> on top, as this is the usual convention. Everything else looks good. +1

Thanks @ayan-b

**Comment by ayan-b** [comment]
@sourabh1031 , please read https://coala.io/commit .

**Comment by AkshJain99** [comment]
@sourabh1031 earlier you have not mention the description about the issue solved in the commit message now after your changes it looks fine :thumbsup:

**Comment by ayan-b** [comment]
@sourabh1031 you haven't added the fixes/closes issue part.

**Comment by sourabh1031** [comment]
> @sourabh1031 you haven't added body(optional) the fixes/closes issue part.



> @sourabh1031 you haven't added body(optional) the fixes/closes issue part.

@ayan-b please check it now

**Comment by ayan-b** [comment]
@sourabh1031 I guess shortlog exceeds 50 characters. Can you please check? And also specify the words you remove.

**Comment by jayvdb** [comment]
There is something wrong with your git commit , cause it to not be linked to your account.

You can see it says "Sourabh" but doesnt use your avatar or link to your account.

https://github.com/coala/coala/pull/5845/commits

Ask for help on chat

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
