### PR TITLE
Requirements.txt: dependency_management 0.3.0

### PR DESCRIPTION
**Pull request by rhemon**
Updated the version used right now since there was a fix
in dependency management and got a new release. Also
changed coala-utils version to 0.6, after seeing error
in the tests.

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [x] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by vijeth-aradhya** [comment]
LGTM :smile: This will also help my PR pass tests.
It's good if you include `coala_utils` version update in your PR message like in your commit message!

**Comment by rhemon** [comment]
done @vijeth-aradhya

**Comment by jayvdb** [comment]
We could also remove the `coala_utils` line from this requirements, as we have `dependency_management` and it depends on `coala_utils`.

But these can be easily managed together.

**Comment by jayvdb** [comment]
ack f32f273

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
