### PR TITLE
Notepadqq

### PR DESCRIPTION
**Pull request by guilherme-p**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by palash25** [comment]
@guilherme-p why don't you fix all the issues raised by gitmate first and repush. After that we can discuss why the CIs are failing.

**Comment by palash25** [comment]
also squash your commits into one and please don't use non-sensical shortlogs like `Git is retarted` like you have used in this PR as your 2nd commit. coala is a mature project and commit shortlogs like that won't look good in the git log. :wink:

**Comment by palash25** [comment]
After looking at the CI logs I don't think we will have any problems once you fix the issues raised by gitmate and repush since the CIs are failing due to formatting issues. :smile:

**Comment by guilherme-p** [comment]
Sorry @palash25, I wrote that message on my own fork, forgot I would include that commit.

**Comment by palash25** [comment]
No need to be sorry just be careful the next time. We all write stupid commits in our projects :wink:

**Comment by palash25** [comment]
@guilherme-p don't close your PR reopen this and push again after solving the issues

**Comment by palash25** [comment]
closing the PR wouldn't solve the issues raised by gitmate :wink:

**Comment by palash25** [comment]
I see that you have made a new PR but this is a bad practice and you shouldn't make multiple PRs for one issue and shouldn't close them like this just make the changes and push to the same PR @guilherme-p

**Pull request closed without merging**
