### PR TITLE
ConsoleInteraction.py: Use middle dot instead of bullet

### PR DESCRIPTION
**Pull request by aptrishu**
### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [x] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### CODE REVIEW

**Comment by aptrishu** [comment]
cc @Makman2

**Comment by Makman2** [comment]
you've changed `spaces='default'` to `spaces=True`. Is there a difference?

**Comment by aptrishu** [comment]
No, there is no difference. @Makman2 
spaces = True -> displays middle dot in place of visible spaces
spaces = False -> displays nothing
spaces = single character string -> displays that single character in place of spaces
spaces = anything else(like more than one character string) -> display middle dot in place of spaces.

**Comment by Makman2** [comment]
ack 41c48dc

**Comment by Makman2** [comment]
rebase and lgtm :)

**Comment by sils** [comment]
204b8ab reack

**Comment by aptrishu** [comment]
@rultor merge

**Comment by sils** [comment]
@aptrishu I'll batch merge a lot of PRs after all this reviewing so don't bother with the rebase

**Comment by aptrishu** [comment]
Thanks for that. :)

**Comment by sils** [comment]
I cherry picked your commit on https://github.com/coala/coala/pull/3563 because we have so many PRs ATM and that would end in rebase hell.

**Pull request closed without merging**
