### PR TITLE
BearTest: Add test for SEE_MORE

### PR DESCRIPTION
**Pull request by newbazz**
Closes https://github.com/coala/coala/issues/4892

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by newbazz** [comment]
please review

**Comment by newbazz** [comment]
@jayvdb review so i can start working on the second one.

**Comment by newbazz** [comment]
@acashmkj changes made.

**Comment by newbazz** [comment]
@Asalle nope not yet mostly....

**Comment by Asalle** [comment]
ack 0ebb87cc65a4247d9d44aca970abf22dda6c65fa

**Comment by jayvdb** [comment]
unack 0ebb87c

**Comment by newbazz** [comment]
When `SEE_MORE` is set means?

**Comment by newbazz** [comment]
@jayvdb i did not find a place where it is set.

**Comment by jayvdb** [comment]
You need to create a unit test with a bear that has `SEE_MORE` set.

**Comment by newbazz** [comment]
image
@jayvdb that is what i was asking that i did not see any file where it is being set, do i need to set its value on my own?

**Comment by newbazz** [comment]
image
@jayvdb that is what i was asking that i did not see any file where it is being set, do i need to set its value on my own?

**Comment by Vamshi99** [comment]
@newbazz you are checking in the wrong repository. Checkout which bear has SEE_MORE attribute here https://github.com/coala/coala-bears/tree/master/bears . For example ApertiumLintBear has SEE_MORE attribute .

**Comment by newbazz** [comment]
How to import class from another repo? @Vamshi99

**Comment by newbazz** [comment]
@can someone help me out, i wanna sove this issue

**Comment by newbazz** [comment]
@jayvdb what can i do to set the SEE_MORE ? Help needed

**Comment by Makman2** [comment]
👉  https://github.com/coala/coala/issues/4892#issuecomment-347041181

**Comment by Makman2** [comment]
Referenced issue is invalid, thus closing.

**Pull request closed without merging**
