### PR TITLE
Fix for issue #4534

### LINKED ISSUE #4534: ConfigurationGathering.py: Add :return: for warn_config_absent
https://github.com/coala/coala/blob/master/coalib/settings/ConfigurationGathering.py#L138
difficulty/newcomer

### PR DESCRIPTION
**Pull request by IamRaviTejaG**
UPDATE ConfigurationGathering.py

Added the :return: statement documentation at L#152.

Closes #4534

### CODE REVIEW

**Comment by IamRaviTejaG** [comment]
Hi @IpshitaC, I have updated the commit message. Please let me know about any further changes.

**Comment by SanketDG** [comment]
@IamRaviTejaG you have to update your commit message in your local branchhttps://help.github.com/articles/changing-a-commit-message/

**Comment by IamRaviTejaG** [comment]
@SanketDG Hello and thanks for the help article. I have updated the commit message now.

**Comment by SanketDG** [comment]
ack 2bf09f1

**Comment by SanketDG** [comment]
unack 2bf09f1

**Comment by SanketDG** [comment]
@IamRaviTejaG Could you change the commit message to something more descriptive? Like:

`ConfigurationGathering: Update docstring`

**Comment by SanketDG** [comment]
ack be6fc42

**Comment by SanketDG** [comment]
@rultor merge

**Pull request merged**
