### PR TITLE
Update Newcomer_Guide.rst : Clarify push command

### PR DESCRIPTION
**Pull request by susg**
Clarify push command in  [Newcomer_Guide.rst](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-4-sending-your-changes)
Closes https://github.com/coala/coala/issues/4485

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Makman2** [comment]
Could you adapt the commit message a bit, so it resembles what you've done? You can actually take the issue title.

Also please use `Closes` instead of `Fixes` in the commit body. We use `Fixes` only for bugs (we will use that somewhen for bug prediction)

**Comment by Makman2** [comment]
But the changes look good ;)

**Comment by susg** [comment]
Is it ok now ?

**Comment by susg** [comment]
is it ok now ?

**Comment by Makman2** [comment]
You have to modify the commit, not the pull request :)
Please read up on our newcomer guide, there's described how you can achieve that :+1:

**Comment by susg** [comment]
can you check this pull request: https://github.com/coala/coala/pull/4585

**Comment by Makman2** [comment]
Please don't reopen new PRs just because the history is not yet nice. You can always change commits in a PR. Really read up on our newcomer guide please, everything is described there :+1: 😄

**Comment by shreyans800755** [comment]
@susg Change short log `Clarify` -> `Improvise`.

Changes are good to merge. Add suitable description in commit and @IpshitaC mentioned and we're good to go.

**Comment by Makman2** [comment]
@shreyans800755 do you mean `improve` instead of `improvise`? Improvising is something totally different ;)

**Comment by shreyans800755** [comment]
@Makman2 Oh yeah, my bad ! `Clarify` -> `Improve`

**Comment by IpshitaC** [comment]
ack a63e853d0d315b8fb607f3bfa77cdc576e742496

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
hm `gitmate rebase base/master` doesn't work, it has to be `gitmate rebase master`. @susg can you rebase manually?

**Comment by swapagarwal** [comment]
ack f36020704467ad5f4dcccca52d198e907700c134

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
