### PR TITLE
AppveyorCI: Create nuget package for llvm 3.4

### PR DESCRIPTION
**Pull request by Techievena**
Install llvm via nuget and then cache it
for further builds.

Closes https://github.com/coala/coala/issues/3726

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Techievena** [comment]
Getting this 
```
Restoring NuGet package LLVMSharp.3.4.0.
  GET https://www.nuget.org/api/v2/Packages(Id='LLVMSharp',Version='3.4.0')
  NotFound https://www.nuget.org/api/v2/Packages(Id='LLVMSharp',Version='3.4.0') 44ms
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='LLVMSharp'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='LLVMSharp' 99ms
WARNING: Unable to find version '3.4.0' of package 'LLVMSharp'.
  C:\Users\appveyor\.nuget\packages\: Package 'LLVMSharp.3.4.0' is not found on source 'C:\Users\appveyor\.nuget\packages\'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'LLVMSharp.3.4.0' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  C:\Program Files\Microsoft SDKs\Service Fabric\packages\: Package 'LLVMSharp.3.4.0' is not found on source 'C:\Program Files\Microsoft SDKs\Service Fabric\packages\'.
  https://www.nuget.org/api/v2: Package 'LLVMSharp.3.4.0' is not found on source 'https://www.nuget.org/api/v2'
```

When I saw the version history of LLVMSharp oldest was `3.6.0`

**Comment by Techievena** [comment]
`Error	D8045 cannot compile C file 'bindings\ocaml\analysis\analysis_ocaml.c' with the /clr option	LLVMSharp	C:\Users\dell\Desktop\llvm\llvm-3.4.1\cl	1` Getting this error while building source code of llvm3.4.1 in Visual Studio 2015. 
Any help on this 😟 @jayvdb

**Comment by adhikasp** [comment]
@Techievena Maybe I am missing something here, but why don't you use the prebuild binary from <http://releases.llvm.org/download.html>? They have v 3.4.1.

**Comment by Techievena** [comment]
@adhikasp For uploading a package to NuGet a .sln file was needed in the package. The built-in binary didn't contain any such files. :worried:

**Comment by Techievena** [comment]
I have created this package by building the source code of llvm 3.4.1 in VS 2015. I don't get why the tests are failing. I am a bit unsure with nuspec file.  Here it is. Please check if anything is wrong with this. http://pastebin.com/AfzkGCGi

**Comment by Mixih** [comment]
Upon discussion with @Techievena on the gitter channel( [link] (https://gitter.im/coala/coala?at=58d9661d4cb8d09173315e7f) ) we have decided to mark this blocked as it would be cleaner to wait for #3854 to get merged

**Comment by Mixih** [comment]
blocked by #3854

**Comment by Mixih** [comment]
blocked by #3857

**Comment by jayvdb** [comment]
Missing coverage of parts of `Diff.py`

**Comment by Mixih** [comment]
seems like an appveyor thing.... This used to happen in the past.

**Comment by jayvdb** [comment]
llvm has been removed from this repo.

**Pull request closed without merging**
