### PR TITLE
Changed writer to author, closes issue #2707

### PR DESCRIPTION
**Pull request by anshuman73**
Solves a simple issue to make logs look better.
Solves issue #2707

### CODE REVIEW

**Comment by anshuman73** [comment]
The cirlceci test fails because of a typo in the commit message. Can fix using git commit --amend, but would require to force push
is it suggested ?

**Comment by Adrianzatreanu** [comment]
hey, i have invited you to our org, contact us on gitter https://gitter.im/coala/coala for more information :D thats where we all hang actively. btw, you can accept it by mail or at github.com/coala

also, your commit message requires some work, follow thi stutorial to make it better, please:

Hi,

it seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.io/commit !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by Nosferatul** [comment]
⬆️ Without "`".
Also you should rebase!
Rebasing
As people work on coala new commits will be added. This will result in your local fork going out of sync with the remote repository. To sync your changes with the remote repository run the following commands in the desired branch:

`$ git fetch origin`
`$ git rebase origin/master`

This will fetch the commits from the remote repository and will merge it into the branch where you are currently working, and move all of the local commits that are ahead of the rebased branch to the top of the history on that branch.

Note

After following these instructions when you try to push to remote you may get fast-forwarding error. If that is the case, then you will have to force push since you are attempting to rewrite the git commit history. To do that append the --force argument in the push command:

`$ git push myfork --force`

Warning: Never force-push on the master branch, or any branch not owned by you.

**Comment by anshuman73** [comment]
Hi, it seems this issue was solved by someone else before I could work on correcting my git faults.
Sorry for being unresponsive for a while.
I'll be closing this pull request as I believe it of no use now :/

**Pull request closed without merging**
