### PR TITLE
Writing_Linter_Bears.rst: Link to API documentation

### PR DESCRIPTION
**Pull request by andreiraduta1101**
The text "API documentation" links now to
"http://api.coala.io/en/latest/".

Closes coala/documentation#21

### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [x] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

### Reviewers
@Adrianzatreanu 
@userzimmermann

### CODE REVIEW

**Comment by andreidinu** [comment]
The word 'link' in your description should be 'links'. Also no ':' after 'Closes'. Be sure to solve your GitCommitBear error.

**Comment by userzimmermann** [comment]
ack https://github.com/coala/coala/pull/3287/commits/1a3699a4db86addf8e5e40ecf68ae9e6cb23670a

**Comment by userzimmermann** [comment]
@rultor merge

**Comment by sims1253** [comment]
@rultor merge

**Pull request merged**
