### PR TITLE
Revert "LICENSE: Remove boilerplate stuff"

### PR DESCRIPTION
**Pull request by adtac**
This reverts commit 2d7ee93d4b8693b2a37c927813aba643d0ffdc6b.

That stuff is very important apparently.

### Checklist

- [ ] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [ ] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [ ] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [ ] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [ ] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [ ] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

**After you submit your pull request, DO NOT click the 'Update Branch' button**

### CODE REVIEW

**Comment by hemangsk** [comment]
ack 264c537

**Comment by Mixih** [comment]
rebase and it should work

**Comment by adtac** [comment]
@Mixih rebased :+1:

**Comment by sils** [comment]
I cherry picked this to https://github.com/coala/coala/pull/3706 so we can merge it in one go without so much rebase. You don't need to do anything and it's taken care of that this gets merged, thanks for your contribution!

**Pull request closed without merging**
