### PR TITLE
Release 0.10

### PR DESCRIPTION
**Pull request by Mixih**
### Checklist

- [x] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [x] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [x] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [x] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [x] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference section in our commit guidelines](http://coala.io/commit#issue-reference).
- [ ] I have [run all the tests](http://api.coala.io/en/latest/Developers/Executing_Tests.html) and they all pass. If any CI (below) is not green, please fix them. If GitMate issues appear you will have to amend your commits, pushing new commits on top is not sufficient!

**After you submit your pull request, DO NOT click the 'Update Branch' button**

### CODE REVIEW

**Comment by Mixih** [comment]
reack
7fade8b7 Release coala 0.10 PolarBear
053f1fca RELEASE_NOTES: Fix malformed heading
d4ed0e49 RELEASE_NOTES: Add release ascii
e00dc715 RELEASE_NOTES: Add 0.10 release notes
f6af4913 Shell: Use shutil.which on Windows
1ca7de0b ConsoleInteraction: Remove format_str (deprecated)
ceaae310 Revert "coafile: Fix shortlog regex"

**Comment by Mixih** [comment]
reack ceaae3101f6b22210dd31ba2786570c4b91572c7

**Comment by Mariatta** [comment]
ack everything.
Ship it! :tada:

**Comment by Mixih** [comment]
reack
b576f55e Release coala 0.10 PolarBear
edf37176 RELEASE_NOTES: Fix malformed heading
87f95ab7 RELEASE_NOTES: Add release ascii
cf4156c1 RELEASE_NOTES: Add 0.10 release notes
b52e432b Fix bare exception clauses
f6af4913 Shell: Use shutil.which on Windows
1ca7de0b ConsoleInteraction: Remove format_str (deprecated)
ceaae310 Revert "coafile: Fix shortlog regex"

**Comment by Mixih** [comment]
@rultor merge

**Pull request merged**
