### PR TITLE
ConsoleInteraction: Fix a typo

### PR DESCRIPTION
**Pull request by raduklb**
Closes https://github.com/coala/coala/issues/5201

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by GlebBerj** [comment]
Typo's been fixed, everything's allright.

**Comment by raduklb** [comment]
@yashovardhanagrawal Is it okay now?

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5285/commits/d448af4ac684b4fa32028e031926a060e4cc8790

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by raduklb** [comment]
@jayvdb Can you please tell me what is wrong? I've previously edited the commit and I had 39 or so characters in the shortlog. Thank you!

**Comment by jayvdb** [comment]
read the gitmate error message above

**Comment by jayvdb** [comment]
And refer to https://coala.io/commit

**Comment by raduklb** [comment]
I thought that the tag is not mandatory, at least that's what it says on "How to write a good commit message" page.

**Comment by yashovardhanagrawal** [comment]
want to finish it fast? 😉 

change you commit shortlog to 
`ConsoleInteraction: Fix a typo`

description:
```
choose_action -> chosen_action
Fixes <issue_url>
```

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala/pull/5285/commits/11d42c656023d587f6b4adf2015e6247bd124861

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
