### PR TITLE
Test cases for FilterHelper

### LINKED ISSUE #4864: Need tests/parsing/FilterHelperTest.py as companion to FilterTest.py
`FilterTest.py` tests bear filtering on a very high level by executing `coala`. An additional `FilterHelperTest.py` should be created for testing the internal features of `coalib.parsing.FilterHelpers` on a lower level. For example, there is currently no test that specifically checks that `InvalidFilterException` (which is currently about to be renamed to `BearFilterTest` by #4856) is raised, which is just not possible in the way `FilterTest.py` performs tests (at least not before #4649 is merged)

@mohit2872 Interested? :)

cc @Makman2 @shreyans800755

### PR DESCRIPTION
**Pull request by saurabhkgp21**
fixes #4864 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

### CODE REVIEW

**Comment by saurabhkgp21** [comment]
@Makman2 how can I check the correct return value of ```apply_filter()``` [here](https://github.com/saurabhkgp21/coala/blob/78e1e7cc04bbbf2de666ebc006fad1ce9b36d663/tests/parsing/FilterHelperTest.py#L10-L14) and [here](https://github.com/saurabhkgp21/coala/blob/78e1e7cc04bbbf2de666ebc006fad1ce9b36d663/tests/parsing/FilterHelperTest.py#L19-L24)

**Comment by Makman2** [comment]
@saurabhkgp21 not sure what you mean, just invoke `apply_filter()`?

**Comment by saurabhkgp21** [comment]
@Makman2, Here I had not compared ```apply_filters()``` with correct values. How can I do it?
For example, we should add something like this:
```assertEqual(correct_value, apply_filter('language', ['C', 'Python']))```
instead of:
```
try:
    apply_filter('language', ['C', 'Python'])
except:
   self.assertFalse(True)
```

**Comment by Makman2** [comment]
sure, sounds good ;)

**Comment by Makman2** [comment]
That it throws an exception, because you've passed strings instead of `Bear`s.

**Comment by Makman2** [comment]
Closing due to inactivity.

**Pull request closed without merging**
