### PR TITLE
Makman2/remove llvm

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by jayvdb** [comment]
This should wait until https://github.com/coala/coala-bears/pull/2211 is merged.  Until then, this is still a core used component, and killing it will break the -bears repo.

**Comment by Makman2** [comment]
https://github.com/coala/coala-bears/pull/2211 is merged.

**Comment by Makman2** [comment]
No reviews, self-acking as per maintainers decision.

**Comment by Makman2** [comment]
ack 4febc53 8910e7f cdd2b98

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
